-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/electronics/cmos_inverter.eml
-- Tier 2: ELECTRONICS

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def V_DD : Real := (3.3 : Real)

axiom vout_at_low_input (v_dd : Real) : Real
axiom vout_at_high_input  : Real
axiom switching_threshold (v_dd : Real) : Real

-- ── low_input_certificate ──

noncomputable def low_input_certificate (v_dd : Real) : Real :=
  v_dd

theorem cmos_low_in_high_out (v_dd : Real) :
    ((low_input_certificate v_dd) = v_dd) := by
  unfold low_input_certificate
  rfl

-- ── high_input_certificate ──

noncomputable def high_input_certificate  : Real :=
  (0 : Real)

theorem cmos_high_in_low_out  :
    ((high_input_certificate ) = (0 : Real)) := by
  unfold high_input_certificate
  rfl

-- ── vm_certificate ──

noncomputable def vm_certificate (v_dd : Real) : Real :=
  (v_dd * (0.5 : Real))

theorem cmos_threshold_positive_when_supply_positive (v_dd : Real)
    (h1 : (v_dd > (0 : Real))) :
    ((vm_certificate v_dd) > (0 : Real)) := by
  unfold vm_certificate
  exact mul_pos h1 (by lit_pos)
