-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/quantum/cnot.eml
-- Tier 7: QUANTUM

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

axiom cnot_control_zero_passes (a : Real) : Real
axiom cnot_self_inverse_amp (a : Real) : Real

-- ── cnot_zero_certificate ──

noncomputable def cnot_zero_certificate (a : Real) : Real :=
  a

theorem cnot_control_zero_fixed (a : Real) :
    ((cnot_zero_certificate a) = a) := by
  unfold cnot_zero_certificate
  rfl

-- ── cnot_involution_certificate ──

noncomputable def cnot_involution_certificate (a : Real) : Real :=
  a

theorem cnot_self_inverse (a : Real) :
    ((cnot_involution_certificate a) = a) := by
  unfold cnot_involution_certificate
  rfl

-- ── prob_witness ──

noncomputable def prob_witness (a : Real) : Real :=
  (a * a)

theorem cnot_probability_witness_squared (a : Real) :
    ((prob_witness a) = (a * a)) := by
  unfold prob_witness
  rfl
