-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/ferronics/ferron_dispersion.eml
-- Tier 6: FERRONICS

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def OMEGA_0 : Real := (1500000000000.0 : Real)
noncomputable def C_F : Real := (1500.0 : Real)

axiom omega_squared (k : Real) (omega_0 : Real) (c_f : Real) : Real

-- ── omega_sq_at_zero_k ──

noncomputable def omega_sq_at_zero_k (omega_0 : Real) (c_f : Real) : Real :=
  (omega_0 * omega_0)

theorem ferron_dispersion_soft_mode_at_zero_k (omega_0 : Real) (c_f : Real) :
    ((omega_sq_at_zero_k omega_0 c_f) = (omega_0 * omega_0)) := by
  unfold omega_sq_at_zero_k
  rfl

-- ── soft_mode_sq_positive ──

noncomputable def soft_mode_sq_positive (omega_0 : Real) : Real :=
  (omega_0 * omega_0)

theorem ferron_soft_mode_sq_positive (omega_0 : Real)
    (h1 : (omega_0 > (0 : Real))) :
    ((soft_mode_sq_positive omega_0) > (0 : Real)) := by
  unfold soft_mode_sq_positive
  exact mul_pos h1 h1
