-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/ferronics/ferron_emission.eml
-- Tier 6: FERRONICS

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def K_EMIT : Real := (1e-22 : Real)

axiom thz_power (p_ddot : Real) (k_emit : Real) : Real

-- ── power_at_zero_drive ──

noncomputable def power_at_zero_drive (k_emit : Real) : Real :=
  (0 : Real)

theorem ferron_emission_zero_drive_zero_power (k_emit : Real) :
    ((power_at_zero_drive k_emit) = (0 : Real)) := by
  unfold power_at_zero_drive
  rfl

-- ── k_emit_certificate ──

noncomputable def k_emit_certificate (k_emit : Real) : Real :=
  k_emit

theorem ferron_emit_constant_positive (k_emit : Real)
    (h1 : (k_emit > (0 : Real))) :
    ((k_emit_certificate k_emit) > (0 : Real)) := by
  unfold k_emit_certificate
  exact h1
