-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/photonics/mach_zehnder.eml
-- Tier 3: PHOTONICS (photon carrier)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

axiom intensity_out (i_in : Real) (dphi : Real) : Real

-- ── intensity_at_zero ──

noncomputable def intensity_at_zero (i_in : Real) : Real :=
  i_in

theorem mach_zehnder_at_zero_phase (i_in : Real) :
    ((intensity_at_zero i_in) = i_in) := by
  unfold intensity_at_zero
  rfl

-- ── cos_sq_at_zero ──

noncomputable def cos_sq_at_zero  : Real :=
  (1 : Real)

theorem mach_zehnder_cos_sq_at_one  :
    ((cos_sq_at_zero ) = (1 : Real)) := by
  unfold cos_sq_at_zero
  rfl
