-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/spintronics/magnon_dispersion.eml
-- Tier 4: SPINTRONICS (magnon carrier)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def GAMMA : Real := (28000000000.0 : Real)
noncomputable def H0 : Real := (0.1 : Real)
noncomputable def D : Real := (5e-17 : Real)

axiom omega (k : Real) (gamma : Real) (h0 : Real) (d : Real) : Real

-- ── omega_at_zero_k ──

noncomputable def omega_at_zero_k (gamma : Real) (h0 : Real) (d : Real) : Real :=
  (gamma * h0)

theorem magnon_uniform_mode_at_gamma_H0 (gamma : Real) (h0 : Real) (d : Real) :
    ((omega_at_zero_k gamma h0 d) = (gamma * h0)) := by
  unfold omega_at_zero_k
  rfl

-- ── fmr_freq ──

noncomputable def fmr_freq (gamma : Real) (h0 : Real) : Real :=
  (gamma * h0)

theorem magnon_fmr_frequency_positive (gamma : Real) (h0 : Real)
    (h1 : (gamma > (0 : Real)))
    (h2 : (h0 > (0 : Real))) :
    ((fmr_freq gamma h0) > (0 : Real)) := by
  unfold fmr_freq
  exact mul_pos h1 h2
