-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/quantum/phase_gate.eml
-- Tier 7: QUANTUM (probability-amplitude carrier)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

axiom r_real (phi : Real) : Real
axiom r_imag (phi : Real) : Real
axiom r_modulus_sq (phi : Real) : Real

-- ── r_real_at_zero ──

noncomputable def r_real_at_zero  : Real :=
  (1 : Real)

theorem phase_gate_real_at_zero  :
    ((r_real_at_zero ) = (1 : Real)) := by
  unfold r_real_at_zero
  rfl

-- ── r_imag_at_zero ──

noncomputable def r_imag_at_zero  : Real :=
  (0 : Real)

theorem phase_gate_imag_at_zero  :
    ((r_imag_at_zero ) = (0 : Real)) := by
  unfold r_imag_at_zero
  rfl

-- ── unitarity_witness ──
-- The witness body is byte-equal to the LHS of MachLib's
-- `pythagorean` axiom; the theorem closes by direct application.

noncomputable def unitarity_witness (phi : Real) : Real :=
  (((Real.sin phi) * (Real.sin phi)) + ((Real.cos phi) * (Real.cos phi)))

theorem phase_gate_unitary_modulus (phi : Real) :
    ((unitarity_witness phi) = (1 : Real)) := by
  unfold unitarity_witness
  exact pythagorean phi
