-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/electronics/pll_loop.eml
-- Tier 2: ELECTRONICS

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def K_VCO : Real := (1000000.0 : Real)
noncomputable def K_PD : Real := (0.5 : Real)

axiom loop_gain (k_vco : Real) (k_pd : Real) : Real
axiom steady_state_error_at_zero_offset (k : Real) : Real

-- ── loop_gain_certificate ──

noncomputable def loop_gain_certificate (k_vco : Real) (k_pd : Real) : Real :=
  (k_vco * k_pd)

theorem pll_loop_gain_positive (k_vco : Real) (k_pd : Real)
    (h1 : (k_vco > (0 : Real)))
    (h2 : (k_pd > (0 : Real))) :
    ((loop_gain_certificate k_vco k_pd) > (0 : Real)) := by
  unfold loop_gain_certificate
  exact mul_pos h1 h2

-- ── ss_error_certificate ──
-- 0 / k = 0  (with k ≠ 0 from h1).

noncomputable def ss_error_certificate (k : Real) : Real :=
  ((0 : Real) / k)

theorem pll_zero_offset_zero_phase_error (k : Real)
    (h1 : (k > (0 : Real))) :
    ((ss_error_certificate k) = (0 : Real)) := by
  unfold ss_error_certificate
  have hne : k ≠ 0 := ne_of_gt h1
  rw [div_def 0 k hne]
  exact zero_mul (1 / k)
