-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/photonics/poisson_spot.eml
-- Tier 3: PHOTONICS

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

axiom axial_intensity (i_0 : Real) : Real

-- ── axial_certificate ──

noncomputable def axial_certificate (i_0 : Real) : Real :=
  i_0

theorem poisson_spot_equals_incident (i_0 : Real) :
    ((axial_certificate i_0) = i_0) := by
  unfold axial_certificate
  rfl

-- ── axial_nonneg ──

noncomputable def axial_nonneg (i_0 : Real) : Real :=
  i_0

theorem poisson_spot_nonneg (i_0 : Real)
    (h1 : (i_0 >= (0 : Real))) :
    ((axial_nonneg i_0) >= (0 : Real)) := by
  unfold axial_nonneg
  exact h1
