-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/photonics/ring_resonator.eml
-- Tier 3: PHOTONICS

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def FINESSE : Real := (200.0 : Real)

axiom transmission (delta : Real) (finesse : Real) : Real

-- ── peak_transmission ──

noncomputable def peak_transmission (finesse : Real) : Real :=
  (1 : Real)

theorem ring_resonator_unity_at_resonance (finesse : Real) :
    ((peak_transmission finesse) = (1 : Real)) := by
  unfold peak_transmission
  rfl

-- ── fsr_separation ──

noncomputable def fsr_separation (c : Real) (n_eff : Real) (L : Real) : Real :=
  ((c * n_eff) * L)

theorem ring_fsr_positive (c : Real) (n_eff : Real) (L : Real)
    (h1 : (c > (0 : Real)))
    (h2 : (n_eff > (0 : Real)))
    (h3 : (L > (0 : Real))) :
    ((fsr_separation c n_eff L) > (0 : Real)) := by
  unfold fsr_separation
  exact mul_pos (mul_pos h1 h2) h3
