-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/spintronics/spin_torque.eml
-- Tier 4: SPINTRONICS

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def GAMMA : Real := (28000000000.0 : Real)
noncomputable def ALPHA : Real := (0.01 : Real)

axiom larmor_frequency (gamma : Real) (h_eff : Real) : Real
axiom damping_prefactor (alpha : Real) : Real

-- ── larmor_certificate ──

noncomputable def larmor_certificate (gamma : Real) (h_eff : Real) : Real :=
  (gamma * h_eff)

theorem spin_torque_larmor_positive (gamma : Real) (h_eff : Real)
    (h1 : (gamma > (0 : Real)))
    (h2 : (h_eff > (0 : Real))) :
    ((larmor_certificate gamma h_eff) > (0 : Real)) := by
  unfold larmor_certificate
  exact mul_pos h1 h2

-- ── prefactor_at_zero_damping ──

noncomputable def prefactor_at_zero_damping  : Real :=
  (1 : Real)

theorem spin_torque_zero_damping_unit_prefactor  :
    ((prefactor_at_zero_damping ) = (1 : Real)) := by
  unfold prefactor_at_zero_damping
  rfl
