-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/carriers/phononics/thermal_rectifier.eml
-- Tier 5: PHONONICS

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def KAPPA_FWD : Real := (25.0 : Real)
noncomputable def KAPPA_REV : Real := (5.0 : Real)

axiom forward_conductance (kappa_fwd : Real) : Real
axiom rectification_ratio (kappa_fwd : Real) (kappa_rev : Real) : Real
axiom asymmetry (kappa_fwd : Real) (kappa_rev : Real) : Real

-- ── forward_positive ──

noncomputable def forward_positive (kappa_fwd : Real) : Real :=
  kappa_fwd

theorem thermal_rectifier_forward_positive (kappa_fwd : Real)
    (h1 : (kappa_fwd > (0 : Real))) :
    ((forward_positive kappa_fwd) > (0 : Real)) := by
  unfold forward_positive
  exact h1

-- ── symmetric_certificate ──
-- kappa - kappa = 0 via sub_def + add_neg.

noncomputable def symmetric_certificate (kappa : Real) : Real :=
  (kappa - kappa)

theorem thermal_rectifier_zero_asymmetry_at_symmetry (kappa : Real) :
    ((symmetric_certificate kappa) = (0 : Real)) := by
  unfold symmetric_certificate
  rw [sub_def]
  exact add_neg kappa
