-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/photonics/components/amplifier.eml
-- P1 Photonic Component Library (2/8)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def G_DEFAULT : Real := (100.0 : Real)

axiom gain (z : Real) (g : Real) : Real

-- ── gain_at_origin ──
-- The optimiser folded `g * 0` to `0` already, so the body
-- reduces to `(1 : Real)` while the ensures says `Real.exp 0`.
-- Bridge with `(exp_zero).symm`.

noncomputable def gain_at_origin (g : Real) : Real :=
  (1 : Real)

theorem amplifier_gain_at_origin (g : Real) :
    ((gain_at_origin g) = (Real.exp (0 : Real))) := by
  unfold gain_at_origin
  exact (exp_zero).symm

-- ── pump_positive ──

noncomputable def pump_positive (g : Real) : Real :=
  g

theorem amplifier_pump_positive (g : Real)
    (h1 : (g > (0 : Real))) :
    ((pump_positive g) > (0 : Real)) := by
  unfold pump_positive
  exact h1
