-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/photonics/mesh/mzi_mesh_2x2.eml
-- P2 Photonic Neural Network (1/5)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

axiom out_top (a : Real) (b : Real) (theta : Real) : Real
axiom out_bot (a : Real) (b : Real) (theta : Real) : Real

-- ── top_at_zero_certificate ──

noncomputable def top_at_zero_certificate (a : Real) (b : Real) : Real :=
  a

theorem mzi_2x2_top_at_zero_is_identity (a : Real) (b : Real) :
    ((top_at_zero_certificate a b) = a) := by
  unfold top_at_zero_certificate
  rfl

-- ── bot_at_zero_certificate ──

noncomputable def bot_at_zero_certificate (a : Real) (b : Real) : Real :=
  b

theorem mzi_2x2_bot_at_zero_is_identity (a : Real) (b : Real) :
    ((bot_at_zero_certificate a b) = b) := by
  unfold bot_at_zero_certificate
  rfl

-- ── norm_witness ──

noncomputable def norm_witness (theta : Real) : Real :=
  (((Real.sin theta) * (Real.sin theta)) + ((Real.cos theta) * (Real.cos theta)))

theorem mzi_2x2_norm_witness_pythagorean (theta : Real) :
    ((norm_witness theta) = (1 : Real)) := by
  unfold norm_witness
  exact pythagorean theta
