-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/photonics/components/phase_shifter.eml
-- P1 Photonic Component Library (5/8)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def LAMBDA_C_BAND : Real := (1.55e-06 : Real)

axiom phase_shift (delta_n : Real) (length : Real) (lambda : Real) : Real

-- ── phase_at_zero_dn ──
-- 0 / lambda = 0 with lambda ≠ 0  via div_def + zero_mul.

noncomputable def phase_at_zero_dn (length : Real) (lambda : Real) : Real :=
  ((0 : Real) / lambda)

theorem phase_shifter_zero_dn_zero_phase (length : Real) (lambda : Real)
    (h1 : (lambda > (0 : Real))) :
    ((phase_at_zero_dn length lambda) = (0 : Real)) := by
  unfold phase_at_zero_dn
  have hne : lambda ≠ 0 := ne_of_gt h1
  rw [div_def 0 lambda hne]
  exact zero_mul (1 / lambda)

-- ── length_positive ──

noncomputable def length_positive (length : Real) : Real :=
  length

theorem phase_shifter_length_positive (length : Real)
    (h1 : (length > (0 : Real))) :
    ((length_positive length) > (0 : Real)) := by
  unfold length_positive
  exact h1
