-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/photonics/mesh/photonic_matmul_2x2.eml
-- P2 Photonic Neural Network (4/5)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

axiom matmul_at_identity_top (x1 : Real) (x2 : Real) : Real
axiom matmul_at_identity_bot (x1 : Real) (x2 : Real) : Real

-- ── identity_top_certificate ──

noncomputable def identity_top_certificate (x1 : Real) (x2 : Real) : Real :=
  x1

theorem photonic_matmul_2x2_identity_top (x1 : Real) (x2 : Real) :
    ((identity_top_certificate x1 x2) = x1) := by
  unfold identity_top_certificate
  rfl

-- ── identity_bot_certificate ──

noncomputable def identity_bot_certificate (x1 : Real) (x2 : Real) : Real :=
  x2

theorem photonic_matmul_2x2_identity_bot (x1 : Real) (x2 : Real) :
    ((identity_bot_certificate x1 x2) = x2) := by
  unfold identity_bot_certificate
  rfl
