-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/photonics/mesh/photonic_attention.eml
-- P2 Photonic Neural Network (5/5)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def D_MODEL : Real := (4.0 : Real)
noncomputable def SQRT_D : Real := (2.0 : Real)

axiom projection_at_identity (x_i : Real) : Real
axiom score_at_identity (x_i : Real) (x_j : Real) (sqrt_d : Real) : Real

-- ── projection_certificate ──

noncomputable def projection_certificate (x_i : Real) : Real :=
  x_i

theorem photonic_attention_projection_identity (x_i : Real) :
    ((projection_certificate x_i) = x_i) := by
  unfold projection_certificate
  rfl

-- ── score_at_zero_input_certificate ──
-- 0 / sqrt_d = 0  via div_def + zero_mul, with sqrt_d > 0 (and ne 0).

noncomputable def score_at_zero_input_certificate (sqrt_d : Real) : Real :=
  ((0 : Real) / sqrt_d)

theorem photonic_attention_score_at_zero_input (sqrt_d : Real)
    (h1 : (sqrt_d > (0 : Real))) :
    ((score_at_zero_input_certificate sqrt_d) = (0 : Real)) := by
  unfold score_at_zero_input_certificate
  have hne : sqrt_d ≠ 0 := ne_of_gt h1
  rw [div_def 0 sqrt_d hne]
  exact zero_mul (1 / sqrt_d)

-- ── matmul_count_certificate ──

noncomputable def matmul_count_certificate  : Real :=
  (4.0 : Real)

theorem photonic_attention_matmul_count  :
    ((matmul_count_certificate ) = (4.0 : Real)) := by
  unfold matmul_count_certificate
  rfl
