-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/photonics/components/photodetector.eml
-- P1 Photonic Component Library (3/8)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def R_SI_1550 : Real := (1.25 : Real)

axiom photocurrent (p_optical : Real) (responsivity : Real) : Real

-- ── current_at_zero_power ──

noncomputable def current_at_zero_power (responsivity : Real) : Real :=
  (0 : Real)

theorem photodetector_dark_current_zero (responsivity : Real) :
    ((current_at_zero_power responsivity) = (0 : Real)) := by
  unfold current_at_zero_power
  rfl

-- ── nonneg_current ──
-- r * p ≥ 0 from r ≥ 0 and p ≥ 0  via mul_nonneg.

noncomputable def nonneg_current (p : Real) (r : Real) : Real :=
  (r * p)

theorem photodetector_nonneg_current (p : Real) (r : Real)
    (h1 : (r >= (0 : Real)))
    (h2 : (p >= (0 : Real))) :
    ((nonneg_current p r) >= (0 : Real)) := by
  unfold nonneg_current
  exact mul_nonneg h1 h2
