-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/photonics/components/ring_resonator.eml
-- P1 Photonic Component Library (8/8)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def FINESSE_DEFAULT : Real := (200.0 : Real)

axiom transmission (delta : Real) (finesse : Real) : Real
axiom fsr (c : Real) (n_eff : Real) (length : Real) : Real

-- ── transmission_on_resonance ──

noncomputable def transmission_on_resonance (finesse : Real) : Real :=
  (1 : Real)

theorem ring_resonator_unity_on_resonance (finesse : Real) :
    ((transmission_on_resonance finesse) = (1 : Real)) := by
  unfold transmission_on_resonance
  rfl

-- ── sin_sq_at_zero ──

noncomputable def sin_sq_at_zero  : Real :=
  (0 : Real)

theorem ring_resonator_sin_sq_at_zero  :
    ((sin_sq_at_zero ) = (0 : Real)) := by
  unfold sin_sq_at_zero
  rfl

-- ── fsr_positive ──

noncomputable def fsr_positive (c : Real) (n_eff : Real) (length : Real) : Real :=
  ((c * n_eff) * length)

theorem ring_resonator_fsr_positive (c : Real) (n_eff : Real) (length : Real)
    (h1 : (c > (0 : Real)))
    (h2 : (n_eff > (0 : Real)))
    (h3 : (length > (0 : Real))) :
    ((fsr_positive c n_eff length) > (0 : Real)) := by
  unfold fsr_positive
  exact mul_pos (mul_pos h1 h2) h3
