-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/photonics/tolerance/thermal_model.eml
-- P3 Manufacturing Tolerance (4/4)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def DN_DT_SOI : Real := (1.86e-04 : Real)
noncomputable def LENGTH_TYPICAL : Real := (1.0e-04 : Real)
noncomputable def LAMBDA_C : Real := (1.55e-06 : Real)

axiom drifted_phase (delta_t : Real) (dn_dt : Real) (length : Real) (lambda : Real) : Real

-- ── zero_dt_certificate ──
-- 0 / lambda = 0 with lambda ≠ 0 (from h1) via div_def + zero_mul.

noncomputable def zero_dt_certificate (dn_dt : Real) (length : Real) (lambda : Real) : Real :=
  ((0 : Real) / lambda)

theorem thermal_model_zero_dt_zero_drift (dn_dt : Real) (length : Real) (lambda : Real)
    (h1 : (lambda > (0 : Real))) :
    ((zero_dt_certificate dn_dt length lambda) = (0 : Real)) := by
  unfold zero_dt_certificate
  have hne : lambda ≠ 0 := ne_of_gt h1
  rw [div_def 0 lambda hne]
  exact zero_mul (1 / lambda)

-- ── dn_dt_positive_certificate ──

noncomputable def dn_dt_positive_certificate (dn_dt : Real) : Real :=
  dn_dt

theorem thermal_model_dn_dt_positive (dn_dt : Real)
    (h1 : (dn_dt > (0 : Real))) :
    ((dn_dt_positive_certificate dn_dt) > (0 : Real)) := by
  unfold dn_dt_positive_certificate
  exact h1
