-- Generated by the EML-lang Lean backend, then sorry-closed by hand.
-- Source: forge/examples/photonics/tolerance/tolerance_model.eml
-- P3 Manufacturing Tolerance (1/4)

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def PHI_DESIGN : Real := (1.5707963267948966 : Real)
noncomputable def LAMBDA_DESIGN : Real := (1.55e-06 : Real)
noncomputable def KAPPA_DESIGN : Real := (1000.0 : Real)

axiom phase_error_magnitude (delta_phi : Real) : Real
axiom wavelength_error_magnitude (delta_lambda : Real) : Real
axiom kappa_error_magnitude (delta_kappa : Real) : Real

-- ── perfect_phase_certificate ──

noncomputable def perfect_phase_certificate  : Real :=
  (0 : Real)

theorem tolerance_zero_phase_tolerance_zero_error  :
    ((perfect_phase_certificate ) = (0 : Real)) := by
  unfold perfect_phase_certificate
  rfl

-- ── phase_error_nonneg ──

noncomputable def phase_error_nonneg (delta_phi : Real) : Real :=
  delta_phi

theorem tolerance_phase_error_nonneg (delta_phi : Real)
    (h1 : (delta_phi >= (0 : Real))) :
    ((phase_error_nonneg delta_phi) >= (0 : Real)) := by
  unfold phase_error_nonneg
  exact h1

-- ── wavelength_error_nonneg ──

noncomputable def wavelength_error_nonneg (delta_lambda : Real) : Real :=
  delta_lambda

theorem tolerance_wavelength_error_nonneg (delta_lambda : Real)
    (h1 : (delta_lambda >= (0 : Real))) :
    ((wavelength_error_nonneg delta_lambda) >= (0 : Real)) := by
  unfold wavelength_error_nonneg
  exact h1
