-- Generated by the EML-lang Lean backend
-- Source module: abrams_strength
-- Source file:   <private>/abrams_strength.eml
-- Verified fns:  compressive_strength, nurse_saul_step, age_strength_factor

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ONE : Real := (1 : Real)
noncomputable def A_MAX : Real := (200.0 : Real)
noncomputable def K_MAX : Real := (10.0 : Real)
noncomputable def WC_MIN : Real := (0.2 : Real)
noncomputable def WC_MAX : Real := (1 : Real)
noncomputable def M_MAX : Real := (10000.0 : Real)
noncomputable def T_MIN_C : Real := (-(10.0 : Real))
noncomputable def T_DATUM : Real := (-(10.0 : Real))

-- ── compressive_strength ──

noncomputable def compressive_strength (a_intercept : Real) (k_decay : Real) (water_cement_ratio : Real) : Real :=
  (a_intercept * (Real.exp ((-k_decay) * water_cement_ratio)))

-- source obligations for compressive_strength: {O1}
--   O1 [e17731314157] -> PRESERVED (accounted)  theorem abrams_strength_decreases_with_wc
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem abrams_strength_decreases_with_wc (a_intercept : Real) (k_decay : Real) (water_cement_ratio : Real)
    (h1 : (a_intercept >= (0 : Real)))
    (h2 : (a_intercept <= A_MAX))
    (h3 : (k_decay >= (0 : Real)))
    (h4 : (k_decay <= K_MAX))
    (h5 : (water_cement_ratio >= WC_MIN))
    (h6 : (water_cement_ratio <= WC_MAX)) :
    ((compressive_strength a_intercept k_decay water_cement_ratio) >= (0 : Real)) := by
  unfold compressive_strength
  try unfold ZERO at *
  try unfold ONE at *
  try unfold A_MAX at *
  try unfold K_MAX at *
  try unfold WC_MIN at *
  try unfold WC_MAX at *
  try unfold M_MAX at *
  try unfold T_MIN_C at *
  try unfold T_DATUM at *
  try mach_split_hyps
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── nurse_saul_step ──

noncomputable def nurse_saul_step (temperature_c : Real) (dt_hours : Real) : Real :=
  ((temperature_c - T_DATUM) * dt_hours)

-- obligations for nurse_saul_step: none declared (this artifact proves well-typedness only)
-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem nurse_saul_step_nonneg_above_datum (temperature_c : Real) (dt_hours : Real)
    (h1 : (temperature_c >= T_MIN_C))
    (h2 : (temperature_c <= (100.0 : Real)))
    (h3 : (dt_hours >= (0 : Real)))
    (h4 : (dt_hours <= (24.0 : Real))) :
    True := by
  trivial

-- ── age_strength_factor ──

noncomputable def age_strength_factor (age_days : Real) (alpha : Real) (beta : Real) : Real :=
  (age_days / (alpha + (beta * age_days)))

-- source obligations for age_strength_factor: {O1}
--   O1 [376123810e91] -> PRESERVED (accounted)  theorem aci_age_strength_factor_in_unit_interval
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem aci_age_strength_factor_in_unit_interval (age_days : Real) (alpha : Real) (beta : Real)
    (h1 : (age_days >= (1 : Real)))
    (h2 : (age_days <= (1000.0 : Real)))
    (h3 : (alpha > (0 : Real)))
    (h4 : (alpha <= (50.0 : Real)))
    (h5 : (beta > (0 : Real)))
    (h6 : (beta <= (5.0 : Real))) :
    ((age_strength_factor age_days alpha beta) >= (0 : Real)) := by
  unfold age_strength_factor
  try unfold ZERO at *
  try unfold ONE at *
  try unfold A_MAX at *
  try unfold K_MAX at *
  try unfold WC_MIN at *
  try unfold WC_MAX at *
  try unfold M_MAX at *
  try unfold T_MIN_C at *
  try unfold T_DATUM at *
  try mach_split_hyps
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
