-- Generated by the EML-lang Lean backend
-- Source module: acc_step
-- Source file:   <private>/acc_step.eml
-- Verified fns:  target_distance, distance_error, outer_speed_command, comfort_accel_limiter

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def V_MAX : Real := (70.0 : Real)
noncomputable def TH_MIN : Real := (0.8 : Real)
noncomputable def TH_MAX : Real := (4.0 : Real)
noncomputable def D_MIN_SAFE : Real := (1.5 : Real)
noncomputable def D_MAX : Real := (250.0 : Real)
noncomputable def KP_MAX : Real := (5.0 : Real)
noncomputable def ACC_MAX : Real := (4.0 : Real)

-- ── target_distance ──

noncomputable def target_distance (ego_speed : Real) (time_headway : Real) (d_min_safe : Real) : Real :=
  ((ego_speed * time_headway) + d_min_safe)

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem target_distance_increases_with_speed (ego_speed : Real) (time_headway : Real) (d_min_safe : Real)
    (h_ego_speed : (((0 : Real) <= ego_speed) ∧ (ego_speed <= V_MAX)))
    (h_time_headway : ((TH_MIN <= time_headway) ∧ (time_headway <= TH_MAX)))
    (h_d_min_safe : (((0.5 : Real) <= d_min_safe) ∧ (d_min_safe <= (10.0 : Real)))) :
    True := by
  trivial

-- ── distance_error ──

noncomputable def distance_error (distance_meas : Real) (distance_target : Real) : Real :=
  (distance_meas - distance_target)

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem distance_error_zero_at_target (distance_meas : Real) (distance_target : Real)
    (h_distance_meas : (((0 : Real) <= distance_meas) ∧ (distance_meas <= D_MAX)))
    (h_distance_target : (((0 : Real) <= distance_target) ∧ (distance_target <= D_MAX))) :
    True := by
  trivial

-- ── outer_speed_command ──

noncomputable def outer_speed_command (ego_speed : Real) (distance_error : Real) (kp : Real) (set_speed_max : Real) : Real :=
  (min (max (ego_speed + (kp * distance_error)) (0 : Real)) set_speed_max)

theorem speed_command_within_set_max (ego_speed : Real) (distance_error : Real) (kp : Real) (set_speed_max : Real)
    (h_ego_speed : (((0 : Real) <= ego_speed) ∧ (ego_speed <= V_MAX)))
    (h_distance_error : (-D_MAX ≤ distance_error ∧ distance_error ≤ D_MAX))
    (h_kp : (((0 : Real) <= kp) ∧ (kp <= KP_MAX)))
    (h_set_speed_max : (((0 : Real) <= set_speed_max) ∧ (set_speed_max <= V_MAX)))
    (h_clamp1 : (0 : Real) ≤ set_speed_max) :
    (((outer_speed_command ego_speed distance_error kp set_speed_max) >= (0 : Real))) ∧ (((outer_speed_command ego_speed distance_error kp set_speed_max) <= set_speed_max)) := by
  unfold outer_speed_command
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover

-- ── comfort_accel_limiter ──

noncomputable def comfort_accel_limiter (accel_cmd : Real) (accel_max : Real) (decel_max : Real) : Real :=
  (min (max accel_cmd (-decel_max)) accel_max)

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem acc_command_within_comfort_band (accel_cmd : Real) (accel_max : Real) (decel_max : Real)
    (h_accel_cmd : (-(ACC_MAX * (4.0 : Real)) ≤ accel_cmd ∧ accel_cmd ≤ (ACC_MAX * (4.0 : Real))))
    (h_accel_max : (((0 : Real) <= accel_max) ∧ (accel_max <= ACC_MAX)))
    (h_decel_max : (((0 : Real) <= decel_max) ∧ (decel_max <= (ACC_MAX * (2.0 : Real)))))
    (h_clamp1 : (-decel_max) ≤ accel_max) :
    True := by
  trivial
