import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: ackermann_steering
-- Source file:   <private>/ackermann_steering.eml
-- Verified fns:  bicycle_yaw_rate, ackermann_inner_tan, ackermann_outer_tan, turn_radius

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def WHEELBASE_MIN : Real := (0.5 : Real)
noncomputable def WHEELBASE_MAX : Real := (5.0 : Real)
noncomputable def TRACK_MAX : Real := (3.0 : Real)
noncomputable def SPEED_MAX : Real := (80.0 : Real)
noncomputable def STEER_MAX : Real := (0.7 : Real)

-- ── bicycle_yaw_rate ──

noncomputable def bicycle_yaw_rate (speed : Real) (steer : Real) (wheelbase : Real) : Real :=
  ((speed * (Real.tan steer)) / wheelbase)

theorem bicycle_yaw_rate_zero_when_steer_zero (speed : Real) (steer : Real) (wheelbase : Real)
    (h1 : ((abs speed) <= SPEED_MAX))
    (h2 : ((abs steer) <= STEER_MAX))
    (h3 : (wheelbase >= WHEELBASE_MIN))
    (h4 : (wheelbase <= WHEELBASE_MAX)) :
    True := by
  trivial

-- ── ackermann_inner_tan ──

noncomputable def ackermann_inner_tan (centerline_steer : Real) (wheelbase : Real) (track : Real) : Real :=
  ((wheelbase * (Real.tan centerline_steer)) / (wheelbase - (((0.5 : Real) * track) * (Real.tan centerline_steer))))

theorem ackermann_inner_steeper_than_outer (centerline_steer : Real) (wheelbase : Real) (track : Real)
    (h1 : ((abs centerline_steer) <= STEER_MAX))
    (h2 : (wheelbase >= WHEELBASE_MIN))
    (h3 : (wheelbase <= WHEELBASE_MAX))
    (h4 : (track >= (0.5 : Real)))
    (h5 : (track <= TRACK_MAX)) :
    True := by
  trivial

-- ── ackermann_outer_tan ──

noncomputable def ackermann_outer_tan (centerline_steer : Real) (wheelbase : Real) (track : Real) : Real :=
  ((wheelbase * (Real.tan centerline_steer)) / (wheelbase + (((0.5 : Real) * track) * (Real.tan centerline_steer))))

theorem ackermann_outer_shallower_than_inner (centerline_steer : Real) (wheelbase : Real) (track : Real)
    (h1 : ((abs centerline_steer) <= STEER_MAX))
    (h2 : (wheelbase >= WHEELBASE_MIN))
    (h3 : (wheelbase <= WHEELBASE_MAX))
    (h4 : (track >= (0.5 : Real)))
    (h5 : (track <= TRACK_MAX)) :
    True := by
  trivial

-- ── turn_radius ──

noncomputable def turn_radius (steer : Real) (wheelbase : Real) : Real :=
  (wheelbase / (Real.tan steer))

theorem turn_radius_inverse_to_steer (steer : Real) (wheelbase : Real)
    (h1 : ((abs steer) >= (0.001 : Real)))
    (h2 : ((abs steer) <= STEER_MAX))
    (h3 : (wheelbase >= WHEELBASE_MIN))
    (h4 : (wheelbase <= WHEELBASE_MAX)) :
    True := by
  trivial
