import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: additive_voice
-- Source file:   <private>/additive_voice.eml
-- Verified fns:  voice_sample

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def PI : Real := (3.141592653589793 : Real)
noncomputable def TWO_PI : Real := (6.283185307179586 : Real)
noncomputable def ATTACK_RATE : Real := (5.0 : Real)
noncomputable def PARTIAL_2 : Real := (0.5 : Real)
noncomputable def PARTIAL_3 : Real := (0.333 : Real)
noncomputable def PARTIAL_4 : Real := (0.25 : Real)

axiom partial_ (t : Real) (freq : Real) (n_harmonic : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom envelope (t : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── voice_sample ──

noncomputable def voice_sample (t : Real) (freq : Real) : Real :=
  (((1.0 : Real) - (Real.exp ((-ATTACK_RATE) * t))) * ((((Real.sin ((TWO_PI * freq) * t)) + (PARTIAL_2 * (Real.sin (((TWO_PI * freq) * (2.0 : Real)) * t)))) + (PARTIAL_3 * (Real.sin (((TWO_PI * freq) * (3.0 : Real)) * t)))) + (PARTIAL_4 * (Real.sin (((TWO_PI * freq) * (4.0 : Real)) * t)))))

theorem additive_voice_amplitude_bounded (t : Real) (freq : Real)
    (h1 : (t >= (0.0 : Real)))
    (h2 : (t < (1000000.0 : Real)))
    (h3 : (freq > (0.0 : Real)))
    (h4 : (freq < (22050.0 : Real))) :
    ((abs (voice_sample t freq)) < (4.0 : Real)) := by
  unfold voice_sample
  sorry  -- TODO: prove against MachLib foundations
