-- Generated by the EML-lang Lean backend
-- Source module: aeb_ttc
-- Source file:   <private>/aeb_ttc.eml
-- Verified fns:  ttc_constant_velocity, ttc_constant_acceleration, stopping_distance

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def RANGE_MAX : Real := (250.0 : Real)
noncomputable def VEL_MAX : Real := (80.0 : Real)
noncomputable def ACCEL_MAX : Real := (12.0 : Real)
noncomputable def TTC_MAX : Real := (30.0 : Real)
noncomputable def EPS : Real := (0.01 : Real)

-- ── ttc_constant_velocity ──

noncomputable def ttc_constant_velocity (range_m : Real) (range_rate : Real) : Real :=
  ((-range_m) / range_rate)

-- source obligations for ttc_constant_velocity: {O1}
--   O1 [d1bea64d0a60] -> PRESERVED (accounted)  theorem ttc_positive_when_closing
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem ttc_positive_when_closing (range_m : Real) (range_rate : Real)
    (h_range_m : (((0 : Real) <= range_m) ∧ (range_m <= RANGE_MAX)))
    (h_range_rate : (((-VEL_MAX) <= range_rate) ∧ (range_rate < (-EPS)))) :
    ((ttc_constant_velocity range_m range_rate) >= (0 : Real)) := by
  unfold ttc_constant_velocity
  try unfold RANGE_MAX at *
  try unfold VEL_MAX at *
  try unfold ACCEL_MAX at *
  try unfold TTC_MAX at *
  try unfold EPS at *
  try mach_split_hyps
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── ttc_constant_acceleration ──

noncomputable def ttc_constant_acceleration (range_m : Real) (range_rate : Real) (rel_accel : Real) : Real :=
  (((-range_rate) - (Real.sqrt (min (max ((range_rate * range_rate) - (((2.0 : Real) * rel_accel) * range_m)) (0 : Real)) (1000000000.0 : Real)))) / (min (max rel_accel EPS) ACCEL_MAX))

-- obligations for ttc_constant_acceleration: none declared (this artifact proves well-typedness only)
-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem ttc_constant_accel_real_when_discriminant_nonneg (range_m : Real) (range_rate : Real) (rel_accel : Real)
    (h_range_m : (((0 : Real) <= range_m) ∧ (range_m <= RANGE_MAX)))
    (h_range_rate : (((-VEL_MAX) <= range_rate) ∧ (range_rate <= VEL_MAX)))
    (h_rel_accel : (-ACCEL_MAX ≤ rel_accel ∧ rel_accel ≤ ACCEL_MAX))
    (h_clamp1 : (0 : Real) ≤ (1000000000.0 : Real))
    (h_clamp2 : EPS ≤ ACCEL_MAX) :
    True := by
  trivial

-- ── stopping_distance ──

noncomputable def stopping_distance (speed : Real) (deceleration : Real) : Real :=
  ((speed * speed) / ((2.0 : Real) * deceleration))

-- source obligations for stopping_distance: {O1}
--   O1 [5dc84298f57f] -> PRESERVED (accounted)  theorem stopping_distance_quadratic_in_speed
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem stopping_distance_quadratic_in_speed (speed : Real) (deceleration : Real)
    (h_speed : (((0 : Real) <= speed) ∧ (speed <= VEL_MAX)))
    (h_deceleration : ((EPS <= deceleration) ∧ (deceleration <= ACCEL_MAX))) :
    ((stopping_distance speed deceleration) >= (0 : Real)) := by
  unfold stopping_distance
  try unfold RANGE_MAX at *
  try unfold VEL_MAX at *
  try unfold ACCEL_MAX at *
  try unfold TTC_MAX at *
  try unfold EPS at *
  try mach_split_hyps
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
