import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: aeb_ttc
-- Source file:   <private>/aeb_ttc.eml
-- Verified fns:  ttc_constant_velocity, ttc_constant_acceleration, stopping_distance

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def RANGE_MAX : Real := (250.0 : Real)
noncomputable def VEL_MAX : Real := (80.0 : Real)
noncomputable def ACCEL_MAX : Real := (12.0 : Real)
noncomputable def TTC_MAX : Real := (30.0 : Real)
noncomputable def EPS : Real := (0.01 : Real)

-- ── ttc_constant_velocity ──

noncomputable def ttc_constant_velocity (range_m : Real) (range_rate : Real) : Real :=
  ((-range_m) / range_rate)

theorem ttc_positive_when_closing (range_m : Real) (range_rate : Real)
    (h1 : (range_m >= (0.0 : Real)))
    (h2 : (range_m <= RANGE_MAX))
    (h3 : (range_rate >= (-VEL_MAX)))
    (h4 : (range_rate <= VEL_MAX))
    (h5 : (range_rate < (-EPS))) :
    ((ttc_constant_velocity range_m range_rate) >= (0.0 : Real)) := by
  unfold ttc_constant_velocity
  sorry  -- TODO: prove against MachLib foundations

-- ── ttc_constant_acceleration ──

noncomputable def ttc_constant_acceleration (range_m : Real) (range_rate : Real) (rel_accel : Real) : Real :=
  (((-range_rate) - (Real.sqrt (min (max ((range_rate * range_rate) - (((2.0 : Real) * rel_accel) * range_m)) (0.0 : Real)) (1000000000.0 : Real)))) / (min (max rel_accel EPS) ACCEL_MAX))

theorem ttc_constant_accel_real_when_discriminant_nonneg (range_m : Real) (range_rate : Real) (rel_accel : Real)
    (h1 : (range_m >= (0.0 : Real)))
    (h2 : (range_m <= RANGE_MAX))
    (h3 : (range_rate >= (-VEL_MAX)))
    (h4 : (range_rate <= VEL_MAX))
    (h5 : ((abs rel_accel) <= ACCEL_MAX)) :
    True := by
  trivial

-- ── stopping_distance ──

noncomputable def stopping_distance (speed : Real) (deceleration : Real) : Real :=
  ((speed * speed) / ((2.0 : Real) * deceleration))

theorem stopping_distance_quadratic_in_speed (speed : Real) (deceleration : Real)
    (h1 : (speed >= (0.0 : Real)))
    (h2 : (speed <= VEL_MAX))
    (h3 : (deceleration >= EPS))
    (h4 : (deceleration <= ACCEL_MAX)) :
    ((stopping_distance speed deceleration) >= (0.0 : Real)) := by
  unfold stopping_distance
  sorry  -- TODO: prove against MachLib foundations
