import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: aes
-- Source file:   <private>/aes.eml
-- Verified fns:  gf256_inverse, aes_sbox

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def NUM_ROUNDS : Int := 14
noncomputable def KEY_BYTES : Int := 32
noncomputable def STATE_BYTES : Int := 16

axiom gf256_square (b : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

axiom gf256_mul (a : Real) (b : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

axiom affine_transform (b : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

-- ── gf256_inverse ──

noncomputable def gf256_inverse (input : Real) : Real :=
  (gf256_mul (gf256_square (gf256_square (gf256_square (gf256_square (gf256_square (gf256_square (gf256_square input))))))) (gf256_mul (gf256_square (gf256_square (gf256_square (gf256_square (gf256_square (gf256_square input)))))) (gf256_mul (gf256_square (gf256_square (gf256_square (gf256_square (gf256_square input))))) (gf256_mul (gf256_square (gf256_square (gf256_square (gf256_square input)))) (gf256_mul (gf256_square (gf256_square (gf256_square input))) (gf256_mul (gf256_square (gf256_square input)) (gf256_square input)))))))

theorem gf256_inverse_correct (input : Real)
    (h1 : True) :
    True := by
  trivial

-- ── aes_sbox ──

noncomputable def aes_sbox (input : Real) : Real :=
  (affine_transform (gf256_inverse input))

theorem aes_sbox_correct (input : Real)
    (h1 : True) :
    True := by
  trivial
