-- Generated by the EML-lang Lean backend
-- Source module: aragonite_saturation
-- Source file:   <private>/aragonite_saturation.eml
-- Verified fns:  saturation_state, ksp_at_temperature

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ONE : Real := (1 : Real)
noncomputable def T_MIN : Real := (271.15 : Real)
noncomputable def T_MAX : Real := (313.15 : Real)
noncomputable def T_REF : Real := (298.15 : Real)
noncomputable def R_GAS : Real := (8.314 : Real)
noncomputable def KSP_MAX : Real := (0.001 : Real)
noncomputable def KSP_MIN : Real := (1e-12 : Real)
noncomputable def ION_MAX : Real := (0.1 : Real)

-- ── saturation_state ──

noncomputable def saturation_state (calcium_concentration : Real) (carbonate_concentration : Real) (ksp_aragonite : Real) : Real :=
  ((calcium_concentration * carbonate_concentration) / ksp_aragonite)

theorem aragonite_saturation_nonneg (calcium_concentration : Real) (carbonate_concentration : Real) (ksp_aragonite : Real)
    (h1 : (calcium_concentration >= (0 : Real)))
    (h2 : (calcium_concentration <= ION_MAX))
    (h3 : (carbonate_concentration >= (0 : Real)))
    (h4 : (carbonate_concentration <= ION_MAX))
    (h5 : (ksp_aragonite >= KSP_MIN))
    (h6 : (ksp_aragonite <= KSP_MAX)) :
    ((saturation_state calcium_concentration carbonate_concentration ksp_aragonite) >= (0 : Real)) := by
  unfold saturation_state
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── ksp_at_temperature ──

noncomputable def ksp_at_temperature (ksp_reference : Real) (delta_h_dissolution : Real) (temperature_k : Real) : Real :=
  (ksp_reference * (Real.exp (((-delta_h_dissolution) / R_GAS) * ((ONE / temperature_k) - (ONE / T_REF)))))

theorem vant_hoff_temperature_correction_positive (ksp_reference : Real) (delta_h_dissolution : Real) (temperature_k : Real)
    (h1 : (ksp_reference >= KSP_MIN))
    (h2 : (ksp_reference <= KSP_MAX))
    (h3 : (delta_h_dissolution >= (-(1000000.0 : Real))))
    (h4 : (delta_h_dissolution <= (1000000.0 : Real)))
    (h5 : (temperature_k >= T_MIN))
    (h6 : (temperature_k <= T_MAX)) :
    ((ksp_at_temperature ksp_reference delta_h_dissolution temperature_k) > (0 : Real)) := by
  unfold ksp_at_temperature
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
