import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: autopilot
-- Source file:   <private>/autopilot.eml
-- Verified fns:  autopilot_step

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def Kp : Real := (2.5 : Real)
noncomputable def Ki : Real := (0.4 : Real)
noncomputable def Kr : Real := (1.8 : Real)
noncomputable def dt : Real := (0.01 : Real)
noncomputable def INTEGRAL_LIMIT : Real := (5.0 : Real)
noncomputable def ELEVATOR_MIN : Real := (-(0.349 : Real))
noncomputable def ELEVATOR_MAX : Real := (0.349 : Real)
noncomputable def GRAVITY_GAIN : Real := (0.196 : Real)

axiom gravity_compensation (pitch : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom rate_controller (pitch_error : Real) (pitch_integral : Real) (pitch_measured : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── autopilot_step ──

noncomputable def autopilot_step (pitch_setpoint : Real) (pitch_measured : Real) (pitch_integral : Real) : Real :=
  (min (max (Kr * (((Kp * (pitch_setpoint - pitch_measured)) + (Ki * pitch_integral)) + (GRAVITY_GAIN * (Real.cos pitch_measured)))) ELEVATOR_MIN) ELEVATOR_MAX)

theorem autopilot_command_within_limits (pitch_setpoint : Real) (pitch_measured : Real) (pitch_integral : Real)
    (h1 : ((abs pitch_setpoint) < (1.5708 : Real)))
    (h2 : ((abs pitch_measured) < (1.5708 : Real)))
    (h3 : ((abs pitch_integral) < INTEGRAL_LIMIT)) :
    ((abs (autopilot_step pitch_setpoint pitch_measured pitch_integral)) < ELEVATOR_MAX) := by
  unfold autopilot_step
  sorry  -- TODO: prove against MachLib foundations
