import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: autothrottle
-- Source file:   <private>/autothrottle.eml
-- Verified fns:  autothrottle_step, speed_integral_step, rate_limited_throttle

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def V_MAX : Real := (300.0 : Real)
noncomputable def KP_MAX : Real := (5.0 : Real)
noncomputable def KI_MAX : Real := (5.0 : Real)
noncomputable def I_LIMIT_MAX : Real := (100.0 : Real)
noncomputable def THROTTLE_MAX : Real := (1.0 : Real)
noncomputable def DT_MAX : Real := (1.0 : Real)

-- ── autothrottle_step ──

noncomputable def autothrottle_step (speed_target : Real) (speed_meas : Real) (integral : Real) (kp : Real) (ki : Real) : Real :=
  (min (max ((kp * (speed_target - speed_meas)) + (ki * integral)) (0.0 : Real)) THROTTLE_MAX)

theorem autothrottle_within_unit_interval (speed_target : Real) (speed_meas : Real) (integral : Real) (kp : Real) (ki : Real)
    (h1 : ((abs speed_target) <= V_MAX))
    (h2 : ((abs speed_meas) <= V_MAX))
    (h3 : ((abs integral) <= I_LIMIT_MAX))
    (h4 : (kp >= (0.0 : Real)))
    (h5 : (kp <= KP_MAX))
    (h6 : (ki >= (0.0 : Real)))
    (h7 : (ki <= KI_MAX)) :
    ((autothrottle_step speed_target speed_meas integral kp ki) >= (0.0 : Real)) := by
  unfold autothrottle_step
  sorry  -- TODO: prove against MachLib foundations

-- ── speed_integral_step ──

noncomputable def speed_integral_step (integral_prev : Real) (error : Real) (error_prev : Real) (dt : Real) (saturation_active : Real) : Real :=
  (min (max (integral_prev + (((1.0 : Real) - saturation_active) * (((0.5 : Real) * (error + error_prev)) * dt))) (-I_LIMIT_MAX)) I_LIMIT_MAX)

theorem speed_integral_held_under_saturation (integral_prev : Real) (error : Real) (error_prev : Real) (dt : Real) (saturation_active : Real)
    (h1 : ((abs integral_prev) <= I_LIMIT_MAX))
    (h2 : ((abs error) <= V_MAX))
    (h3 : ((abs error_prev) <= V_MAX))
    (h4 : (dt >= (0.0 : Real)))
    (h5 : (dt <= DT_MAX))
    (h6 : (saturation_active >= (0.0 : Real)))
    (h7 : (saturation_active <= (1.0 : Real))) :
    True := by
  trivial

-- ── rate_limited_throttle ──

noncomputable def rate_limited_throttle (cmd_new : Real) (cmd_prev : Real) (rate_limit : Real) (dt : Real) : Real :=
  (cmd_prev + (min (max (cmd_new - cmd_prev) (-(rate_limit * dt))) (rate_limit * dt)))

theorem throttle_rate_within_limit (cmd_new : Real) (cmd_prev : Real) (rate_limit : Real) (dt : Real)
    (h1 : (cmd_new >= (0.0 : Real)))
    (h2 : (cmd_new <= THROTTLE_MAX))
    (h3 : (cmd_prev >= (0.0 : Real)))
    (h4 : (cmd_prev <= THROTTLE_MAX))
    (h5 : (rate_limit >= (0.0 : Real)))
    (h6 : (rate_limit <= (10.0 : Real)))
    (h7 : (dt > (0.0 : Real)))
    (h8 : (dt <= DT_MAX)) :
    True := by
  trivial
