-- Generated by the EML-lang Lean backend
-- Source module: baro_altitude
-- Source file:   <private>/baro_altitude.eml
-- Verified fns:  pressure_to_altitude, altitude_to_pressure

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def P0 : Real := (101325.0 : Real)
noncomputable def T0 : Real := (288.15 : Real)
noncomputable def LAPSE : Real := (0.0065 : Real)
noncomputable def RL_OVER_G : Real := (0.190263 : Real)
noncomputable def T0_OVER_L : Real := (44330.769230769 : Real)
noncomputable def P_MIN : Real := (22632.0 : Real)
noncomputable def P_MAX : Real := (110000.0 : Real)

axiom qfe_altitude (static_pressure : Real) (field_pressure : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── pressure_to_altitude ──

noncomputable def pressure_to_altitude (static_pressure : Real) : Real :=
  (T0_OVER_L * ((1 : Real) - ((static_pressure / P0) ^ RL_OVER_G)))

theorem baro_altitude_monotone_decreasing_in_pressure (static_pressure : Real)
    (h1 : (static_pressure >= P_MIN))
    (h2 : (static_pressure <= P_MAX)) :
    True := by
  trivial

-- ── altitude_to_pressure ──

noncomputable def altitude_to_pressure (altitude : Real) : Real :=
  (P0 * (((1 : Real) - ((LAPSE * altitude) / T0)) ^ (5.25588 : Real)))

theorem altitude_to_pressure_inverse (altitude : Real)
    (h1 : (altitude >= (-(500.0 : Real))))
    (h2 : (altitude <= (11000.0 : Real))) :
    ((altitude_to_pressure altitude) >= P_MIN) := by
  unfold altitude_to_pressure
  sorry  -- TODO: prove against MachLib foundations
