-- Generated by the EML-lang Lean backend
-- Source module: baro_altitude
-- Source file:   <private>/baro_altitude.eml
-- Verified fns:  pressure_to_altitude, altitude_to_pressure

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def P0 : Real := (101325.0 : Real)
noncomputable def T0 : Real := (288.15 : Real)
noncomputable def LAPSE : Real := (0.0065 : Real)
noncomputable def RL_OVER_G : Real := (0.190263 : Real)
noncomputable def T0_OVER_L : Real := (44330.769230769 : Real)
noncomputable def P_MIN : Real := (22632.0 : Real)
noncomputable def P_MAX : Real := (110000.0 : Real)

axiom qfe_altitude (static_pressure : Real) (field_pressure : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── pressure_to_altitude ──

noncomputable def pressure_to_altitude (static_pressure : Real) : Real :=
  (T0_OVER_L * ((1 : Real) - ((static_pressure / P0) ^ RL_OVER_G)))

-- obligations for pressure_to_altitude: none declared (this artifact proves well-typedness only)
-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem baro_altitude_monotone_decreasing_in_pressure (static_pressure : Real)
    (h_static_pressure : ((P_MIN <= static_pressure) ∧ (static_pressure <= P_MAX))) :
    True := by
  trivial

-- ── altitude_to_pressure ──

noncomputable def altitude_to_pressure (altitude : Real) : Real :=
  (P0 * (((1 : Real) - ((LAPSE * altitude) / T0)) ^ (5.25588 : Real)))

-- source obligations for altitude_to_pressure: {O1, O2}
--   O1 [dfa2a6fc3a5d] -> PRESERVED (accounted)  theorem altitude_to_pressure_inverse
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
--   O2 [57cb25cb2e90] -> PRESERVED (accounted)  theorem altitude_to_pressure_inverse
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem altitude_to_pressure_inverse (altitude : Real)
    (h_altitude : (((-(500.0 : Real)) <= altitude) ∧ (altitude <= (11000.0 : Real)))) :
    (((altitude_to_pressure altitude) >= P_MIN)) ∧ (((altitude_to_pressure altitude) <= P_MAX)) := by
  unfold altitude_to_pressure
  try unfold P0 at *
  try unfold T0 at *
  try unfold LAPSE at *
  try unfold RL_OVER_G at *
  try unfold T0_OVER_L at *
  try unfold P_MIN at *
  try unfold P_MAX at *
  try mach_split_hyps
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
