import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: battery_soc
-- Source file:   <private>/battery_soc.eml
-- Verified fns:  coulomb_count_step, lithium_ion_ocv_curve, mixed_soc_estimate

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def SOC_MIN : Real := (0.0 : Real)
noncomputable def SOC_MAX : Real := (1.0 : Real)
noncomputable def I_MAX : Real := (1000.0 : Real)
noncomputable def Q_MIN : Real := (0.1 : Real)
noncomputable def Q_MAX : Real := (10000.0 : Real)
noncomputable def V_MIN : Real := (2.0 : Real)
noncomputable def V_MAX : Real := (5.0 : Real)
noncomputable def DT_MAX : Real := (60.0 : Real)

-- ── coulomb_count_step ──

noncomputable def coulomb_count_step (soc_prev : Real) (current_a : Real) (capacity_ah : Real) (dt_s : Real) : Real :=
  (min (max (soc_prev - (((current_a * dt_s) / (3600.0 : Real)) / capacity_ah)) SOC_MIN) SOC_MAX)

theorem soc_coulomb_count_decreases_under_discharge (soc_prev : Real) (current_a : Real) (capacity_ah : Real) (dt_s : Real)
    (h1 : (soc_prev >= SOC_MIN))
    (h2 : (soc_prev <= SOC_MAX))
    (h3 : ((abs current_a) <= I_MAX))
    (h4 : (capacity_ah >= Q_MIN))
    (h5 : (capacity_ah <= Q_MAX))
    (h6 : (dt_s >= (0.0 : Real)))
    (h7 : (dt_s <= DT_MAX)) :
    ((coulomb_count_step soc_prev current_a capacity_ah dt_s) >= SOC_MIN) := by
  unfold coulomb_count_step
  sorry  -- TODO: prove against MachLib foundations

-- ── lithium_ion_ocv_curve ──

noncomputable def lithium_ion_ocv_curve (soc : Real) : Real :=
  ((((3.0 : Real) + ((1.5 : Real) * soc)) - ((1.2 : Real) * (soc * soc))) + ((0.5 : Real) * ((soc * soc) * soc)))

theorem ocv_curve_monotone_in_soc (soc : Real)
    (h1 : (soc >= (0.05 : Real)))
    (h2 : (soc <= (0.95 : Real))) :
    ((lithium_ion_ocv_curve soc) >= V_MIN) := by
  unfold lithium_ion_ocv_curve
  sorry  -- TODO: prove against MachLib foundations

-- ── mixed_soc_estimate ──

noncomputable def mixed_soc_estimate (soc_coulomb : Real) (soc_from_ocv : Real) (alpha : Real) : Real :=
  ((alpha * soc_coulomb) + (((1.0 : Real) - alpha) * soc_from_ocv))

theorem mixed_soc_blends_estimators (soc_coulomb : Real) (soc_from_ocv : Real) (alpha : Real)
    (h1 : (soc_coulomb >= SOC_MIN))
    (h2 : (soc_coulomb <= SOC_MAX))
    (h3 : (soc_from_ocv >= SOC_MIN))
    (h4 : (soc_from_ocv <= SOC_MAX))
    (h5 : (alpha >= (0.0 : Real)))
    (h6 : (alpha <= (1.0 : Real))) :
    ((mixed_soc_estimate soc_coulomb soc_from_ocv alpha) >= SOC_MIN) := by
  unfold mixed_soc_estimate
  sorry  -- TODO: prove against MachLib foundations
