import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: beer_lambert
-- Source file:   <private>/beer_lambert.eml
-- Verified fns:  absorbance, transmittance

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def A_MAX : Real := (6.0 : Real)
noncomputable def C_MAX : Real := (1000.0 : Real)
noncomputable def L_MAX : Real := (100.0 : Real)

axiom transmitted_intensity (incident_intensity : Real) (molar_absorptivity : Real) (path_length : Real) (concentration : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom concentration_from_absorbance (absorbance_value : Real) (molar_absorptivity : Real) (path_length : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── absorbance ──

noncomputable def absorbance (molar_absorptivity : Real) (path_length : Real) (concentration : Real) : Real :=
  ((molar_absorptivity * path_length) * concentration)

theorem beer_lambert_linear_in_concentration (molar_absorptivity : Real) (path_length : Real) (concentration : Real)
    (h1 : (molar_absorptivity >= (0.0 : Real)))
    (h2 : (path_length >= (0.0 : Real)))
    (h3 : (path_length <= L_MAX))
    (h4 : (concentration >= (0.0 : Real)))
    (h5 : (concentration <= C_MAX)) :
    ((absorbance molar_absorptivity path_length concentration) >= (0.0 : Real)) := by
  unfold absorbance
  sorry  -- TODO: prove against MachLib foundations

-- ── transmittance ──

noncomputable def transmittance (absorbance_value : Real) : Real :=
  (Real.exp (-absorbance_value))

theorem transmittance_in_unit_interval (absorbance_value : Real)
    (h1 : (absorbance_value >= (0.0 : Real)))
    (h2 : (absorbance_value <= A_MAX)) :
    ((transmittance absorbance_value) >= (0.0 : Real)) := by
  unfold transmittance
  sorry  -- TODO: prove against MachLib foundations
