-- Generated by the EML-lang Lean backend
-- Source module: beer_lambert
-- Source file:   <private>/beer_lambert.eml
-- Verified fns:  absorbance, transmittance

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def A_MAX : Real := (6.0 : Real)
noncomputable def C_MAX : Real := (1000.0 : Real)
noncomputable def L_MAX : Real := (100.0 : Real)

axiom transmitted_intensity (incident_intensity : Real) (molar_absorptivity : Real) (path_length : Real) (concentration : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom concentration_from_absorbance (absorbance_value : Real) (molar_absorptivity : Real) (path_length : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── absorbance ──

noncomputable def absorbance (molar_absorptivity : Real) (path_length : Real) (concentration : Real) : Real :=
  ((molar_absorptivity * path_length) * concentration)

-- source obligations for absorbance: {O1}
--   O1 [4be718136d89] -> PRESERVED (accounted)  theorem beer_lambert_linear_in_concentration
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem beer_lambert_linear_in_concentration (molar_absorptivity : Real) (path_length : Real) (concentration : Real)
    (h1 : (molar_absorptivity >= (0 : Real)))
    (h2 : (path_length >= (0 : Real)))
    (h3 : (path_length <= L_MAX))
    (h4 : (concentration >= (0 : Real)))
    (h5 : (concentration <= C_MAX)) :
    ((absorbance molar_absorptivity path_length concentration) >= (0 : Real)) := by
  unfold absorbance
  try unfold A_MAX at *
  try unfold C_MAX at *
  try unfold L_MAX at *
  try mach_split_hyps
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── transmittance ──

noncomputable def transmittance (absorbance_value : Real) : Real :=
  (Real.exp (-absorbance_value))

-- source obligations for transmittance: {O1, O2}
--   O1 [a5b7e9ce87d7] -> PRESERVED (accounted)  theorem transmittance_in_unit_interval
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
--   O2 [f70a7997fadf] -> PRESERVED (accounted)  theorem transmittance_in_unit_interval
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem transmittance_in_unit_interval (absorbance_value : Real)
    (h1 : (absorbance_value >= (0 : Real)))
    (h2 : (absorbance_value <= A_MAX)) :
    (((transmittance absorbance_value) >= (0 : Real))) ∧ (((transmittance absorbance_value) <= (1 : Real))) := by
  unfold transmittance
  try unfold A_MAX at *
  try unfold C_MAX at *
  try unfold L_MAX at *
  try mach_split_hyps
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
