-- Generated by the EML-lang Lean backend
-- Source module: bilateral_filter
-- Source file:   <private>/bilateral_filter.eml
-- Verified fns:  bilateral_weight, spatial_gaussian_weight

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def COORD_MAX : Real := (10000.0 : Real)
noncomputable def INTENSITY_MAX : Real := (65535.0 : Real)
noncomputable def SIGMA_MIN : Real := (0.001 : Real)
noncomputable def SIGMA_MAX : Real := (1000000.0 : Real)
noncomputable def HALF : Real := (0.5 : Real)

axiom weighted_contribution (weight : Real) (intensity : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── bilateral_weight ──

noncomputable def bilateral_weight (dx : Real) (dy : Real) (di : Real) (sigma_spatial : Real) (sigma_range : Real) : Real :=
  (Real.exp ((-HALF) * ((((dx * dx) + (dy * dy)) / (sigma_spatial * sigma_spatial)) + ((di * di) / (sigma_range * sigma_range)))))

theorem bilateral_weight_in_unit_interval (dx : Real) (dy : Real) (di : Real) (sigma_spatial : Real) (sigma_range : Real)
    (h1 : ((abs dx) <= COORD_MAX))
    (h2 : ((abs dy) <= COORD_MAX))
    (h3 : ((abs di) <= INTENSITY_MAX))
    (h4 : (sigma_spatial >= SIGMA_MIN))
    (h5 : (sigma_spatial <= SIGMA_MAX))
    (h6 : (sigma_range >= SIGMA_MIN))
    (h7 : (sigma_range <= SIGMA_MAX)) :
    (((bilateral_weight dx dy di sigma_spatial sigma_range) >= (0 : Real))) ∧ (((bilateral_weight dx dy di sigma_spatial sigma_range) <= (1 : Real))) := by
  unfold bilateral_weight
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover

-- ── spatial_gaussian_weight ──

noncomputable def spatial_gaussian_weight (dx : Real) (dy : Real) (sigma : Real) : Real :=
  (Real.exp (((-HALF) * ((dx * dx) + (dy * dy))) / (sigma * sigma)))

theorem spatial_gaussian_weight_in_unit_interval (dx : Real) (dy : Real) (sigma : Real)
    (h1 : ((abs dx) <= COORD_MAX))
    (h2 : ((abs dy) <= COORD_MAX))
    (h3 : (sigma >= SIGMA_MIN))
    (h4 : (sigma <= SIGMA_MAX)) :
    (((spatial_gaussian_weight dx dy sigma) >= (0 : Real))) ∧ (((spatial_gaussian_weight dx dy sigma) <= (1 : Real))) := by
  unfold spatial_gaussian_weight
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
