-- Generated by the EML-lang Lean backend
-- Source module: bjt_collector_current
-- Source file:   <private>/bjt_collector_current.eml
-- Verified fns:  collector_current, collector_current_with_early, transconductance

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def VT_300K : Real := (0.025852 : Real)
noncomputable def IS_MIN : Real := (1e-18 : Real)
noncomputable def IS_MAX : Real := (1e-09 : Real)
noncomputable def VBE_MIN : Real := (-(0.5 : Real))
noncomputable def VBE_MAX : Real := (1.5 : Real)
noncomputable def VA_MIN : Real := (10.0 : Real)
noncomputable def VA_MAX : Real := (1000.0 : Real)

-- ── collector_current ──

noncomputable def collector_current (saturation_current : Real) (base_emitter_voltage : Real) (thermal_voltage : Real) : Real :=
  (saturation_current * ((Real.exp (base_emitter_voltage / thermal_voltage)) - (1 : Real)))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem ic_monotone_in_vbe (saturation_current : Real) (base_emitter_voltage : Real) (thermal_voltage : Real)
    (h1 : (saturation_current >= IS_MIN))
    (h2 : (saturation_current <= IS_MAX))
    (h3 : (base_emitter_voltage >= VBE_MIN))
    (h4 : (base_emitter_voltage <= VBE_MAX))
    (h5 : (thermal_voltage > (0 : Real)))
    (h6 : (thermal_voltage <= (0.1 : Real))) :
    True := by
  trivial

-- ── collector_current_with_early ──

noncomputable def collector_current_with_early (saturation_current : Real) (base_emitter_voltage : Real) (collector_emitter_voltage : Real) (thermal_voltage : Real) (early_voltage : Real) : Real :=
  ((saturation_current * ((Real.exp (base_emitter_voltage / thermal_voltage)) - (1 : Real))) * ((1 : Real) + (collector_emitter_voltage / early_voltage)))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem ic_with_early_increases_with_vce (saturation_current : Real) (base_emitter_voltage : Real) (collector_emitter_voltage : Real) (thermal_voltage : Real) (early_voltage : Real)
    (h1 : (saturation_current >= IS_MIN))
    (h2 : (saturation_current <= IS_MAX))
    (h3 : (base_emitter_voltage >= VBE_MIN))
    (h4 : (base_emitter_voltage <= VBE_MAX))
    (h5 : (collector_emitter_voltage >= (0 : Real)))
    (h6 : (collector_emitter_voltage <= (50.0 : Real)))
    (h7 : (thermal_voltage > (0 : Real)))
    (h8 : (thermal_voltage <= (0.1 : Real)))
    (h9 : (early_voltage >= VA_MIN))
    (h10 : (early_voltage <= VA_MAX)) :
    True := by
  trivial

-- ── transconductance ──

noncomputable def transconductance (collector_current : Real) (thermal_voltage : Real) : Real :=
  (collector_current / thermal_voltage)

theorem transconductance_proportional_to_ic (collector_current : Real) (thermal_voltage : Real)
    (h1 : (collector_current >= (0 : Real)))
    (h2 : (collector_current <= (1 : Real)))
    (h3 : (thermal_voltage > (0 : Real)))
    (h4 : (thermal_voltage <= (0.1 : Real))) :
    ((transconductance collector_current thermal_voltage) >= (0 : Real)) := by
  unfold transconductance
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
