-- Generated by the EML-lang Lean backend
-- Source module: black_scholes
-- Source file:   <private>/black_scholes.eml
-- Verified fns:  black_scholes_call, black_scholes_put

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def SQRT_2_OVER_PI : Real := (0.7978845608028654 : Real)
noncomputable def GELU_C3 : Real := (0.044715 : Real)
noncomputable def HALF : Real := (0.5 : Real)
noncomputable def TINY_T : Real := (0.000274 : Real)

axiom norm_cdf (x : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom bs_d1 (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom bs_d2 (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── black_scholes_call ──

noncomputable def black_scholes_call (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real :=
  ((spot * (HALF * ((1 : Real) + (Real.tanh (SQRT_2_OVER_PI * ((bs_d1 spot strike rate vol time_to_expiry) + (((GELU_C3 * (bs_d1 spot strike rate vol time_to_expiry)) * (bs_d1 spot strike rate vol time_to_expiry)) * (bs_d1 spot strike rate vol time_to_expiry)))))))) - ((strike * (Real.exp ((-rate) * time_to_expiry))) * (HALF * ((1 : Real) + (Real.tanh (SQRT_2_OVER_PI * (((bs_d1 spot strike rate vol time_to_expiry) - (vol * (Real.sqrt time_to_expiry))) + (((GELU_C3 * ((bs_d1 spot strike rate vol time_to_expiry) - (vol * (Real.sqrt time_to_expiry)))) * ((bs_d1 spot strike rate vol time_to_expiry) - (vol * (Real.sqrt time_to_expiry)))) * ((bs_d1 spot strike rate vol time_to_expiry) - (vol * (Real.sqrt time_to_expiry)))))))))))

theorem black_scholes_call_no_arb (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real)
    (h_spot : (spot > (0 : Real)))
    (h_strike : (strike > (0 : Real)))
    (h_vol : (vol > (0 : Real)))
    (h_time_to_expiry : (time_to_expiry > TINY_T)) :
    ((black_scholes_call spot strike rate vol time_to_expiry) >= (0 : Real)) := by
  unfold black_scholes_call
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── black_scholes_put ──

noncomputable def black_scholes_put (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real :=
  (((black_scholes_call spot strike rate vol time_to_expiry) - spot) + (strike * (Real.exp ((-rate) * time_to_expiry))))

theorem black_scholes_put_via_parity (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real)
    (h_spot : (spot > (0 : Real)))
    (h_strike : (strike > (0 : Real)))
    (h_vol : (vol > (0 : Real)))
    (h_time_to_expiry : (time_to_expiry > TINY_T)) :
    ((black_scholes_put spot strike rate vol time_to_expiry) >= (0 : Real)) := by
  unfold black_scholes_put
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
