-- Generated by the EML-lang Lean backend
-- Source module: boltzmann
-- Source file:   <private>/boltzmann.eml
-- Verified fns:  population_ratio

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def KB : Real := (1.380649e-23 : Real)
noncomputable def T_MIN : Real := (0.001 : Real)
noncomputable def T_MAX : Real := (100000000.0 : Real)

axiom maxwell_boltzmann_density (prefactor : Real) (mass : Real) (speed : Real) (temperature : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── population_ratio ──

noncomputable def population_ratio (energy_difference : Real) (temperature : Real) : Real :=
  (Real.exp ((-energy_difference) / (KB * temperature)))

theorem boltzmann_ratio_positive (energy_difference : Real) (temperature : Real)
    (h1 : (energy_difference >= (0 : Real)))
    (h2 : (temperature >= T_MIN))
    (h3 : (temperature <= T_MAX)) :
    (((population_ratio energy_difference temperature) >= (0 : Real))) ∧ (((population_ratio energy_difference temperature) <= (1 : Real))) := by
  unfold population_ratio
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
