import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: boltzmann
-- Source file:   <private>/boltzmann.eml
-- Verified fns:  population_ratio

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def KB : Real := (1.380649e-23 : Real)
noncomputable def T_MIN : Real := (0.001 : Real)
noncomputable def T_MAX : Real := (100000000.0 : Real)

axiom maxwell_boltzmann_density (prefactor : Real) (mass : Real) (speed : Real) (temperature : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── population_ratio ──

noncomputable def population_ratio (energy_difference : Real) (temperature : Real) : Real :=
  (Real.exp ((-energy_difference) / (KB * temperature)))

theorem boltzmann_ratio_positive (energy_difference : Real) (temperature : Real)
    (h1 : (energy_difference >= (0.0 : Real)))
    (h2 : (temperature >= T_MIN))
    (h3 : (temperature <= T_MAX)) :
    ((population_ratio energy_difference temperature) >= (0.0 : Real)) := by
  unfold population_ratio
  sorry  -- TODO: prove against MachLib foundations
