import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: butler_volmer
-- Source file:   <private>/butler_volmer.eml
-- Verified fns:  current_density

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def R_GAS : Real := (8.314462618 : Real)
noncomputable def F_FARAD : Real := (96485.33212 : Real)
noncomputable def T_MIN : Real := (200.0 : Real)
noncomputable def T_MAX : Real := (1000.0 : Real)
noncomputable def ETA_MAX : Real := (1.0 : Real)

axiom current_density_symmetric (exchange_current_density : Real) (alpha : Real) (overpotential : Real) (temperature : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── current_density ──

noncomputable def current_density (exchange_current_density : Real) (alpha_anodic : Real) (alpha_cathodic : Real) (overpotential : Real) (temperature : Real) : Real :=
  (exchange_current_density * ((Real.exp (alpha_anodic * ((F_FARAD * overpotential) / (R_GAS * temperature)))) - (Real.exp ((-alpha_cathodic) * ((F_FARAD * overpotential) / (R_GAS * temperature))))))

theorem butler_volmer_zero_at_zero_overpotential (exchange_current_density : Real) (alpha_anodic : Real) (alpha_cathodic : Real) (overpotential : Real) (temperature : Real)
    (h1 : (exchange_current_density > (0.0 : Real)))
    (h2 : (alpha_anodic > (0.0 : Real)))
    (h3 : (alpha_anodic <= (1.0 : Real)))
    (h4 : (alpha_cathodic > (0.0 : Real)))
    (h5 : (alpha_cathodic <= (1.0 : Real)))
    (h6 : (overpotential >= (-ETA_MAX)))
    (h7 : (overpotential <= ETA_MAX))
    (h8 : (temperature >= T_MIN))
    (h9 : (temperature <= T_MAX)) :
    True := by
  trivial
