-- Generated by the EML-lang Lean backend
-- Source module: carbon_intensity
-- Source file:   <private>/carbon_intensity.eml
-- Verified fns:  intensity, source_emissions, total_emissions_3way

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ENERGY_MIN : Real := (1e-06 : Real)
noncomputable def ENERGY_MAX : Real := (1000000000000000.0 : Real)
noncomputable def MASS_MAX : Real := (1e+18 : Real)
noncomputable def INTENSITY_MAX : Real := (1500.0 : Real)
noncomputable def USAGE_MAX : Real := (1000000000000.0 : Real)

-- ── intensity ──

noncomputable def intensity (mass_co2_eq : Real) (energy_delivered : Real) : Real :=
  (mass_co2_eq / energy_delivered)

theorem carbon_intensity_nonneg (mass_co2_eq : Real) (energy_delivered : Real)
    (h1 : (mass_co2_eq >= (0 : Real)))
    (h2 : (mass_co2_eq <= MASS_MAX))
    (h3 : (energy_delivered >= ENERGY_MIN))
    (h4 : (energy_delivered <= ENERGY_MAX)) :
    ((intensity mass_co2_eq energy_delivered) >= (0 : Real)) := by
  unfold intensity
  sorry  -- TODO: prove against MachLib foundations

-- ── source_emissions ──

noncomputable def source_emissions (usage : Real) (source_intensity : Real) : Real :=
  (usage * source_intensity)

theorem carbon_source_contribution_nonneg (usage : Real) (source_intensity : Real)
    (h1 : (usage >= (0 : Real)))
    (h2 : (usage <= USAGE_MAX))
    (h3 : (source_intensity >= (0 : Real)))
    (h4 : (source_intensity <= INTENSITY_MAX)) :
    ((source_emissions usage source_intensity) >= (0 : Real)) := by
  unfold source_emissions
  apply mul_nonneg <;> assumption

-- ── total_emissions_3way ──

noncomputable def total_emissions_3way (scope1 : Real) (scope2 : Real) (scope3 : Real) : Real :=
  ((scope1 + scope2) + scope3)

theorem carbon_total_above_each_source (scope1 : Real) (scope2 : Real) (scope3 : Real)
    (h1 : (scope1 >= (0 : Real)))
    (h2 : (scope2 >= (0 : Real)))
    (h3 : (scope3 >= (0 : Real)))
    (h4 : (scope1 <= MASS_MAX))
    (h5 : (scope2 <= MASS_MAX))
    (h6 : (scope3 <= MASS_MAX)) :
    ((total_emissions_3way scope1 scope2 scope3) >= scope1) := by
  unfold total_emissions_3way
  sorry  -- TODO: prove against MachLib foundations
