-- Generated by the EML-lang Lean backend
-- Source module: cfar_threshold
-- Source file:   <private>/cfar_threshold.eml
-- Verified fns:  cfar_threshold

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

axiom cfar_scale (p_fa : Real) (n_ref : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── cfar_threshold ──

noncomputable def cfar_threshold (window_mean : Real) (scale : Real) : Real :=
  (scale * window_mean)

theorem cfar_threshold_non_negative (window_mean : Real) (scale : Real)
    (h1 : (window_mean >= (0 : Real)))
    (h2 : (scale > (0 : Real))) :
    ((cfar_threshold window_mean scale) >= (0 : Real)) := by
  unfold cfar_threshold
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
