import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: cfar_threshold
-- Source file:   <private>/cfar_threshold.eml
-- Verified fns:  cfar_threshold

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

axiom cfar_scale (p_fa : Real) (n_ref : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── cfar_threshold ──

noncomputable def cfar_threshold (window_mean : Real) (scale : Real) : Real :=
  (scale * window_mean)

theorem cfar_threshold_non_negative (window_mean : Real) (scale : Real)
    (h1 : (window_mean >= (0.0 : Real)))
    (h2 : (scale > (0.0 : Real))) :
    ((cfar_threshold window_mean scale) >= (0.0 : Real)) := by
  unfold cfar_threshold
  sorry  -- TODO: prove against MachLib foundations
