import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: chacha20
-- Source file:   <private>/chacha20.eml
-- Verified fns:  quarter_round

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def ROUNDS : Int := 20
noncomputable def STATE : Int := 16
noncomputable def KEY_BITS : Int := 256

axiom wadd (a : Real) (b : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

axiom wxor (a : Real) (b : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

axiom rotl (a : Real) (n : Int) : Real  -- extern (axiomatised in MachLib/Discovered)

-- ── quarter_round ──

axiom quarter_round (a : Real) (b : Real) (c : Real) (d : Real) : Real -- tuple-return; axiomatised for now

theorem chacha20_quarter_round_invertible (a : Real) (b : Real) (c : Real) (d : Real)
    (h1 : True) :
    True := by
  trivial
