-- Generated by the EML-lang Lean backend
-- Source module: chirp_jammer
-- Source file:   <private>/chirp_jammer.eml
-- Verified fns:  chirp_phase, chirp_instantaneous_freq, chirp_sample

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def F0_MAX : Real := (10000000000.0 : Real)
noncomputable def RATE_MAX : Real := (1000000000000000.0 : Real)
noncomputable def T_MAX : Real := (1 : Real)
noncomputable def TWO_PI : Real := (6.283185307179586 : Real)

-- ── chirp_phase ──

noncomputable def chirp_phase (start_freq : Real) (chirp_rate : Real) (time_s : Real) : Real :=
  (TWO_PI * ((start_freq * time_s) + ((((0.5 : Real) * chirp_rate) * time_s) * time_s)))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem chirp_phase_zero_at_t0 (start_freq : Real) (chirp_rate : Real) (time_s : Real)
    (h1 : (start_freq >= (0 : Real)))
    (h2 : (start_freq <= F0_MAX))
    (h3 : ((abs chirp_rate) <= RATE_MAX))
    (h4 : (time_s >= (0 : Real)))
    (h5 : (time_s <= T_MAX)) :
    True := by
  trivial

-- ── chirp_instantaneous_freq ──

noncomputable def chirp_instantaneous_freq (start_freq : Real) (chirp_rate : Real) (time_s : Real) : Real :=
  (start_freq + (chirp_rate * time_s))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem chirp_instantaneous_freq_linear_in_t (start_freq : Real) (chirp_rate : Real) (time_s : Real)
    (h1 : (start_freq >= (0 : Real)))
    (h2 : (start_freq <= F0_MAX))
    (h3 : ((abs chirp_rate) <= RATE_MAX))
    (h4 : (time_s >= (0 : Real)))
    (h5 : (time_s <= T_MAX)) :
    True := by
  trivial

-- ── chirp_sample ──

noncomputable def chirp_sample (start_freq : Real) (chirp_rate : Real) (time_s : Real) : Real :=
  (Real.cos (TWO_PI * ((start_freq * time_s) + ((((0.5 : Real) * chirp_rate) * time_s) * time_s))))

theorem chirp_sample_bounded_by_unit (start_freq : Real) (chirp_rate : Real) (time_s : Real)
    (h1 : (start_freq >= (0 : Real)))
    (h2 : (start_freq <= F0_MAX))
    (h3 : ((abs chirp_rate) <= RATE_MAX))
    (h4 : (time_s >= (0 : Real)))
    (h5 : (time_s <= T_MAX)) :
    (((chirp_sample start_freq chirp_rate time_s) >= (-(1 : Real)))) ∧ (((chirp_sample start_freq chirp_rate time_s) <= (1 : Real))) := by
  unfold chirp_sample
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
