-- Generated by the EML-lang Lean backend
-- Source module: compressor
-- Source file:   <private>/compressor.eml
-- Verified fns:  hard_knee_gain, soft_knee_gain, linear_to_db, db_to_linear

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def THRESHOLD_MIN : Real := (-(60.0 : Real))
noncomputable def THRESHOLD_MAX : Real := (0 : Real)
noncomputable def RATIO_MIN : Real := (1 : Real)
noncomputable def RATIO_MAX : Real := (100.0 : Real)
noncomputable def KNEE_MIN : Real := (0 : Real)
noncomputable def KNEE_MAX : Real := (24.0 : Real)
noncomputable def LEVEL_MIN : Real := (-(120.0 : Real))
noncomputable def LEVEL_MAX : Real := (24.0 : Real)
noncomputable def LN10_INV : Real := (0.4342944819032518 : Real)

-- ── hard_knee_gain ──

noncomputable def hard_knee_gain (level_db : Real) (threshold_db : Real) (ratio : Real) : Real :=
  ((-(min (max (level_db - threshold_db) (0 : Real)) LEVEL_MAX)) * ((1 : Real) - ((1 : Real) / ratio)))

theorem hard_knee_unity_below_threshold (level_db : Real) (threshold_db : Real) (ratio : Real)
    (h1 : (level_db >= LEVEL_MIN))
    (h2 : (level_db <= LEVEL_MAX))
    (h3 : (threshold_db >= THRESHOLD_MIN))
    (h4 : (threshold_db <= THRESHOLD_MAX))
    (h5 : (ratio >= RATIO_MIN))
    (h6 : (ratio <= RATIO_MAX)) :
    ((hard_knee_gain level_db threshold_db ratio) <= (0 : Real)) := by
  unfold hard_knee_gain
  sorry  -- TODO: prove against MachLib foundations

-- ── soft_knee_gain ──

noncomputable def soft_knee_gain (level_db : Real) (threshold_db : Real) (ratio : Real) (knee_db : Real) : Real :=
  ((-((1 : Real) - ((1 : Real) / ratio))) * (((((min (max (level_db - threshold_db) (-((0.5 : Real) * knee_db))) ((0.5 : Real) * knee_db)) + ((0.5 : Real) * knee_db)) * ((min (max (level_db - threshold_db) (-((0.5 : Real) * knee_db))) ((0.5 : Real) * knee_db)) + ((0.5 : Real) * knee_db))) / ((2.0 : Real) * knee_db)) + (min (max ((level_db - threshold_db) - ((0.5 : Real) * knee_db)) (0 : Real)) LEVEL_MAX)))

theorem soft_knee_continuous_at_boundary (level_db : Real) (threshold_db : Real) (ratio : Real) (knee_db : Real)
    (h1 : (level_db >= LEVEL_MIN))
    (h2 : (level_db <= LEVEL_MAX))
    (h3 : (threshold_db >= THRESHOLD_MIN))
    (h4 : (threshold_db <= THRESHOLD_MAX))
    (h5 : (ratio >= RATIO_MIN))
    (h6 : (ratio <= RATIO_MAX))
    (h7 : (knee_db >= (KNEE_MIN + (0.001 : Real))))
    (h8 : (knee_db <= KNEE_MAX)) :
    True := by
  trivial

-- ── linear_to_db ──

noncomputable def linear_to_db (linear : Real) : Real :=
  (((20.0 : Real) * LN10_INV) * (Real.log linear))

theorem linear_to_db_monotone (linear : Real)
    (h1 : (linear >= (1e-09 : Real)))
    (h2 : (linear <= (8.0 : Real))) :
    True := by
  trivial

-- ── db_to_linear ──

noncomputable def db_to_linear (db : Real) : Real :=
  (Real.exp (db / ((20.0 : Real) * LN10_INV)))

theorem db_to_linear_monotone (db : Real)
    (h1 : (db >= LEVEL_MIN))
    (h2 : (db <= LEVEL_MAX)) :
    ((db_to_linear db) >= (0 : Real)) := by
  unfold db_to_linear
  exact exp_nonneg _
