import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: cross_entropy
-- Source file:   <private>/cross_entropy.eml
-- Verified fns:  bce_loss, bce_with_logits, categorical_ce_pair

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def MAX_LOGIT : Real := (30.0 : Real)
noncomputable def EPS : Real := (1e-07 : Real)

axiom bce_with_logits_grad (logit : Real) (target : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── bce_loss ──

noncomputable def bce_loss (prediction : Real) (target : Real) : Real :=
  (-((target * (Real.log prediction)) + (((1.0 : Real) - target) * (Real.log ((1.0 : Real) - prediction)))))

theorem bce_loss_nonnegative (prediction : Real) (target : Real)
    (h1 : (target >= (0.0 : Real)))
    (h2 : (target <= (1.0 : Real))) :
    ((bce_loss prediction target) >= (0.0 : Real)) := by
  unfold bce_loss
  sorry  -- TODO: prove against MachLib foundations

-- ── bce_with_logits ──

noncomputable def bce_with_logits (logit : Real) (target : Real) : Real :=
  (((min (max logit (0.0 : Real)) MAX_LOGIT) - (logit * target)) + (Real.log ((1.0 : Real) + (Real.exp (-(abs logit))))))

theorem bce_with_logits_equals_bce (logit : Real) (target : Real)
    (h1 : ((abs logit) < MAX_LOGIT))
    (h2 : (target >= (0.0 : Real)))
    (h3 : (target <= (1.0 : Real))) :
    ((bce_with_logits logit target) >= (0.0 : Real)) := by
  unfold bce_with_logits
  sorry  -- TODO: prove against MachLib foundations

-- ── categorical_ce_pair ──

noncomputable def categorical_ce_pair (logit : Real) (log_sum_exp_val : Real) (target_one_hot : Real) : Real :=
  (target_one_hot * (log_sum_exp_val - logit))

theorem categorical_ce_pair_nonnegative (logit : Real) (log_sum_exp_val : Real) (target_one_hot : Real)
    (h1 : ((abs logit) < MAX_LOGIT))
    (h2 : (target_one_hot >= (0.0 : Real)))
    (h3 : (target_one_hot <= (1.0 : Real))) :
    True := by
  trivial
