-- Generated by the EML-lang Lean backend
-- Source module: crystallization
-- Source file:   <private>/crystallization.eml
-- Verified fns:  relative_supersaturation, absolute_supersaturation, power_law_growth_rate

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def C_MAX : Real := (1000000.0 : Real)
noncomputable def KG_MAX : Real := (1000.0 : Real)
noncomputable def G_MAX : Real := (5.0 : Real)

-- ── relative_supersaturation ──

noncomputable def relative_supersaturation (concentration : Real) (saturation_concentration : Real) : Real :=
  (concentration / saturation_concentration)

-- source obligations for relative_supersaturation: {O1}
--   O1 [751dc336d483] -> PRESERVED (accounted)  theorem supersaturation_zero_at_solubility
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem supersaturation_zero_at_solubility (concentration : Real) (saturation_concentration : Real)
    (h1 : (concentration >= (0 : Real)))
    (h2 : (saturation_concentration > (0 : Real))) :
    (((relative_supersaturation concentration saturation_concentration) >= (0 : Real)) ∨ (concentration < saturation_concentration)) := by
  unfold relative_supersaturation
  try unfold C_MAX at *
  try unfold KG_MAX at *
  try unfold G_MAX at *
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── absolute_supersaturation ──

noncomputable def absolute_supersaturation (concentration : Real) (saturation_concentration : Real) : Real :=
  ((concentration - saturation_concentration) / saturation_concentration)

-- obligations for absolute_supersaturation: none declared (this artifact proves well-typedness only)
-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem absolute_supersaturation_zero_at_solubility (concentration : Real) (saturation_concentration : Real)
    (h1 : (concentration >= (0 : Real)))
    (h2 : (saturation_concentration > (0 : Real))) :
    True := by
  trivial

-- ── power_law_growth_rate ──

noncomputable def power_law_growth_rate (growth_constant : Real) (concentration : Real) (saturation_concentration : Real) (growth_exponent : Real) : Real :=
  (growth_constant * ((max (concentration - saturation_concentration) (0 : Real)) ^ growth_exponent))

-- source obligations for power_law_growth_rate: {O1}
--   O1 [79648937d4f0] -> PRESERVED (accounted)  theorem growth_rate_nonneg_above_solubility
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem growth_rate_nonneg_above_solubility (growth_constant : Real) (concentration : Real) (saturation_concentration : Real) (growth_exponent : Real)
    (h1 : (growth_constant >= (0 : Real)))
    (h2 : (growth_constant <= KG_MAX))
    (h3 : (concentration >= (0 : Real)))
    (h4 : (saturation_concentration > (0 : Real)))
    (h5 : (growth_exponent > (0 : Real)))
    (h6 : (growth_exponent <= G_MAX)) :
    ((power_law_growth_rate growth_constant concentration saturation_concentration growth_exponent) >= (0 : Real)) := by
  unfold power_law_growth_rate
  try unfold C_MAX at *
  try unfold KG_MAX at *
  try unfold G_MAX at *
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
