-- Generated by the EML-lang Lean backend
-- Source module: defibrillator_energy
-- Source file:   <private>/defibrillator_energy.eml
-- Verified fns:  discharge_voltage, phase1_energy, biphasic_total_energy, impedance_compensation_v0

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def C_MIN : Real := (5e-05 : Real)
noncomputable def C_MAX : Real := (0.0005 : Real)
noncomputable def R_MIN : Real := (25.0 : Real)
noncomputable def R_MAX : Real := (200.0 : Real)
noncomputable def V_MAX : Real := (5000.0 : Real)
noncomputable def T_MIN : Real := (0.001 : Real)
noncomputable def T_MAX : Real := (0.05 : Real)
noncomputable def HALF : Real := (0.5 : Real)

-- ── discharge_voltage ──

noncomputable def discharge_voltage (initial_voltage : Real) (duration : Real) (capacitance : Real) (impedance : Real) : Real :=
  (initial_voltage * (Real.exp ((-duration) / (impedance * capacitance))))

theorem discharge_voltage_decays_exponentially (initial_voltage : Real) (duration : Real) (capacitance : Real) (impedance : Real)
    (h1 : ((abs initial_voltage) <= V_MAX))
    (h2 : (duration >= (0 : Real)))
    (h3 : (duration <= T_MAX))
    (h4 : (capacitance >= C_MIN))
    (h5 : (capacitance <= C_MAX))
    (h6 : (impedance >= R_MIN))
    (h7 : (impedance <= R_MAX)) :
    True := by
  trivial

-- ── phase1_energy ──

noncomputable def phase1_energy (initial_voltage : Real) (final_voltage : Real) (capacitance : Real) : Real :=
  ((HALF * capacitance) * ((initial_voltage * initial_voltage) - (final_voltage * final_voltage)))

theorem phase1_energy_nonneg (initial_voltage : Real) (final_voltage : Real) (capacitance : Real)
    (h1 : ((abs initial_voltage) <= V_MAX))
    (h2 : ((abs final_voltage) <= V_MAX))
    (h3 : ((abs final_voltage) <= (abs initial_voltage)))
    (h4 : (capacitance >= C_MIN))
    (h5 : (capacitance <= C_MAX)) :
    ((phase1_energy initial_voltage final_voltage capacitance) >= (0 : Real)) := by
  unfold phase1_energy
  sorry  -- TODO: prove against MachLib foundations

-- ── biphasic_total_energy ──

noncomputable def biphasic_total_energy (initial_voltage : Real) (end_voltage : Real) (capacitance : Real) : Real :=
  ((HALF * capacitance) * (min (max ((initial_voltage * initial_voltage) - (end_voltage * end_voltage)) (0 : Real)) (V_MAX * V_MAX)))

theorem biphasic_total_energy_nonneg (initial_voltage : Real) (end_voltage : Real) (capacitance : Real)
    (h1 : ((abs initial_voltage) <= V_MAX))
    (h2 : ((abs end_voltage) <= V_MAX))
    (h3 : (capacitance >= C_MIN))
    (h4 : (capacitance <= C_MAX)) :
    ((biphasic_total_energy initial_voltage end_voltage capacitance) >= (0 : Real)) := by
  unfold biphasic_total_energy
  sorry  -- TODO: prove against MachLib foundations

-- ── impedance_compensation_v0 ──

noncomputable def impedance_compensation_v0 (target_joules : Real) (capacitance : Real) (duration : Real) (impedance : Real) : Real :=
  (Real.sqrt (((2.0 : Real) * target_joules) / (min (max (capacitance * ((1 : Real) - (Real.exp (((-2.0 : Real) * duration) / (impedance * capacitance))))) (1e-09 : Real)) (1 : Real))))

theorem compensation_v0_increases_with_target_energy (target_joules : Real) (capacitance : Real) (duration : Real) (impedance : Real)
    (h1 : (target_joules >= (0 : Real)))
    (h2 : (target_joules <= (360.0 : Real)))
    (h3 : (capacitance >= C_MIN))
    (h4 : (capacitance <= C_MAX))
    (h5 : (duration >= T_MIN))
    (h6 : (duration <= T_MAX))
    (h7 : (impedance >= R_MIN))
    (h8 : (impedance <= R_MAX)) :
    ((impedance_compensation_v0 target_joules capacitance duration impedance) >= (0 : Real)) := by
  unfold impedance_compensation_v0
  exact sqrt_nonneg _
