-- Generated by the EML-lang Lean backend
-- Source module: delta
-- Source file:   <private>/delta.eml
-- Verified fns:  call_delta, put_delta

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def SQRT_2_OVER_PI : Real := (0.7978845608028654 : Real)
noncomputable def GELU_C3 : Real := (0.044715 : Real)
noncomputable def HALF : Real := (0.5 : Real)
noncomputable def TINY_T : Real := (0.000274 : Real)

axiom norm_cdf (x : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom d1 (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── call_delta ──

noncomputable def call_delta (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real :=
  (HALF * ((1 : Real) + (Real.tanh (SQRT_2_OVER_PI * ((d1 spot strike rate vol time_to_expiry) + (((GELU_C3 * (d1 spot strike rate vol time_to_expiry)) * (d1 spot strike rate vol time_to_expiry)) * (d1 spot strike rate vol time_to_expiry)))))))

-- source obligations for call_delta: {O1, O2}
--   O1 [eda10f5dee21] -> PRESERVED (accounted)  theorem bs_call_delta_in_zero_one
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
--   O2 [42a6198f18c0] -> PRESERVED (accounted)  theorem bs_call_delta_in_zero_one
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem bs_call_delta_in_zero_one (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real)
    (h_spot : (spot > (0 : Real)))
    (h_strike : (strike > (0 : Real)))
    (h_vol : (vol > (0 : Real)))
    (h_time_to_expiry : (time_to_expiry > TINY_T)) :
    (((call_delta spot strike rate vol time_to_expiry) >= (0 : Real))) ∧ (((call_delta spot strike rate vol time_to_expiry) <= (1 : Real))) := by
  unfold call_delta
  try unfold SQRT_2_OVER_PI at *
  try unfold GELU_C3 at *
  try unfold HALF at *
  try unfold TINY_T at *
  try mach_split_hyps
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover

-- ── put_delta ──

noncomputable def put_delta (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real :=
  ((HALF * ((1 : Real) + (Real.tanh (SQRT_2_OVER_PI * ((d1 spot strike rate vol time_to_expiry) + (((GELU_C3 * (d1 spot strike rate vol time_to_expiry)) * (d1 spot strike rate vol time_to_expiry)) * (d1 spot strike rate vol time_to_expiry))))))) - (1 : Real))

-- source obligations for put_delta: {O1, O2}
--   O1 [45385b3def34] -> PRESERVED (accounted)  theorem bs_put_delta_in_minus_one_zero
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
--   O2 [6da1aea7f3f3] -> PRESERVED (accounted)  theorem bs_put_delta_in_minus_one_zero
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem bs_put_delta_in_minus_one_zero (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real)
    (h_spot : (spot > (0 : Real)))
    (h_strike : (strike > (0 : Real)))
    (h_vol : (vol > (0 : Real)))
    (h_time_to_expiry : (time_to_expiry > TINY_T)) :
    (((put_delta spot strike rate vol time_to_expiry) >= (-(1 : Real)))) ∧ (((put_delta spot strike rate vol time_to_expiry) <= (0 : Real))) := by
  unfold put_delta
  try unfold SQRT_2_OVER_PI at *
  try unfold GELU_C3 at *
  try unfold HALF at *
  try unfold TINY_T at *
  try mach_split_hyps
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
