import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: delta
-- Source file:   <private>/delta.eml
-- Verified fns:  call_delta, put_delta

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def SQRT_2_OVER_PI : Real := (0.7978845608028654 : Real)
noncomputable def GELU_C3 : Real := (0.044715 : Real)
noncomputable def HALF : Real := (0.5 : Real)
noncomputable def TINY_T : Real := (0.000274 : Real)

axiom norm_cdf (x : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom d1 (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── call_delta ──

noncomputable def call_delta (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real :=
  (HALF * ((1.0 : Real) + (Real.tanh (SQRT_2_OVER_PI * ((d1 spot strike rate vol time_to_expiry) + (((GELU_C3 * (d1 spot strike rate vol time_to_expiry)) * (d1 spot strike rate vol time_to_expiry)) * (d1 spot strike rate vol time_to_expiry)))))))

theorem bs_call_delta_in_zero_one (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real)
    (h1 : (spot > (0.0 : Real)))
    (h2 : (strike > (0.0 : Real)))
    (h3 : (vol > (0.0 : Real)))
    (h4 : (time_to_expiry > TINY_T)) :
    ((call_delta spot strike rate vol time_to_expiry) >= (0.0 : Real)) := by
  unfold call_delta
  sorry  -- TODO: prove against MachLib foundations

-- ── put_delta ──

noncomputable def put_delta (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real :=
  ((HALF * ((1.0 : Real) + (Real.tanh (SQRT_2_OVER_PI * ((d1 spot strike rate vol time_to_expiry) + (((GELU_C3 * (d1 spot strike rate vol time_to_expiry)) * (d1 spot strike rate vol time_to_expiry)) * (d1 spot strike rate vol time_to_expiry))))))) - (1.0 : Real))

theorem bs_put_delta_in_minus_one_zero (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real)
    (h1 : (spot > (0.0 : Real)))
    (h2 : (strike > (0.0 : Real)))
    (h3 : (vol > (0.0 : Real)))
    (h4 : (time_to_expiry > TINY_T)) :
    ((put_delta spot strike rate vol time_to_expiry) >= (-(1.0 : Real))) := by
  unfold put_delta
  sorry  -- TODO: prove against MachLib foundations
