-- Generated by the EML-lang Lean backend
-- Source module: doppler_velocity
-- Source file:   <private>/doppler_velocity.eml
-- Verified fns:  doppler_shift_hz, velocity_from_shift, unambiguous_velocity, velocity_resolution

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def LAMBDA_MIN : Real := (1e-06 : Real)
noncomputable def LAMBDA_MAX : Real := (1000.0 : Real)
noncomputable def VEL_MAX : Real := (10000.0 : Real)
noncomputable def FREQ_MAX : Real := (1000000000.0 : Real)
noncomputable def PRF_MIN : Real := (100.0 : Real)
noncomputable def PRF_MAX : Real := (1000000.0 : Real)

-- ── doppler_shift_hz ──

noncomputable def doppler_shift_hz (radial_velocity : Real) (wavelength : Real) : Real :=
  (((2.0 : Real) * radial_velocity) / wavelength)

theorem doppler_shift_proportional_to_velocity (radial_velocity : Real) (wavelength : Real)
    (h1 : ((abs radial_velocity) <= VEL_MAX))
    (h2 : (wavelength >= LAMBDA_MIN))
    (h3 : (wavelength <= LAMBDA_MAX)) :
    True := by
  trivial

-- ── velocity_from_shift ──

noncomputable def velocity_from_shift (doppler_hz : Real) (wavelength : Real) : Real :=
  (((0.5 : Real) * doppler_hz) * wavelength)

theorem velocity_from_shift_signed (doppler_hz : Real) (wavelength : Real)
    (h1 : ((abs doppler_hz) <= FREQ_MAX))
    (h2 : (wavelength >= LAMBDA_MIN))
    (h3 : (wavelength <= LAMBDA_MAX)) :
    True := by
  trivial

-- ── unambiguous_velocity ──

noncomputable def unambiguous_velocity (pulse_repetition_freq : Real) (wavelength : Real) : Real :=
  (((0.25 : Real) * wavelength) * pulse_repetition_freq)

theorem unambiguous_velocity_proportional_to_prf (pulse_repetition_freq : Real) (wavelength : Real)
    (h1 : (pulse_repetition_freq >= PRF_MIN))
    (h2 : (pulse_repetition_freq <= PRF_MAX))
    (h3 : (wavelength >= LAMBDA_MIN))
    (h4 : (wavelength <= LAMBDA_MAX)) :
    ((unambiguous_velocity pulse_repetition_freq wavelength) > (0 : Real)) := by
  unfold unambiguous_velocity
  sorry  -- TODO: prove against MachLib foundations

-- ── velocity_resolution ──

noncomputable def velocity_resolution (n_pulses : Real) (pulse_repetition_freq : Real) (wavelength : Real) : Real :=
  ((((0.5 : Real) * wavelength) * pulse_repetition_freq) / n_pulses)

theorem velocity_resolution_inverse_to_dwell (n_pulses : Real) (pulse_repetition_freq : Real) (wavelength : Real)
    (h1 : (n_pulses >= (1 : Real)))
    (h2 : (n_pulses <= (1000000.0 : Real)))
    (h3 : (pulse_repetition_freq >= PRF_MIN))
    (h4 : (pulse_repetition_freq <= PRF_MAX))
    (h5 : (wavelength >= LAMBDA_MIN))
    (h6 : (wavelength <= LAMBDA_MAX)) :
    ((velocity_resolution n_pulses pulse_repetition_freq wavelength) >= (0 : Real)) := by
  unfold velocity_resolution
  sorry  -- TODO: prove against MachLib foundations
