-- Generated by the EML-lang Lean backend
-- Source module: dose_response
-- Source file:   <private>/dose_response.eml
-- Verified fns:  effect

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def C_MAX : Real := (1000.0 : Real)
noncomputable def N_MAX : Real := (8.0 : Real)
noncomputable def EC50_MAX : Real := (1000.0 : Real)

axiom inhibitor_effect (e_baseline : Real) (concentration : Real) (ic50 : Real) (hill_coefficient : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── effect ──

noncomputable def effect (e_max : Real) (concentration : Real) (ec50 : Real) (hill_coefficient : Real) : Real :=
  ((e_max * (concentration ^ hill_coefficient)) / ((ec50 ^ hill_coefficient) + (concentration ^ hill_coefficient)))

theorem dose_response_saturating (e_max : Real) (concentration : Real) (ec50 : Real) (hill_coefficient : Real)
    (h1 : (e_max >= (0 : Real)))
    (h2 : (concentration >= (0 : Real)))
    (h3 : (concentration <= C_MAX))
    (h4 : (ec50 > (0 : Real)))
    (h5 : (ec50 <= EC50_MAX))
    (h6 : (hill_coefficient > (0 : Real)))
    (h7 : (hill_coefficient <= N_MAX)) :
    ((effect e_max concentration ec50 hill_coefficient) >= (0 : Real)) := by
  unfold effect
  sorry  -- TODO: prove against MachLib foundations
