-- Generated by the EML-lang Lean backend
-- Source module: ecdsa
-- Source file:   <private>/ecdsa.eml
-- Verified fns:  scalar_mul_x, sign_r

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def CURVE_BITS : Int := 256
noncomputable def HASH_BITS : Int := 256

axiom montgomery_ladder_p256_x (scalar : Real) (point_x : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

axiom sign_p256_r (d : Real) (k : Real) (h : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

-- ── scalar_mul_x ──

noncomputable def scalar_mul_x (scalar : Real) (point_x : Real) : Real :=
  (montgomery_ladder_p256_x scalar point_x)

theorem ecdsa_scalar_mul_correct (scalar : Real) (point_x : Real)
    (h1 : True) :
    True := by
  trivial

-- ── sign_r ──

noncomputable def sign_r (private_key : Real) (nonce : Real) (msg_hash : Real) : Real :=
  (sign_p256_r private_key nonce msg_hash)

theorem ecdsa_sign_correct (private_key : Real) (nonce : Real) (msg_hash : Real)
    (h1 : (nonce > (0 : Real))) :
    True := by
  trivial
