-- Generated by the EML-lang Lean backend
-- Source module: ed25519
-- Source file:   <private>/ed25519.eml
-- Verified fns:  edwards_add_y, sign_r

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def FIELD_BITS : Int := 255
noncomputable def ORDER_BITS : Int := 252
noncomputable def SIG_BYTES : Int := 64

axiom edwards_add_complete_y (p_y : Real) (q_y : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

axiom sign_ed25519_r (sk : Real) (msg_first : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

-- ── edwards_add_y ──

noncomputable def edwards_add_y (p_y : Real) (q_y : Real) : Real :=
  (edwards_add_complete_y p_y q_y)

theorem ed25519_point_addition_complete (p_y : Real) (q_y : Real)
    (h1 : True) :
    True := by
  trivial

-- ── sign_r ──

noncomputable def sign_r (private_key : Real) (msg_first : Real) : Real :=
  (sign_ed25519_r private_key msg_first)

theorem ed25519_sign_correct (private_key : Real) (msg_first : Real)
    (h1 : True) :
    True := by
  trivial
