-- Generated by the EML-lang Lean backend
-- Source module: energy_budget
-- Source file:   <private>/energy_budget.eml
-- Verified fns:  equilibrium_temperature, climate_response, toa_imbalance

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def SOLAR_CONSTANT : Real := (1361.0 : Real)
noncomputable def SIGMA_SB : Real := (5.670374419e-08 : Real)
noncomputable def QUARTER : Real := (0.25 : Real)
noncomputable def ALBEDO_MIN : Real := (0 : Real)
noncomputable def ALBEDO_MAX : Real := (1 : Real)
noncomputable def EPS_MIN : Real := (0.05 : Real)
noncomputable def EPS_MAX : Real := (1 : Real)

-- ── equilibrium_temperature ──

noncomputable def equilibrium_temperature (solar_flux : Real) (albedo : Real) (emissivity : Real) : Real :=
  ((((((1 : Real) - albedo) * solar_flux) * QUARTER) / (emissivity * SIGMA_SB)) ^ QUARTER)

theorem equilibrium_temperature_decreasing_in_albedo (solar_flux : Real) (albedo : Real) (emissivity : Real)
    (h1 : (solar_flux > (0 : Real)))
    (h2 : (solar_flux <= ((4.0 : Real) * SOLAR_CONSTANT)))
    (h3 : (albedo >= ALBEDO_MIN))
    (h4 : (albedo <= ALBEDO_MAX))
    (h5 : (emissivity >= EPS_MIN))
    (h6 : (emissivity <= EPS_MAX)) :
    ((equilibrium_temperature solar_flux albedo emissivity) > (0 : Real)) := by
  unfold equilibrium_temperature
  sorry  -- TODO: prove against MachLib foundations

-- ── climate_response ──

noncomputable def climate_response (forcing : Real) (lambda : Real) : Real :=
  (forcing / lambda)

theorem climate_response_linear_in_forcing (forcing : Real) (lambda : Real)
    (h1 : ((abs forcing) <= (100.0 : Real)))
    (h2 : (lambda > (0.05 : Real)))
    (h3 : (lambda <= (5.0 : Real))) :
    True := by
  trivial

-- ── toa_imbalance ──

noncomputable def toa_imbalance (solar_flux : Real) (albedo : Real) (emissivity : Real) (surface_t : Real) : Real :=
  (((((1 : Real) - albedo) * solar_flux) * QUARTER) - ((emissivity * SIGMA_SB) * (surface_t ^ (4.0 : Real))))

theorem toa_imbalance_zero_at_equilibrium (solar_flux : Real) (albedo : Real) (emissivity : Real) (surface_t : Real)
    (h1 : (solar_flux > (0 : Real)))
    (h2 : (solar_flux <= ((4.0 : Real) * SOLAR_CONSTANT)))
    (h3 : (albedo >= ALBEDO_MIN))
    (h4 : (albedo <= ALBEDO_MAX))
    (h5 : (emissivity >= EPS_MIN))
    (h6 : (emissivity <= EPS_MAX))
    (h7 : (surface_t > (0 : Real)))
    (h8 : (surface_t <= (1000.0 : Real))) :
    True := by
  trivial
