-- Generated by the EML-lang Lean backend
-- Source module: enzyme_inhibition
-- Source file:   <private>/enzyme_inhibition.eml
-- Verified fns:  competitive_rate, noncompetitive_rate, uncompetitive_rate, ic50_competitive

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def VMAX_MAX : Real := (1000000.0 : Real)
noncomputable def KM_MIN : Real := (1e-09 : Real)
noncomputable def KM_MAX : Real := (1000.0 : Real)
noncomputable def S_MAX : Real := (1000.0 : Real)
noncomputable def I_MAX : Real := (1000.0 : Real)
noncomputable def KI_MIN : Real := (1e-09 : Real)
noncomputable def KI_MAX : Real := (1000.0 : Real)

-- ── competitive_rate ──

noncomputable def competitive_rate (vmax : Real) (substrate : Real) (km : Real) (inhibitor : Real) (ki : Real) : Real :=
  ((vmax * substrate) / ((((1 : Real) + (inhibitor / ki)) * km) + substrate))

theorem competitive_decreases_with_inhibitor (vmax : Real) (substrate : Real) (km : Real) (inhibitor : Real) (ki : Real)
    (h1 : (vmax > (0 : Real)))
    (h2 : (vmax <= VMAX_MAX))
    (h3 : (substrate >= (0 : Real)))
    (h4 : (substrate <= S_MAX))
    (h5 : (km >= KM_MIN))
    (h6 : (km <= KM_MAX))
    (h7 : (inhibitor >= (0 : Real)))
    (h8 : (inhibitor <= I_MAX))
    (h9 : (ki >= KI_MIN))
    (h10 : (ki <= KI_MAX)) :
    ((competitive_rate vmax substrate km inhibitor ki) >= (0 : Real)) := by
  unfold competitive_rate
  sorry  -- TODO: prove against MachLib foundations

-- ── noncompetitive_rate ──

noncomputable def noncompetitive_rate (vmax : Real) (substrate : Real) (km : Real) (inhibitor : Real) (ki : Real) : Real :=
  (((vmax / ((1 : Real) + (inhibitor / ki))) * substrate) / (km + substrate))

theorem noncompetitive_lowers_vmax_only (vmax : Real) (substrate : Real) (km : Real) (inhibitor : Real) (ki : Real)
    (h1 : (vmax > (0 : Real)))
    (h2 : (vmax <= VMAX_MAX))
    (h3 : (substrate >= (0 : Real)))
    (h4 : (substrate <= S_MAX))
    (h5 : (km >= KM_MIN))
    (h6 : (km <= KM_MAX))
    (h7 : (inhibitor >= (0 : Real)))
    (h8 : (inhibitor <= I_MAX))
    (h9 : (ki >= KI_MIN))
    (h10 : (ki <= KI_MAX)) :
    ((noncompetitive_rate vmax substrate km inhibitor ki) >= (0 : Real)) := by
  unfold noncompetitive_rate
  sorry  -- TODO: prove against MachLib foundations

-- ── uncompetitive_rate ──

noncomputable def uncompetitive_rate (vmax : Real) (substrate : Real) (km : Real) (inhibitor : Real) (ki : Real) : Real :=
  (((vmax / ((1 : Real) + (inhibitor / ki))) * substrate) / ((km / ((1 : Real) + (inhibitor / ki))) + substrate))

theorem uncompetitive_scales_both (vmax : Real) (substrate : Real) (km : Real) (inhibitor : Real) (ki : Real)
    (h1 : (vmax > (0 : Real)))
    (h2 : (vmax <= VMAX_MAX))
    (h3 : (substrate >= (0 : Real)))
    (h4 : (substrate <= S_MAX))
    (h5 : (km >= KM_MIN))
    (h6 : (km <= KM_MAX))
    (h7 : (inhibitor >= (0 : Real)))
    (h8 : (inhibitor <= I_MAX))
    (h9 : (ki >= KI_MIN))
    (h10 : (ki <= KI_MAX)) :
    ((uncompetitive_rate vmax substrate km inhibitor ki) >= (0 : Real)) := by
  unfold uncompetitive_rate
  sorry  -- TODO: prove against MachLib foundations

-- ── ic50_competitive ──

noncomputable def ic50_competitive (ki : Real) (substrate : Real) (km : Real) : Real :=
  (ki * ((1 : Real) + (substrate / km)))

theorem ic50_grows_with_substrate (ki : Real) (substrate : Real) (km : Real)
    (h1 : (ki >= KI_MIN))
    (h2 : (ki <= KI_MAX))
    (h3 : (substrate >= (0 : Real)))
    (h4 : (substrate <= S_MAX))
    (h5 : (km >= KM_MIN))
    (h6 : (km <= KM_MAX)) :
    ((ic50_competitive ki substrate km) >= (0 : Real)) := by
  unfold ic50_competitive
  sorry  -- TODO: prove against MachLib foundations
