-- Generated by the EML-lang Lean backend
-- Source module: particle_euler_step
-- Source file:   <private>/euler_step.eml
-- Verified fns:  velocity_step, position_step, velocity_step_with_drag

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def DT_MAX : Real := (0.1 : Real)
noncomputable def VEL_MAX : Real := (10000.0 : Real)
noncomputable def ACC_MAX : Real := (10000.0 : Real)
noncomputable def DRAG_MAX : Real := (50.0 : Real)

-- ── velocity_step ──

noncomputable def velocity_step (velocity : Real) (acceleration : Real) (dt : Real) : Real :=
  (velocity + (acceleration * dt))

theorem euler_step_velocity_linear_in_acceleration (velocity : Real) (acceleration : Real) (dt : Real)
    (h1 : (dt >= (0 : Real)))
    (h2 : (dt <= DT_MAX))
    (h3 : (velocity >= (-VEL_MAX)))
    (h4 : (velocity <= VEL_MAX))
    (h5 : (acceleration >= (-ACC_MAX)))
    (h6 : (acceleration <= ACC_MAX)) :
    True := by
  trivial

-- ── position_step ──

noncomputable def position_step (position : Real) (velocity_new : Real) (dt : Real) : Real :=
  (position + (velocity_new * dt))

theorem euler_step_position_linear_in_velocity (position : Real) (velocity_new : Real) (dt : Real)
    (h1 : (dt >= (0 : Real)))
    (h2 : (dt <= DT_MAX))
    (h3 : (velocity_new >= (-VEL_MAX)))
    (h4 : (velocity_new <= VEL_MAX)) :
    True := by
  trivial

-- ── velocity_step_with_drag ──

noncomputable def velocity_step_with_drag (velocity : Real) (acceleration : Real) (drag_coefficient : Real) (dt : Real) : Real :=
  ((velocity * (Real.exp ((-drag_coefficient) * dt))) + (acceleration * dt))

theorem euler_step_drag_decays_velocity (velocity : Real) (acceleration : Real) (drag_coefficient : Real) (dt : Real)
    (h1 : (dt >= (0 : Real)))
    (h2 : (dt <= DT_MAX))
    (h3 : (velocity >= (-VEL_MAX)))
    (h4 : (velocity <= VEL_MAX))
    (h5 : (acceleration >= (-ACC_MAX)))
    (h6 : (acceleration <= ACC_MAX))
    (h7 : (drag_coefficient >= (0 : Real)))
    (h8 : (drag_coefficient <= DRAG_MAX)) :
    True := by
  trivial
