import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: falcon
-- Source file:   <private>/falcon.eml
-- Verified fns:  ntt_butterfly

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def FALCON_N : Int := 512
noncomputable def FALCON_Q : Int := 12289

axiom gaussian_sample (seed : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

axiom falcon_butterfly (coeff : Real) (twiddle : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

-- ── ntt_butterfly ──

noncomputable def ntt_butterfly (coeff : Real) (twiddle : Real) : Real :=
  (falcon_butterfly coeff twiddle)

theorem falcon_ntt_correct (coeff : Real) (twiddle : Real)
    (h1 : True) :
    True := by
  trivial
