-- Generated by the EML-lang Lean backend
-- Source module: farquhar_c3
-- Source file:   <private>/farquhar_c3.eml
-- Verified fns:  rubisco_limited, light_limited, net_assimilation

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def FOUR : Real := (4.0 : Real)
noncomputable def EIGHT : Real := (8.0 : Real)
noncomputable def ONE : Real := (1 : Real)
noncomputable def CI_MIN : Real := (1 : Real)
noncomputable def CI_MAX : Real := (1500.0 : Real)
noncomputable def O2_MIN : Real := (10000.0 : Real)
noncomputable def O2_MAX : Real := (300000.0 : Real)
noncomputable def VCMAX_MAX : Real := (300.0 : Real)
noncomputable def J_MAX : Real := (500.0 : Real)
noncomputable def RD_MAX : Real := (10.0 : Real)
noncomputable def GAMMA_MAX : Real := (100.0 : Real)

-- ── rubisco_limited ──

noncomputable def rubisco_limited (ci : Real) (gamma_star : Real) (vcmax : Real) (kc : Real) (ko : Real) (o2 : Real) : Real :=
  ((vcmax * (ci - gamma_star)) / (ci + (kc * (ONE + (o2 / ko)))))

theorem farquhar_ac_nonneg_when_ci_above_gamma_star (ci : Real) (gamma_star : Real) (vcmax : Real) (kc : Real) (ko : Real) (o2 : Real)
    (h1 : (ci >= CI_MIN))
    (h2 : (ci <= CI_MAX))
    (h3 : (gamma_star >= (0 : Real)))
    (h4 : (gamma_star <= GAMMA_MAX))
    (h5 : (gamma_star <= ci))
    (h6 : (vcmax >= (0 : Real)))
    (h7 : (vcmax <= VCMAX_MAX))
    (h8 : (kc > (0 : Real)))
    (h9 : (ko > (0 : Real)))
    (h10 : (o2 >= O2_MIN))
    (h11 : (o2 <= O2_MAX)) :
    ((rubisco_limited ci gamma_star vcmax kc ko o2) >= (0 : Real)) := by
  unfold rubisco_limited
  sorry  -- TODO: prove against MachLib foundations

-- ── light_limited ──

noncomputable def light_limited (ci : Real) (gamma_star : Real) (electron_transport : Real) : Real :=
  ((electron_transport * (ci - gamma_star)) / ((FOUR * ci) + (EIGHT * gamma_star)))

theorem farquhar_aj_nonneg_when_ci_above_gamma_star (ci : Real) (gamma_star : Real) (electron_transport : Real)
    (h1 : (ci >= CI_MIN))
    (h2 : (ci <= CI_MAX))
    (h3 : (gamma_star >= (0 : Real)))
    (h4 : (gamma_star <= GAMMA_MAX))
    (h5 : (gamma_star <= ci))
    (h6 : (electron_transport >= (0 : Real)))
    (h7 : (electron_transport <= J_MAX)) :
    ((light_limited ci gamma_star electron_transport) >= (0 : Real)) := by
  unfold light_limited
  sorry  -- TODO: prove against MachLib foundations

-- ── net_assimilation ──

noncomputable def net_assimilation (rubisco_rate : Real) (light_rate : Real) (dark_respiration : Real) : Real :=
  ((min rubisco_rate light_rate) - dark_respiration)

theorem farquhar_net_below_min_of_limits (rubisco_rate : Real) (light_rate : Real) (dark_respiration : Real)
    (h1 : (rubisco_rate >= (0 : Real)))
    (h2 : (rubisco_rate <= VCMAX_MAX))
    (h3 : (light_rate >= (0 : Real)))
    (h4 : (light_rate <= J_MAX))
    (h5 : (dark_respiration >= (0 : Real)))
    (h6 : (dark_respiration <= RD_MAX)) :
    True := by
  trivial
