-- Generated by the EML-lang Lean backend
-- Source module: feed_rate
-- Source file:   <private>/feed_rate.eml
-- Verified fns:  linear_feed, rpm_from_cutting_speed, material_removal_rate

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def PI : Real := (3.141592653589793 : Real)
noncomputable def D_MIN : Real := (0.1 : Real)
noncomputable def D_MAX : Real := (200.0 : Real)
noncomputable def RPM_MIN : Real := (10.0 : Real)
noncomputable def RPM_MAX : Real := (60000.0 : Real)
noncomputable def N_MIN : Real := (1 : Real)
noncomputable def N_MAX : Real := (32.0 : Real)
noncomputable def FZ_MIN : Real := (0.001 : Real)
noncomputable def FZ_MAX : Real := (1 : Real)
noncomputable def SCUT_MIN : Real := (1 : Real)
noncomputable def SCUT_MAX : Real := (50000.0 : Real)

axiom chip_thinning_compensation (feed_per_tooth : Real) (diameter : Real) (radial_engagement : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── linear_feed ──

noncomputable def linear_feed (num_teeth : Real) (feed_per_tooth : Real) (rpm : Real) : Real :=
  ((num_teeth * feed_per_tooth) * rpm)

theorem cnc_feed_proportional_to_rpm (num_teeth : Real) (feed_per_tooth : Real) (rpm : Real)
    (h_num_teeth : ((N_MIN <= num_teeth) ∧ (num_teeth <= N_MAX)))
    (h_feed_per_tooth : ((FZ_MIN <= feed_per_tooth) ∧ (feed_per_tooth <= FZ_MAX)))
    (h_rpm : ((RPM_MIN <= rpm) ∧ (rpm <= RPM_MAX))) :
    ((linear_feed num_teeth feed_per_tooth rpm) >= (0 : Real)) := by
  unfold linear_feed
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── rpm_from_cutting_speed ──

noncomputable def rpm_from_cutting_speed (cutting_speed : Real) (diameter : Real) : Real :=
  (cutting_speed / (PI * diameter))

theorem rpm_inversely_proportional_to_diameter (cutting_speed : Real) (diameter : Real)
    (h_cutting_speed : ((SCUT_MIN <= cutting_speed) ∧ (cutting_speed <= SCUT_MAX)))
    (h_diameter : ((D_MIN <= diameter) ∧ (diameter <= D_MAX))) :
    ((rpm_from_cutting_speed cutting_speed diameter) >= (0 : Real)) := by
  unfold rpm_from_cutting_speed
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── material_removal_rate ──

noncomputable def material_removal_rate (feed_mm_per_min : Real) (radial_engagement : Real) (axial_depth : Real) : Real :=
  (((feed_mm_per_min * radial_engagement) * axial_depth) / (1000.0 : Real))

theorem mrr_nonneg (feed_mm_per_min : Real) (radial_engagement : Real) (axial_depth : Real)
    (h_feed_mm_per_min : (((0 : Real) <= feed_mm_per_min) ∧ (feed_mm_per_min <= (100000.0 : Real))))
    (h_radial_engagement : (((0 : Real) <= radial_engagement) ∧ (radial_engagement <= D_MAX)))
    (h_axial_depth : (((0 : Real) <= axial_depth) ∧ (axial_depth <= D_MAX))) :
    ((material_removal_rate feed_mm_per_min radial_engagement axial_depth) >= (0 : Real)) := by
  unfold material_removal_rate
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
