import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: flory_huggins
-- Source file:   <private>/flory_huggins.eml
-- Verified fns:  delta_g_per_site

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def N_MAX : Real := (1000000.0 : Real)
noncomputable def PHI_MIN : Real := (1e-09 : Real)
noncomputable def CHI_MAX : Real := (100.0 : Real)

axiom chi_critical_symmetric (degree_of_polymerisation : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── delta_g_per_site ──

noncomputable def delta_g_per_site (phi_1 : Real) (n_1 : Real) (phi_2 : Real) (n_2 : Real) (chi : Real) : Real :=
  ((((phi_1 / n_1) * (log phi_1)) + ((phi_2 / n_2) * (log phi_2))) + ((chi * phi_1) * phi_2))

theorem flory_huggins_symmetric_under_phi_swap (phi_1 : Real) (n_1 : Real) (phi_2 : Real) (n_2 : Real) (chi : Real)
    (h1 : (phi_1 >= PHI_MIN))
    (h2 : (phi_1 <= (1.0 : Real)))
    (h3 : (phi_2 >= PHI_MIN))
    (h4 : (phi_2 <= (1.0 : Real)))
    (h5 : (n_1 >= (1.0 : Real)))
    (h6 : (n_1 <= N_MAX))
    (h7 : (n_2 >= (1.0 : Real)))
    (h8 : (n_2 <= N_MAX))
    (h9 : (chi >= (-CHI_MAX)))
    (h10 : (chi <= CHI_MAX)) :
    True := by
  trivial
