import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: friis_link_budget
-- Source file:   <private>/friis_link_budget.eml
-- Verified fns:  received_power_linear, free_space_path_loss_db, link_margin_db

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def D_MIN : Real := (1.0 : Real)
noncomputable def D_MAX : Real := (100000000.0 : Real)
noncomputable def F_MHZ_MIN : Real := (0.1 : Real)
noncomputable def F_MHZ_MAX : Real := (1000000.0 : Real)
noncomputable def P_DBM_MIN : Real := (-(200.0 : Real))
noncomputable def P_DBM_MAX : Real := (100.0 : Real)
noncomputable def G_DB_MAX : Real := (80.0 : Real)
noncomputable def C_LIGHT : Real := (299792458.0 : Real)
noncomputable def FOUR_PI : Real := (12.566370614359172 : Real)
noncomputable def LN10_INV : Real := (0.4342944819032518 : Real)

-- ── received_power_linear ──

noncomputable def received_power_linear (p_tx : Real) (g_tx : Real) (g_rx : Real) (frequency_hz : Real) (distance_m : Real) : Real :=
  ((((p_tx * g_tx) * g_rx) * ((C_LIGHT / frequency_hz) / (FOUR_PI * distance_m))) * ((C_LIGHT / frequency_hz) / (FOUR_PI * distance_m)))

theorem received_power_decreases_with_distance (p_tx : Real) (g_tx : Real) (g_rx : Real) (frequency_hz : Real) (distance_m : Real)
    (h1 : (p_tx >= (0.0 : Real)))
    (h2 : (p_tx <= (1000000000.0 : Real)))
    (h3 : (g_tx >= (0.0 : Real)))
    (h4 : (g_tx <= (100000000.0 : Real)))
    (h5 : (g_rx >= (0.0 : Real)))
    (h6 : (g_rx <= (100000000.0 : Real)))
    (h7 : (frequency_hz >= (1.0 : Real)))
    (h8 : (frequency_hz <= (1000000000000.0 : Real)))
    (h9 : (distance_m >= D_MIN))
    (h10 : (distance_m <= D_MAX)) :
    ((received_power_linear p_tx g_tx g_rx frequency_hz distance_m) >= (0.0 : Real)) := by
  unfold received_power_linear
  sorry  -- TODO: prove against MachLib foundations

-- ── free_space_path_loss_db ──

noncomputable def free_space_path_loss_db (distance_km : Real) (frequency_mhz : Real) : Real :=
  ((((20.0 : Real) * LN10_INV) * ((Real.log distance_km) + (Real.log frequency_mhz))) + (32.45 : Real))

theorem fspl_db_increases_with_log_distance (distance_km : Real) (frequency_mhz : Real)
    (h1 : (distance_km >= (D_MIN / (1000.0 : Real))))
    (h2 : (distance_km <= (D_MAX / (1000.0 : Real))))
    (h3 : (frequency_mhz >= F_MHZ_MIN))
    (h4 : (frequency_mhz <= F_MHZ_MAX)) :
    ((free_space_path_loss_db distance_km frequency_mhz) >= (0.0 : Real)) := by
  unfold free_space_path_loss_db
  sorry  -- TODO: prove against MachLib foundations

-- ── link_margin_db ──

noncomputable def link_margin_db (p_rx_dbm : Real) (sensitivity_dbm : Real) : Real :=
  (p_rx_dbm - sensitivity_dbm)

theorem link_margin_signed_by_received_minus_sensitivity (p_rx_dbm : Real) (sensitivity_dbm : Real)
    (h1 : (p_rx_dbm >= P_DBM_MIN))
    (h2 : (p_rx_dbm <= P_DBM_MAX))
    (h3 : (sensitivity_dbm >= P_DBM_MIN))
    (h4 : (sensitivity_dbm <= P_DBM_MAX)) :
    True := by
  trivial
