import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: gamma_correct
-- Source file:   <private>/gamma_correct.eml
-- Verified fns:  gamma_correct

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

axiom srgb_to_linear (x : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── gamma_correct ──

noncomputable def gamma_correct (x : Real) (gamma : Real) : Real :=
  (x ^ ((1.0 : Real) / gamma))

theorem gamma_correct_monotone_in_x (x : Real) (gamma : Real)
    (h1 : (x >= (0.0 : Real)))
    (h2 : (x <= (1.0 : Real)))
    (h3 : (gamma > (0.0 : Real))) :
    ((gamma_correct x gamma) >= (0.0 : Real)) := by
  unfold gamma_correct
  sorry  -- TODO: prove against MachLib foundations
