-- Generated by the EML-lang Lean backend
-- Source module: gamma_greek
-- Source file:   <private>/gamma.eml
-- Verified fns:  bs_gamma

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def HALF : Real := (0.5 : Real)
noncomputable def SQRT_2_PI_INV : Real := (0.3989422804014327 : Real)
noncomputable def TINY_T : Real := (0.000274 : Real)

axiom norm_pdf (x : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom d1 (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── bs_gamma ──

noncomputable def bs_gamma (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real :=
  ((SQRT_2_PI_INV * (Real.exp (((-HALF) * (d1 spot strike rate vol time_to_expiry)) * (d1 spot strike rate vol time_to_expiry)))) / ((spot * vol) * (Real.sqrt time_to_expiry)))

theorem bs_gamma_non_negative (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real)
    (h_spot : (spot > (0 : Real)))
    (h_strike : (strike > (0 : Real)))
    (h_vol : (vol > (0 : Real)))
    (h_time_to_expiry : (time_to_expiry > TINY_T)) :
    ((bs_gamma spot strike rate vol time_to_expiry) >= (0 : Real)) := by
  unfold bs_gamma
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
