-- Generated by the EML-lang Lean backend
-- Source module: gelu
-- Source file:   <private>/gelu.eml
-- Verified fns:  gelu_tanh, quick_gelu

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def GELU_X_MAX : Real := (30.0 : Real)
noncomputable def SQRT_2_OVER_PI : Real := (0.7978845608028654 : Real)
noncomputable def GELU_CUBIC : Real := (0.044715 : Real)
noncomputable def HALF : Real := (0.5 : Real)

-- ── gelu_tanh ──

noncomputable def gelu_tanh (x : Real) : Real :=
  ((HALF * x) * ((1 : Real) + (Real.tanh (SQRT_2_OVER_PI * (x + (((GELU_CUBIC * x) * x) * x))))))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem gelu_tanh_monotone_in_x (x : Real)
    (h1 : ((abs x) < GELU_X_MAX)) :
    True := by
  trivial

-- ── quick_gelu ──

noncomputable def quick_gelu (x : Real) : Real :=
  (x / ((1 : Real) + (Real.exp ((-1.702 : Real) * x))))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem quick_gelu_monotone_in_x (x : Real)
    (h1 : ((abs x) < GELU_X_MAX)) :
    True := by
  trivial
