import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: gibbs
-- Source file:   <private>/gibbs.eml
-- Verified fns:  delta_g, equilibrium_constant

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def R_GAS : Real := (8.314462618 : Real)
noncomputable def T_MIN : Real := (200.0 : Real)
noncomputable def T_MAX : Real := (2000.0 : Real)
noncomputable def DG_MAX : Real := (1000000.0 : Real)

axiom delta_g_from_k (equilibrium_k : Real) (temperature : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── delta_g ──

noncomputable def delta_g (delta_h : Real) (delta_s : Real) (temperature : Real) : Real :=
  (delta_h - (temperature * delta_s))

theorem gibbs_linear_in_temperature (delta_h : Real) (delta_s : Real) (temperature : Real)
    (h1 : (temperature >= T_MIN))
    (h2 : (temperature <= T_MAX)) :
    True := by
  trivial

-- ── equilibrium_constant ──

noncomputable def equilibrium_constant (delta_g_value : Real) (temperature : Real) : Real :=
  (Real.exp ((-delta_g_value) / (R_GAS * temperature)))

theorem equilibrium_constant_positive (delta_g_value : Real) (temperature : Real)
    (h1 : (temperature >= T_MIN))
    (h2 : (temperature <= T_MAX))
    (h3 : (delta_g_value >= (-DG_MAX)))
    (h4 : (delta_g_value <= DG_MAX)) :
    ((equilibrium_constant delta_g_value temperature) > (0.0 : Real)) := by
  unfold equilibrium_constant
  sorry  -- TODO: prove against MachLib foundations
