import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: gnss_pseudorange
-- Source file:   <private>/gnss_pseudorange.eml
-- Verified fns:  geometric_range, pseudorange_residual, line_of_sight_x

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def POS_MAX : Real := (50000000.0 : Real)
noncomputable def C_LIGHT : Real := (299792458.0 : Real)
noncomputable def CLOCK_MAX : Real := (0.1 : Real)
noncomputable def RANGE_MIN : Real := (1000000.0 : Real)

-- ── geometric_range ──

noncomputable def geometric_range (sat_x : Real) (sat_y : Real) (sat_z : Real) (user_x : Real) (user_y : Real) (user_z : Real) : Real :=
  (Real.sqrt ((((sat_x - user_x) * (sat_x - user_x)) + ((sat_y - user_y) * (sat_y - user_y))) + ((sat_z - user_z) * (sat_z - user_z))))

theorem range_nonneg (sat_x : Real) (sat_y : Real) (sat_z : Real) (user_x : Real) (user_y : Real) (user_z : Real)
    (h1 : ((abs sat_x) <= POS_MAX))
    (h2 : ((abs sat_y) <= POS_MAX))
    (h3 : ((abs sat_z) <= POS_MAX))
    (h4 : ((abs user_x) <= POS_MAX))
    (h5 : ((abs user_y) <= POS_MAX))
    (h6 : ((abs user_z) <= POS_MAX)) :
    ((geometric_range sat_x sat_y sat_z user_x user_y user_z) >= (0.0 : Real)) := by
  unfold geometric_range
  sorry  -- TODO: prove against MachLib foundations

-- ── pseudorange_residual ──

noncomputable def pseudorange_residual (pseudorange_obs : Real) (geometric_range : Real) (clock_bias : Real) : Real :=
  (pseudorange_obs - (geometric_range + (C_LIGHT * clock_bias)))

theorem pseudorange_residual_zero_at_truth (pseudorange_obs : Real) (geometric_range : Real) (clock_bias : Real)
    (h1 : (pseudorange_obs >= (0.0 : Real)))
    (h2 : (pseudorange_obs <= POS_MAX))
    (h3 : (geometric_range >= RANGE_MIN))
    (h4 : (geometric_range <= POS_MAX))
    (h5 : ((abs clock_bias) <= CLOCK_MAX)) :
    True := by
  trivial

-- ── line_of_sight_x ──

noncomputable def line_of_sight_x (sat_x : Real) (user_x : Real) (geometric_range : Real) : Real :=
  (min (max ((user_x - sat_x) / geometric_range) (-1.0 : Real)) (1.0 : Real))

theorem los_component_in_unit_interval (sat_x : Real) (user_x : Real) (geometric_range : Real)
    (h1 : ((abs sat_x) <= POS_MAX))
    (h2 : ((abs user_x) <= POS_MAX))
    (h3 : (geometric_range >= RANGE_MIN))
    (h4 : (geometric_range <= POS_MAX)) :
    ((line_of_sight_x sat_x user_x geometric_range) >= (-(1.0 : Real))) := by
  unfold line_of_sight_x
  sorry  -- TODO: prove against MachLib foundations
