-- Generated by the EML-lang Lean backend
-- Source module: heston
-- Source file:   <private>/heston.eml
-- Verified fns:  heston_log_spot_step

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def HALF : Real := (0.5 : Real)
noncomputable def VAR_FLOOR : Real := (0 : Real)
noncomputable def VAR_CEILING : Real := (100.0 : Real)

axiom heston_variance_step (variance : Real) (kappa : Real) (theta : Real) (xi : Real) (sqrt_dt : Real) (z2 : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── heston_log_spot_step ──

noncomputable def heston_log_spot_step (log_spot : Real) (variance : Real) (drift : Real) (sqrt_dt : Real) (z1 : Real) : Real :=
  ((log_spot + ((drift - (HALF * (min (max variance VAR_FLOOR) VAR_CEILING))) * (sqrt_dt * sqrt_dt))) + (((Real.sqrt (min (max variance VAR_FLOOR) VAR_CEILING)) * sqrt_dt) * z1))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem heston_log_spot_step_stable (log_spot : Real) (variance : Real) (drift : Real) (sqrt_dt : Real) (z1 : Real)
    (h1 : (variance >= (0 : Real)))
    (h2 : (sqrt_dt > (0 : Real)))
    (h_clamp1 : VAR_FLOOR ≤ VAR_CEILING) :
    True := by
  trivial
