-- Generated by the EML-lang Lean backend
-- Source module: hill
-- Source file:   <private>/hill.eml
-- Verified fns:  hill_velocity

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def S_MAX : Real := (1000.0 : Real)
noncomputable def N_MAX : Real := (8.0 : Real)

axiom hill_logit (velocity_obs : Real) (vmax : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── hill_velocity ──

noncomputable def hill_velocity (vmax : Real) (substrate : Real) (half_saturation : Real) (hill_coefficient : Real) : Real :=
  ((vmax * (substrate ^ hill_coefficient)) / ((half_saturation ^ hill_coefficient) + (substrate ^ hill_coefficient)))

theorem hill_monotone_in_substrate (vmax : Real) (substrate : Real) (half_saturation : Real) (hill_coefficient : Real)
    (h1 : (vmax > (0 : Real)))
    (h2 : (substrate >= (0 : Real)))
    (h3 : (substrate <= S_MAX))
    (h4 : (half_saturation > (0 : Real)))
    (h5 : (half_saturation <= S_MAX))
    (h6 : (hill_coefficient > (0 : Real)))
    (h7 : (hill_coefficient <= N_MAX)) :
    (((hill_velocity vmax substrate half_saturation hill_coefficient) >= (0 : Real))) ∧ (((hill_velocity vmax substrate half_saturation hill_coefficient) <= vmax)) := by
  unfold hill_velocity
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
