import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: historical_var
-- Source file:   <private>/historical_var.eml
-- Verified fns:  parametric_var, expected_shortfall

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def SQRT_2_PI : Real := (2.5066282746310002 : Real)
noncomputable def ONE_OVER_SQRT_2PI : Real := (0.3989422804014327 : Real)
noncomputable def HALF : Real := (0.5 : Real)
noncomputable def ONE : Real := (1.0 : Real)
noncomputable def PV_MAX : Real := (1000000000000.0 : Real)
noncomputable def Z_MAX : Real := (6.0 : Real)
noncomputable def ALPHA_MIN : Real := (0.5 : Real)
noncomputable def ALPHA_MAX : Real := (0.999999 : Real)

axiom standard_normal_pdf (z : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── parametric_var ──

noncomputable def parametric_var (pnl_mean : Real) (pnl_stddev : Real) (portfolio_value : Real) (z_alpha : Real) : Real :=
  ((-(pnl_mean - (z_alpha * pnl_stddev))) * portfolio_value)

theorem parametric_var_nonneg_when_z_positive (pnl_mean : Real) (pnl_stddev : Real) (portfolio_value : Real) (z_alpha : Real)
    (h1 : (pnl_stddev >= (0.0 : Real)))
    (h2 : (portfolio_value >= (0.0 : Real)))
    (h3 : (portfolio_value <= PV_MAX))
    (h4 : (z_alpha >= (0.0 : Real)))
    (h5 : (z_alpha <= Z_MAX)) :
    True := by
  trivial

-- ── expected_shortfall ──

noncomputable def expected_shortfall (pnl_mean : Real) (pnl_stddev : Real) (portfolio_value : Real) (z_alpha : Real) (alpha : Real) : Real :=
  ((-(pnl_mean - (((ONE_OVER_SQRT_2PI * (Real.exp ((-(z_alpha * z_alpha)) * HALF))) / (ONE - alpha)) * pnl_stddev))) * portfolio_value)

theorem expected_shortfall_at_least_var (pnl_mean : Real) (pnl_stddev : Real) (portfolio_value : Real) (z_alpha : Real) (alpha : Real)
    (h1 : (pnl_stddev >= (0.0 : Real)))
    (h2 : (portfolio_value >= (0.0 : Real)))
    (h3 : (portfolio_value <= PV_MAX))
    (h4 : (z_alpha >= (0.0 : Real)))
    (h5 : (z_alpha <= Z_MAX))
    (h6 : (alpha >= ALPHA_MIN))
    (h7 : (alpha <= ALPHA_MAX)) :
    True := by
  trivial
