-- Generated by the EML-lang Lean backend
-- Source module: inertia_emulation
-- Source file:   <private>/inertia_emulation.eml
-- Verified fns:  synthetic_power_command, rocof_estimate, headroom_limited_response

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def K_INERTIA_MIN : Real := (0 : Real)
noncomputable def K_INERTIA_MAX : Real := (50.0 : Real)
noncomputable def K_DROOP_MIN : Real := (0 : Real)
noncomputable def K_DROOP_MAX : Real := (100.0 : Real)
noncomputable def F_NOM : Real := (50.0 : Real)
noncomputable def F_MIN : Real := (45.0 : Real)
noncomputable def F_MAX : Real := (55.0 : Real)
noncomputable def DF_DT_MAX : Real := (5.0 : Real)
noncomputable def POWER_MAX : Real := (1000.0 : Real)

-- ── synthetic_power_command ──

noncomputable def synthetic_power_command (df_dt : Real) (frequency_meas : Real) (frequency_nominal : Real) (k_inertia : Real) (k_droop : Real) : Real :=
  (((-k_inertia) * df_dt) - (k_droop * (frequency_meas - frequency_nominal)))

theorem synthetic_inertia_response_signed (df_dt : Real) (frequency_meas : Real) (frequency_nominal : Real) (k_inertia : Real) (k_droop : Real)
    (h1 : ((abs df_dt) <= DF_DT_MAX))
    (h2 : (frequency_meas >= F_MIN))
    (h3 : (frequency_meas <= F_MAX))
    (h4 : (frequency_nominal >= F_MIN))
    (h5 : (frequency_nominal <= F_MAX))
    (h6 : (k_inertia >= K_INERTIA_MIN))
    (h7 : (k_inertia <= K_INERTIA_MAX))
    (h8 : (k_droop >= K_DROOP_MIN))
    (h9 : (k_droop <= K_DROOP_MAX)) :
    True := by
  trivial

-- ── rocof_estimate ──

noncomputable def rocof_estimate (frequency_now : Real) (frequency_prev : Real) (dt : Real) : Real :=
  ((frequency_now - frequency_prev) / dt)

theorem rocof_zero_at_constant_frequency (frequency_now : Real) (frequency_prev : Real) (dt : Real)
    (h1 : (frequency_now >= F_MIN))
    (h2 : (frequency_now <= F_MAX))
    (h3 : (frequency_prev >= F_MIN))
    (h4 : (frequency_prev <= F_MAX))
    (h5 : (dt > (0 : Real)))
    (h6 : (dt <= (1 : Real))) :
    True := by
  trivial

-- ── headroom_limited_response ──

noncomputable def headroom_limited_response (desired_power : Real) (headroom_up : Real) (headroom_down : Real) : Real :=
  (min (max desired_power (-headroom_down)) headroom_up)

theorem headroom_limited_within_inverter_capability (desired_power : Real) (headroom_up : Real) (headroom_down : Real)
    (h1 : ((abs desired_power) <= POWER_MAX))
    (h2 : (headroom_up >= (0 : Real)))
    (h3 : (headroom_up <= POWER_MAX))
    (h4 : (headroom_down >= (0 : Real)))
    (h5 : (headroom_down <= POWER_MAX)) :
    True := by
  trivial
