-- Generated by the EML-lang Lean backend
-- Source module: infusion_pump
-- Source file:   <private>/infusion_pump.eml
-- Verified fns:  motor_command

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def Kp : Real := (0.4 : Real)
noncomputable def Ki : Real := (0.05 : Real)
noncomputable def dt : Real := (0.1 : Real)
noncomputable def RATE_MIN : Real := (0.1 : Real)
noncomputable def RATE_MAX : Real := (999.0 : Real)
noncomputable def MOTOR_MIN : Real := (-(100.0 : Real))
noncomputable def MOTOR_MAX : Real := (500.0 : Real)

-- ── motor_command ──

noncomputable def motor_command (prescribed_rate : Real) (measured_rate : Real) (rate_integral : Real) : Real :=
  (min (max ((Kp * (prescribed_rate - measured_rate)) + (Ki * rate_integral)) MOTOR_MIN) MOTOR_MAX)

theorem infusion_motor_command_safe (prescribed_rate : Real) (measured_rate : Real) (rate_integral : Real)
    (h_prescribed_rate : ((RATE_MIN <= prescribed_rate) ∧ (prescribed_rate <= RATE_MAX)))
    (h_measured_rate : (-RATE_MAX < measured_rate ∧ measured_rate < RATE_MAX))
    (h_rate_integral : (-(100.0 : Real) < rate_integral ∧ rate_integral < (100.0 : Real)))
    (h_clamp1 : MOTOR_MIN ≤ MOTOR_MAX) :
    ((MOTOR_MIN <= (motor_command prescribed_rate measured_rate rate_integral))) ∧ (((motor_command prescribed_rate measured_rate rate_integral) <= MOTOR_MAX)) := by
  unfold motor_command
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
