-- Generated by the EML-lang Lean backend
-- Source module: infusion_pid
-- Source file:   <private>/infusion_pid.eml
-- Verified fns:  infusion_pid_step, infusion_integral_step, bis_error

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def RATE_MAX : Real := (1200.0 : Real)
noncomputable def I_LIMIT_MAX : Real := (100.0 : Real)
noncomputable def KP_MAX : Real := (1000.0 : Real)
noncomputable def KI_MAX : Real := (1000.0 : Real)
noncomputable def KD_MAX : Real := (1000.0 : Real)
noncomputable def ERR_MAX : Real := (1000.0 : Real)

-- ── infusion_pid_step ──

noncomputable def infusion_pid_step (error : Real) (integral : Real) (derivative : Real) (kp : Real) (ki : Real) (kd : Real) (integral_limit : Real) (rate_max : Real) : Real :=
  (min (max (((kp * error) + (ki * (min (max integral (-integral_limit)) integral_limit))) + (kd * derivative)) (0 : Real)) rate_max)

theorem infusion_pid_within_pump_limit (error : Real) (integral : Real) (derivative : Real) (kp : Real) (ki : Real) (kd : Real) (integral_limit : Real) (rate_max : Real)
    (h1 : ((abs error) <= ERR_MAX))
    (h2 : ((abs integral) <= I_LIMIT_MAX))
    (h3 : ((abs derivative) <= ERR_MAX))
    (h4 : (kp >= (0 : Real)))
    (h5 : (kp <= KP_MAX))
    (h6 : (ki >= (0 : Real)))
    (h7 : (ki <= KI_MAX))
    (h8 : (kd >= (0 : Real)))
    (h9 : (kd <= KD_MAX))
    (h10 : (integral_limit >= (0 : Real)))
    (h11 : (integral_limit <= I_LIMIT_MAX))
    (h12 : (rate_max >= (0 : Real)))
    (h13 : (rate_max <= RATE_MAX)) :
    ((infusion_pid_step error integral derivative kp ki kd integral_limit rate_max) >= (0 : Real)) := by
  unfold infusion_pid_step
  sorry  -- TODO: prove against MachLib foundations

-- ── infusion_integral_step ──

noncomputable def infusion_integral_step (integral_prev : Real) (error : Real) (error_prev : Real) (dt : Real) (saturation_active : Real) : Real :=
  (integral_prev + (((1 : Real) - saturation_active) * (((0.5 : Real) * (error + error_prev)) * dt)))

theorem infusion_integral_held_under_saturation (integral_prev : Real) (error : Real) (error_prev : Real) (dt : Real) (saturation_active : Real)
    (h1 : ((abs integral_prev) <= I_LIMIT_MAX))
    (h2 : ((abs error) <= ERR_MAX))
    (h3 : ((abs error_prev) <= ERR_MAX))
    (h4 : (dt >= (0 : Real)))
    (h5 : (dt <= (1 : Real)))
    (h6 : (saturation_active >= (0 : Real)))
    (h7 : (saturation_active <= (1 : Real))) :
    True := by
  trivial

-- ── bis_error ──

noncomputable def bis_error (target_bis : Real) (measured_bis : Real) : Real :=
  (min (max (target_bis - measured_bis) (-50.0 : Real)) (50.0 : Real))

theorem bis_error_bounded (target_bis : Real) (measured_bis : Real)
    (h1 : (target_bis >= (20.0 : Real)))
    (h2 : (target_bis <= (80.0 : Real)))
    (h3 : (measured_bis >= (0 : Real)))
    (h4 : (measured_bis <= (100.0 : Real))) :
    True := by
  trivial
