-- Generated by the EML-lang Lean backend
-- Source module: ins
-- Source file:   <private>/ins.eml
-- Verified fns:  attitude_step

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def dt : Real := (0.001 : Real)
noncomputable def ATT_LIMIT : Real := (6.28319 : Real)

-- ── attitude_step ──

noncomputable def attitude_step (attitude : Real) (rate_gyro : Real) : Real :=
  ((attitude + (rate_gyro * dt)) * ((1 : Real) - (((((0.5 : Real) * rate_gyro) * dt) * rate_gyro) * dt)))

theorem ins_attitude_update_bounded (attitude : Real) (rate_gyro : Real)
    (h1 : ((abs attitude) < ATT_LIMIT))
    (h2 : ((abs rate_gyro) < (100.0 : Real))) :
    ((abs (attitude_step attitude rate_gyro)) < (ATT_LIMIT * (2.0 : Real))) := by
  unfold attitude_step
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
