-- Generated by the EML-lang Lean backend
-- Source module: ins_alignment
-- Source file:   <private>/ins_alignment.eml
-- Verified fns:  coarse_pitch, coarse_roll, coarse_heading, gravity_residual

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def G_REF : Real := (9.80665 : Real)
noncomputable def A_MAX : Real := ((16.0 : Real) * G_REF)
noncomputable def OMEGA_MAX : Real := ((7.292e-05 : Real) * (5.0 : Real))
noncomputable def PITCH_MAX : Real := (1.5708 : Real)

-- ── coarse_pitch ──

noncomputable def coarse_pitch (accel_x : Real) (accel_y : Real) (accel_z : Real) : Real :=
  (atan2 (-accel_x) (Real.sqrt ((accel_y * accel_y) + (accel_z * accel_z))))

theorem pitch_initial_zero_at_level (accel_x : Real) (accel_y : Real) (accel_z : Real)
    (h1 : ((abs accel_x) <= A_MAX))
    (h2 : ((abs accel_y) <= A_MAX))
    (h3 : ((abs accel_z) <= A_MAX)) :
    True := by
  trivial

-- ── coarse_roll ──

noncomputable def coarse_roll (accel_y : Real) (accel_z : Real) : Real :=
  (atan2 accel_y accel_z)

theorem roll_initial_zero_at_level (accel_y : Real) (accel_z : Real)
    (h1 : ((abs accel_y) <= A_MAX))
    (h2 : ((abs accel_z) <= A_MAX)) :
    True := by
  trivial

-- ── coarse_heading ──

noncomputable def coarse_heading (gyro_y_horizontal : Real) (gyro_x_horizontal : Real) : Real :=
  (atan2 (-gyro_y_horizontal) gyro_x_horizontal)

theorem heading_initial_zero_due_north (gyro_y_horizontal : Real) (gyro_x_horizontal : Real)
    (h1 : ((abs gyro_y_horizontal) <= OMEGA_MAX))
    (h2 : ((abs gyro_x_horizontal) <= OMEGA_MAX)) :
    True := by
  trivial

-- ── gravity_residual ──

noncomputable def gravity_residual (accel_x : Real) (accel_y : Real) (accel_z : Real) : Real :=
  ((Real.sqrt (((accel_x * accel_x) + (accel_y * accel_y)) + (accel_z * accel_z))) - G_REF)

theorem gravity_residual_zero_at_level_stationary (accel_x : Real) (accel_y : Real) (accel_z : Real)
    (h1 : ((abs accel_x) <= A_MAX))
    (h2 : ((abs accel_y) <= A_MAX))
    (h3 : ((abs accel_z) <= A_MAX)) :
    True := by
  trivial
