-- Generated by the EML-lang Lean backend
-- Source module: langmuir
-- Source file:   <private>/langmuir.eml
-- Verified fns:  coverage

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def K_MAX : Real := (1000000.0 : Real)
noncomputable def P_MAX : Real := (100000000.0 : Real)

axiom adsorbed_amount (monolayer_capacity : Real) (langmuir_constant : Real) (pressure : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom linearised_pressure_over_n (pressure : Real) (adsorbed_amount : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── coverage ──

noncomputable def coverage (langmuir_constant : Real) (pressure : Real) : Real :=
  ((langmuir_constant * pressure) / ((1 : Real) + (langmuir_constant * pressure)))

theorem langmuir_saturating (langmuir_constant : Real) (pressure : Real)
    (h1 : (langmuir_constant >= (0 : Real)))
    (h2 : (langmuir_constant <= K_MAX))
    (h3 : (pressure >= (0 : Real)))
    (h4 : (pressure <= P_MAX)) :
    (((coverage langmuir_constant pressure) >= (0 : Real))) ∧ (((coverage langmuir_constant pressure) <= (1 : Real))) := by
  unfold coverage
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
