import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: load_flow
-- Source file:   <private>/load_flow.eml
-- Verified fns:  active_injection, reactive_injection, dc_load_flow

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def V_MIN : Real := (0.5 : Real)
noncomputable def V_MAX : Real := (1.5 : Real)
noncomputable def Y_MAX : Real := (1000.0 : Real)
noncomputable def ANGLE_MAX : Real := (6.2832 : Real)

-- ── active_injection ──

noncomputable def active_injection (v_local : Real) (v_remote : Real) (g : Real) (b : Real) (angle_diff : Real) : Real :=
  ((v_local * v_remote) * ((g * (Real.cos angle_diff)) + (b * (Real.sin angle_diff))))

theorem active_injection_zero_at_zero_voltage (v_local : Real) (v_remote : Real) (g : Real) (b : Real) (angle_diff : Real)
    (h1 : (v_local >= V_MIN))
    (h2 : (v_local <= V_MAX))
    (h3 : (v_remote >= V_MIN))
    (h4 : (v_remote <= V_MAX))
    (h5 : ((abs g) <= Y_MAX))
    (h6 : ((abs b) <= Y_MAX))
    (h7 : ((abs angle_diff) <= ANGLE_MAX)) :
    True := by
  trivial

-- ── reactive_injection ──

noncomputable def reactive_injection (v_local : Real) (v_remote : Real) (g : Real) (b : Real) (angle_diff : Real) : Real :=
  ((v_local * v_remote) * ((g * (Real.sin angle_diff)) - (b * (Real.cos angle_diff))))

theorem reactive_injection_zero_at_zero_voltage (v_local : Real) (v_remote : Real) (g : Real) (b : Real) (angle_diff : Real)
    (h1 : (v_local >= V_MIN))
    (h2 : (v_local <= V_MAX))
    (h3 : (v_remote >= V_MIN))
    (h4 : (v_remote <= V_MAX))
    (h5 : ((abs g) <= Y_MAX))
    (h6 : ((abs b) <= Y_MAX))
    (h7 : ((abs angle_diff) <= ANGLE_MAX)) :
    True := by
  trivial

-- ── dc_load_flow ──

noncomputable def dc_load_flow (b : Real) (angle_diff : Real) : Real :=
  (b * angle_diff)

theorem dc_load_flow_linear_in_angle_diff (b : Real) (angle_diff : Real)
    (h1 : ((abs b) <= Y_MAX))
    (h2 : ((abs angle_diff) <= (1.0 : Real))) :
    True := by
  trivial
