-- Generated by the EML-lang Lean backend
-- Source module: mantis_shrimp_16ch
-- Source file:   <private>/mantis_shrimp_16ch.eml
-- Verified fns:  response_at_peak, pol_response_at_axis, false_color_r, false_color_g, false_color_b

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ONE : Real := (1 : Real)
noncomputable def HALF : Real := (0.5 : Real)
noncomputable def SIGMA_UM : Real := (0.02 : Real)
noncomputable def PEAK_01_UM : Real := (0.32 : Real)
noncomputable def PEAK_02_UM : Real := (0.35 : Real)
noncomputable def PEAK_03_UM : Real := (0.41 : Real)
noncomputable def PEAK_04_UM : Real := (0.44 : Real)
noncomputable def PEAK_05_UM : Real := (0.47 : Real)
noncomputable def PEAK_06_UM : Real := (0.5 : Real)
noncomputable def PEAK_07_UM : Real := (0.53 : Real)
noncomputable def PEAK_08_UM : Real := (0.56 : Real)
noncomputable def PEAK_09_UM : Real := (0.59 : Real)
noncomputable def PEAK_10_UM : Real := (0.62 : Real)
noncomputable def PEAK_11_UM : Real := (0.65 : Real)
noncomputable def PEAK_12_UM : Real := (0.7 : Real)
noncomputable def POL_AXIS_01 : Real := (0 : Real)
noncomputable def POL_AXIS_02 : Real := (0.785398 : Real)
noncomputable def POL_AXIS_03 : Real := (1.570796 : Real)
noncomputable def POL_AXIS_04 : Real := (2.356194 : Real)

-- ── response_at_peak ──

noncomputable def response_at_peak (lambda_um : Real) (peak_um : Real) : Real :=
  (Real.exp (((-HALF) * ((lambda_um - peak_um) / SIGMA_UM)) * ((lambda_um - peak_um) / SIGMA_UM)))

theorem mantis_response_at_peak_in_unit_band (lambda_um : Real) (peak_um : Real) :
    ((response_at_peak lambda_um peak_um) >= ZERO) := by
  unfold response_at_peak
  sorry  -- TODO: prove against MachLib foundations

-- ── pol_response_at_axis ──

noncomputable def pol_response_at_axis (angle_rad : Real) (axis_rad : Real) : Real :=
  ((Real.cos (angle_rad - axis_rad)) * (Real.cos (angle_rad - axis_rad)))

theorem mantis_pol_response_at_axis_in_unit_band (angle_rad : Real) (axis_rad : Real) :
    ((pol_response_at_axis angle_rad axis_rad) >= ZERO) := by
  unfold pol_response_at_axis
  sorry  -- TODO: prove against MachLib foundations

-- ── false_color_r ──

noncomputable def false_color_r (c01 : Real) (c02 : Real) (c03 : Real) (c04 : Real) (c05 : Real) (c06 : Real) (c07 : Real) (c08 : Real) (c09 : Real) (c10 : Real) (c11 : Real) (c12 : Real) : Real :=
  (min (max ((((c09 * (0.2 : Real)) + (c10 * (0.3 : Real))) + (c11 * (0.3 : Real))) + (c12 * (0.2 : Real))) ZERO) ONE)

theorem mantis_false_color_r_in_unit_band (c01 : Real) (c02 : Real) (c03 : Real) (c04 : Real) (c05 : Real) (c06 : Real) (c07 : Real) (c08 : Real) (c09 : Real) (c10 : Real) (c11 : Real) (c12 : Real) :
    ((false_color_r c01 c02 c03 c04 c05 c06 c07 c08 c09 c10 c11 c12) >= ZERO) := by
  unfold false_color_r
  sorry  -- TODO: prove against MachLib foundations

-- ── false_color_g ──

noncomputable def false_color_g (c01 : Real) (c02 : Real) (c03 : Real) (c04 : Real) (c05 : Real) (c06 : Real) (c07 : Real) (c08 : Real) (c09 : Real) (c10 : Real) (c11 : Real) (c12 : Real) : Real :=
  (min (max ((((c05 * (0.25 : Real)) + (c06 * (0.25 : Real))) + (c07 * (0.25 : Real))) + (c08 * (0.25 : Real))) ZERO) ONE)

theorem mantis_false_color_g_in_unit_band (c01 : Real) (c02 : Real) (c03 : Real) (c04 : Real) (c05 : Real) (c06 : Real) (c07 : Real) (c08 : Real) (c09 : Real) (c10 : Real) (c11 : Real) (c12 : Real) :
    ((false_color_g c01 c02 c03 c04 c05 c06 c07 c08 c09 c10 c11 c12) >= ZERO) := by
  unfold false_color_g
  sorry  -- TODO: prove against MachLib foundations

-- ── false_color_b ──

noncomputable def false_color_b (c01 : Real) (c02 : Real) (c03 : Real) (c04 : Real) (c05 : Real) (c06 : Real) (c07 : Real) (c08 : Real) (c09 : Real) (c10 : Real) (c11 : Real) (c12 : Real) : Real :=
  (min (max ((((c01 * (0.2 : Real)) + (c02 * (0.2 : Real))) + (c03 * (0.3 : Real))) + (c04 * (0.3 : Real))) ZERO) ONE)

theorem mantis_false_color_b_in_unit_band (c01 : Real) (c02 : Real) (c03 : Real) (c04 : Real) (c05 : Real) (c06 : Real) (c07 : Real) (c08 : Real) (c09 : Real) (c10 : Real) (c11 : Real) (c12 : Real) :
    ((false_color_b c01 c02 c03 c04 c05 c06 c07 c08 c09 c10 c11 c12) >= ZERO) := by
  unfold false_color_b
  sorry  -- TODO: prove against MachLib foundations
