-- Generated by the EML-lang Lean backend
-- Source module: mark_houwink
-- Source file:   <private>/mark_houwink.eml
-- Verified fns:  intrinsic_viscosity

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def M_MAX : Real := (1000000000.0 : Real)
noncomputable def K_MAX : Real := (1000.0 : Real)
noncomputable def A_MAX : Real := (1 : Real)

axiom molecular_weight_from_viscosity (measured_viscosity : Real) (k_param : Real) (a_exponent : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── intrinsic_viscosity ──

noncomputable def intrinsic_viscosity (k_param : Real) (a_exponent : Real) (molecular_weight : Real) : Real :=
  (k_param * (molecular_weight ^ a_exponent))

theorem mark_houwink_monotone_in_m (k_param : Real) (a_exponent : Real) (molecular_weight : Real)
    (h1 : (k_param >= (0 : Real)))
    (h2 : (k_param <= K_MAX))
    (h3 : (a_exponent >= (0 : Real)))
    (h4 : (a_exponent <= A_MAX))
    (h5 : (molecular_weight > (0 : Real)))
    (h6 : (molecular_weight <= M_MAX)) :
    ((intrinsic_viscosity k_param a_exponent molecular_weight) >= (0 : Real)) := by
  unfold intrinsic_viscosity
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
