-- Generated by the EML-lang Lean backend
-- Source module: mat4
-- Source file:   <private>/mat4.eml
-- Verified fns:  identity_00, identity_11, identity_22, identity_33, from_translation_03, from_translation_13, from_translation_23, transform_point3_x, transform_point3_y, transform_point3_z, translate_then_transform_x_witness, from_scale_00, from_scale_11, from_scale_22, scale_then_transform_x_witness, from_rotation_z_00, from_rotation_z_01, from_rotation_z_10, from_rotation_z_11, rotation_z_preserves_z_witness, rotation_z_orthonormal_witness, from_rotation_x_11, from_rotation_x_12, from_rotation_x_21, from_rotation_x_22, rotation_x_preserves_x_witness, rotation_x_orthonormal_witness, from_rotation_y_00, from_rotation_y_02, from_rotation_y_20, from_rotation_y_22, rotation_y_preserves_y_witness, rotation_y_orthonormal_witness

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ONE : Real := (1 : Real)

-- ── identity_00 ──

noncomputable def identity_00  : Real :=
  ONE

theorem mat4_identity_diagonal_00_is_one  :
    ((identity_00 ) = ONE) := by
  unfold identity_00
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── identity_11 ──

noncomputable def identity_11  : Real :=
  ONE

theorem mat4_identity_diagonal_11_is_one  :
    ((identity_11 ) = ONE) := by
  unfold identity_11
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── identity_22 ──

noncomputable def identity_22  : Real :=
  ONE

theorem mat4_identity_diagonal_22_is_one  :
    ((identity_22 ) = ONE) := by
  unfold identity_22
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── identity_33 ──

noncomputable def identity_33  : Real :=
  ONE

theorem mat4_identity_diagonal_33_is_one  :
    ((identity_33 ) = ONE) := by
  unfold identity_33
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_translation_03 ──

noncomputable def from_translation_03 (tx : Real) : Real :=
  tx

theorem mat4_translation_components_x (tx : Real) :
    ((from_translation_03 tx) = tx) := by
  unfold from_translation_03
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_translation_13 ──

noncomputable def from_translation_13 (ty : Real) : Real :=
  ty

theorem mat4_translation_components_y (ty : Real) :
    ((from_translation_13 ty) = ty) := by
  unfold from_translation_13
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_translation_23 ──

noncomputable def from_translation_23 (tz : Real) : Real :=
  tz

theorem mat4_translation_components_z (tz : Real) :
    ((from_translation_23 tz) = tz) := by
  unfold from_translation_23
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── transform_point3_x ──

noncomputable def transform_point3_x (m00 : Real) (m01 : Real) (m02 : Real) (m03 : Real) (px : Real) (py : Real) (pz : Real) : Real :=
  ((((m00 * px) + (m01 * py)) + (m02 * pz)) + m03)

theorem mat4_transform_point3_components_x (m00 : Real) (m01 : Real) (m02 : Real) (m03 : Real) (px : Real) (py : Real) (pz : Real) :
    True := by
  trivial

-- ── transform_point3_y ──

noncomputable def transform_point3_y (m10 : Real) (m11 : Real) (m12 : Real) (m13 : Real) (px : Real) (py : Real) (pz : Real) : Real :=
  ((((m10 * px) + (m11 * py)) + (m12 * pz)) + m13)

theorem mat4_transform_point3_components_y (m10 : Real) (m11 : Real) (m12 : Real) (m13 : Real) (px : Real) (py : Real) (pz : Real) :
    True := by
  trivial

-- ── transform_point3_z ──

noncomputable def transform_point3_z (m20 : Real) (m21 : Real) (m22 : Real) (m23 : Real) (px : Real) (py : Real) (pz : Real) : Real :=
  ((((m20 * px) + (m21 * py)) + (m22 * pz)) + m23)

theorem mat4_transform_point3_components_z (m20 : Real) (m21 : Real) (m22 : Real) (m23 : Real) (px : Real) (py : Real) (pz : Real) :
    True := by
  trivial

-- ── translate_then_transform_x_witness ──

noncomputable def translate_then_transform_x_witness (tx : Real) (x : Real) : Real :=
  (((((ONE * x) + (ZERO * ZERO)) + (ZERO * ZERO)) + tx) - (x + tx))

theorem mat4_translate_then_transform_shifts_x (tx : Real) (x : Real) :
    ((translate_then_transform_x_witness tx x) = ZERO) := by
  unfold translate_then_transform_x_witness
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_scale_00 ──

noncomputable def from_scale_00 (sx : Real) : Real :=
  sx

theorem mat4_scale_diagonal_components_x (sx : Real) :
    ((from_scale_00 sx) = sx) := by
  unfold from_scale_00
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_scale_11 ──

noncomputable def from_scale_11 (sy : Real) : Real :=
  sy

theorem mat4_scale_diagonal_components_y (sy : Real) :
    ((from_scale_11 sy) = sy) := by
  unfold from_scale_11
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_scale_22 ──

noncomputable def from_scale_22 (sz : Real) : Real :=
  sz

theorem mat4_scale_diagonal_components_z (sz : Real) :
    ((from_scale_22 sz) = sz) := by
  unfold from_scale_22
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── scale_then_transform_x_witness ──

noncomputable def scale_then_transform_x_witness (sx : Real) (x : Real) : Real :=
  (((((sx * x) + (ZERO * ZERO)) + (ZERO * ZERO)) + ZERO) - (sx * x))

theorem mat4_scale_then_transform_x (sx : Real) (x : Real) :
    ((scale_then_transform_x_witness sx x) = ZERO) := by
  unfold scale_then_transform_x_witness
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_z_00 ──

noncomputable def from_rotation_z_00 (angle : Real) : Real :=
  (Real.cos angle)

theorem mat4_rotation_z_cell_00 (angle : Real) :
    ((from_rotation_z_00 angle) = (Real.cos angle)) := by
  unfold from_rotation_z_00
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_z_01 ──

noncomputable def from_rotation_z_01 (angle : Real) : Real :=
  (-(Real.sin angle))

theorem mat4_rotation_z_cell_01 (angle : Real) :
    ((from_rotation_z_01 angle) = (-(Real.sin angle))) := by
  unfold from_rotation_z_01
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_z_10 ──

noncomputable def from_rotation_z_10 (angle : Real) : Real :=
  (Real.sin angle)

theorem mat4_rotation_z_cell_10 (angle : Real) :
    ((from_rotation_z_10 angle) = (Real.sin angle)) := by
  unfold from_rotation_z_10
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_z_11 ──

noncomputable def from_rotation_z_11 (angle : Real) : Real :=
  (Real.cos angle)

theorem mat4_rotation_z_cell_11 (angle : Real) :
    ((from_rotation_z_11 angle) = (Real.cos angle)) := by
  unfold from_rotation_z_11
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── rotation_z_preserves_z_witness ──

noncomputable def rotation_z_preserves_z_witness (z : Real) : Real :=
  (((((ZERO * ZERO) + (ZERO * ZERO)) + (ONE * z)) + ZERO) - z)

theorem mat4_rotation_z_preserves_z (z : Real) :
    ((rotation_z_preserves_z_witness z) = ZERO) := by
  unfold rotation_z_preserves_z_witness
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── rotation_z_orthonormal_witness ──

noncomputable def rotation_z_orthonormal_witness (angle : Real) : Real :=
  ((((Real.cos angle) * (Real.cos angle)) + ((Real.sin angle) * (Real.sin angle))) - ONE)

theorem mat4_rotation_z_orthonormal_witness (angle : Real) :
    ((rotation_z_orthonormal_witness angle) = ZERO) := by
  unfold rotation_z_orthonormal_witness
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_x_11 ──

noncomputable def from_rotation_x_11 (angle : Real) : Real :=
  (Real.cos angle)

theorem mat4_rotation_x_cell_11 (angle : Real) :
    ((from_rotation_x_11 angle) = (Real.cos angle)) := by
  unfold from_rotation_x_11
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_x_12 ──

noncomputable def from_rotation_x_12 (angle : Real) : Real :=
  (-(Real.sin angle))

theorem mat4_rotation_x_cell_12 (angle : Real) :
    ((from_rotation_x_12 angle) = (-(Real.sin angle))) := by
  unfold from_rotation_x_12
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_x_21 ──

noncomputable def from_rotation_x_21 (angle : Real) : Real :=
  (Real.sin angle)

theorem mat4_rotation_x_cell_21 (angle : Real) :
    ((from_rotation_x_21 angle) = (Real.sin angle)) := by
  unfold from_rotation_x_21
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_x_22 ──

noncomputable def from_rotation_x_22 (angle : Real) : Real :=
  (Real.cos angle)

theorem mat4_rotation_x_cell_22 (angle : Real) :
    ((from_rotation_x_22 angle) = (Real.cos angle)) := by
  unfold from_rotation_x_22
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── rotation_x_preserves_x_witness ──

noncomputable def rotation_x_preserves_x_witness (x : Real) : Real :=
  (((((ONE * x) + (ZERO * ZERO)) + (ZERO * ZERO)) + ZERO) - x)

theorem mat4_rotation_x_preserves_x (x : Real) :
    ((rotation_x_preserves_x_witness x) = ZERO) := by
  unfold rotation_x_preserves_x_witness
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── rotation_x_orthonormal_witness ──

noncomputable def rotation_x_orthonormal_witness (angle : Real) : Real :=
  ((((Real.cos angle) * (Real.cos angle)) + ((Real.sin angle) * (Real.sin angle))) - ONE)

theorem mat4_rotation_x_orthonormal_witness (angle : Real) :
    ((rotation_x_orthonormal_witness angle) = ZERO) := by
  unfold rotation_x_orthonormal_witness
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_y_00 ──

noncomputable def from_rotation_y_00 (angle : Real) : Real :=
  (Real.cos angle)

theorem mat4_rotation_y_cell_00 (angle : Real) :
    ((from_rotation_y_00 angle) = (Real.cos angle)) := by
  unfold from_rotation_y_00
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_y_02 ──

noncomputable def from_rotation_y_02 (angle : Real) : Real :=
  (Real.sin angle)

theorem mat4_rotation_y_cell_02 (angle : Real) :
    ((from_rotation_y_02 angle) = (Real.sin angle)) := by
  unfold from_rotation_y_02
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_y_20 ──

noncomputable def from_rotation_y_20 (angle : Real) : Real :=
  (-(Real.sin angle))

theorem mat4_rotation_y_cell_20 (angle : Real) :
    ((from_rotation_y_20 angle) = (-(Real.sin angle))) := by
  unfold from_rotation_y_20
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_y_22 ──

noncomputable def from_rotation_y_22 (angle : Real) : Real :=
  (Real.cos angle)

theorem mat4_rotation_y_cell_22 (angle : Real) :
    ((from_rotation_y_22 angle) = (Real.cos angle)) := by
  unfold from_rotation_y_22
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── rotation_y_preserves_y_witness ──

noncomputable def rotation_y_preserves_y_witness (y : Real) : Real :=
  (((((ZERO * ZERO) + (ONE * y)) + (ZERO * ZERO)) + ZERO) - y)

theorem mat4_rotation_y_preserves_y (y : Real) :
    ((rotation_y_preserves_y_witness y) = ZERO) := by
  unfold rotation_y_preserves_y_witness
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── rotation_y_orthonormal_witness ──

noncomputable def rotation_y_orthonormal_witness (angle : Real) : Real :=
  ((((Real.cos angle) * (Real.cos angle)) + ((Real.sin angle) * (Real.sin angle))) - ONE)

theorem mat4_rotation_y_orthonormal_witness (angle : Real) :
    ((rotation_y_orthonormal_witness angle) = ZERO) := by
  unfold rotation_y_orthonormal_witness
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover
