-- Generated by the EML-lang Lean backend
-- Source module: mitscherlich_yield
-- Source file:   <private>/mitscherlich_yield.eml
-- Verified fns:  yield_response, marginal_yield

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ONE : Real := (1 : Real)
noncomputable def Y_MAX : Real := (100.0 : Real)
noncomputable def K_MAX : Real := (5.0 : Real)
noncomputable def X_MAX : Real := (1000.0 : Real)

-- ── yield_response ──

noncomputable def yield_response (y_max : Real) (k_coefficient : Real) (input_applied : Real) (input_baseline : Real) : Real :=
  (y_max * (ONE - (Real.exp ((-k_coefficient) * (input_applied - input_baseline)))))

theorem mitscherlich_yield_below_potential (y_max : Real) (k_coefficient : Real) (input_applied : Real) (input_baseline : Real)
    (h1 : (y_max >= (0 : Real)))
    (h2 : (y_max <= Y_MAX))
    (h3 : (k_coefficient >= (0 : Real)))
    (h4 : (k_coefficient <= K_MAX))
    (h5 : (input_applied >= input_baseline))
    (h6 : (input_applied <= X_MAX))
    (h7 : (input_baseline >= (0 : Real))) :
    (((yield_response y_max k_coefficient input_applied input_baseline) >= (0 : Real))) ∧ (((yield_response y_max k_coefficient input_applied input_baseline) <= y_max)) := by
  unfold yield_response
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover

-- ── marginal_yield ──

noncomputable def marginal_yield (y_max : Real) (k_coefficient : Real) (input_applied : Real) (input_baseline : Real) : Real :=
  ((y_max * k_coefficient) * (Real.exp ((-k_coefficient) * (input_applied - input_baseline))))

theorem mitscherlich_marginal_yield_nonneg (y_max : Real) (k_coefficient : Real) (input_applied : Real) (input_baseline : Real)
    (h1 : (y_max >= (0 : Real)))
    (h2 : (y_max <= Y_MAX))
    (h3 : (k_coefficient >= (0 : Real)))
    (h4 : (k_coefficient <= K_MAX))
    (h5 : (input_applied >= input_baseline))
    (h6 : (input_applied <= X_MAX))
    (h7 : (input_baseline >= (0 : Real))) :
    ((marginal_yield y_max k_coefficient input_applied input_baseline) >= (0 : Real)) := by
  unfold marginal_yield
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
