-- Generated by the EML-lang Lean backend
-- Source module: motor_foc_automotive
-- Source file:   <private>/motor_foc.eml
-- Verified fns:  foc_d_axis

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def Kp_d : Real := (0.8 : Real)
noncomputable def Ki_d : Real := (12.0 : Real)
noncomputable def Kp_q : Real := (0.8 : Real)
noncomputable def Ki_q : Real := (12.0 : Real)
noncomputable def dt : Real := (0.0001 : Real)
noncomputable def V_DC : Real := (400.0 : Real)
noncomputable def V_LIMIT : Real := (230.94 : Real)

axiom pi_step (error : Real) (integral : Real) (Kp : Real) (Ki : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── foc_d_axis ──

noncomputable def foc_d_axis (i_d_setpoint : Real) (i_d_measured : Real) (i_d_integral : Real) : Real :=
  (min (max ((Kp_d * (i_d_setpoint - i_d_measured)) + (Ki_d * i_d_integral)) (-V_LIMIT)) V_LIMIT)

theorem vd_command_within_inverter_limits (i_d_setpoint : Real) (i_d_measured : Real) (i_d_integral : Real)
    (h_i_d_setpoint : (-(500.0 : Real) < i_d_setpoint ∧ i_d_setpoint < (500.0 : Real)))
    (h_i_d_measured : (-(500.0 : Real) < i_d_measured ∧ i_d_measured < (500.0 : Real)))
    (h_i_d_integral : (-(100.0 : Real) < i_d_integral ∧ i_d_integral < (100.0 : Real)))
    (h_clamp1 : (-V_LIMIT) ≤ V_LIMIT) :
    ((abs (foc_d_axis i_d_setpoint i_d_measured i_d_integral)) < V_LIMIT) := by
  unfold foc_d_axis
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
