-- Generated by the EML-lang Lean backend
-- Source module: mppt
-- Source file:   <private>/mppt.eml
-- Verified fns:  mppt_step

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def STEP : Real := (0.5 : Real)
noncomputable def V_MIN : Real := (0 : Real)
noncomputable def V_MAX : Real := (1000.0 : Real)
noncomputable def POWER_MIN : Real := (0 : Real)
noncomputable def POWER_MAX : Real := (50000.0 : Real)

-- ── mppt_step ──

noncomputable def mppt_step (voltage_now : Real) (power_now : Real) (power_prev : Real) : Real :=
  (min (max (voltage_now + (STEP * (Real.tanh (power_now - power_prev)))) V_MIN) V_MAX)

-- source obligations for mppt_step: {O1, O2}
--   O1 [d1d168ef39cb] -> PRESERVED (accounted)  theorem mppt_voltage_command_safe
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
--   O2 [0e59db6b1c76] -> PRESERVED (accounted)  theorem mppt_voltage_command_safe
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem mppt_voltage_command_safe (voltage_now : Real) (power_now : Real) (power_prev : Real)
    (h_voltage_now : ((V_MIN <= voltage_now) ∧ (voltage_now <= V_MAX)))
    (h_power_now : ((POWER_MIN <= power_now) ∧ (power_now <= POWER_MAX)))
    (h_power_prev : ((POWER_MIN <= power_prev) ∧ (power_prev <= POWER_MAX)))
    (h_clamp1 : V_MIN ≤ V_MAX) :
    ((V_MIN <= (mppt_step voltage_now power_now power_prev))) ∧ (((mppt_step voltage_now power_now power_prev) <= V_MAX)) := by
  unfold mppt_step
  try unfold STEP at *
  try unfold V_MIN at *
  try unfold V_MAX at *
  try unfold POWER_MIN at *
  try unfold POWER_MAX at *
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
