import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: mse_loss
-- Source file:   <private>/mse.eml
-- Verified fns:  mse_loss, mse_grad

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def MAX_RESIDUAL : Real := (1000000.0 : Real)
noncomputable def HALF : Real := (0.5 : Real)

axiom half_mse (prediction : Real) (target : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom squared_residual (prediction : Real) (target : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── mse_loss ──

noncomputable def mse_loss (prediction : Real) (target : Real) : Real :=
  ((prediction - target) * (prediction - target))

theorem mse_loss_nonnegative (prediction : Real) (target : Real)
    (h1 : ((abs prediction) < MAX_RESIDUAL))
    (h2 : ((abs target) < MAX_RESIDUAL)) :
    ((mse_loss prediction target) >= (0.0 : Real)) := by
  unfold mse_loss
  sorry  -- TODO: prove against MachLib foundations

-- ── mse_grad ──

noncomputable def mse_grad (prediction : Real) (target : Real) : Real :=
  ((2.0 : Real) * (prediction - target))

theorem mse_grad_sign_matches_residual (prediction : Real) (target : Real)
    (h1 : ((abs prediction) < MAX_RESIDUAL))
    (h2 : ((abs target) < MAX_RESIDUAL)) :
    True := by
  trivial
