-- Generated by the EML-lang Lean backend
-- Source module: mti_filter
-- Source file:   <private>/mti_filter.eml
-- Verified fns:  mti_2pulse, mti_3pulse, mti_4pulse_weighted, improvement_factor

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def SAMPLE_MAX : Real := (1000000.0 : Real)

-- ── mti_2pulse ──

noncomputable def mti_2pulse (sample_now : Real) (sample_prev : Real) : Real :=
  (sample_now - sample_prev)

theorem mti_2pulse_canceller_zeros_dc (sample_now : Real) (sample_prev : Real)
    (h1 : ((abs sample_now) <= SAMPLE_MAX))
    (h2 : ((abs sample_prev) <= SAMPLE_MAX)) :
    True := by
  trivial

-- ── mti_3pulse ──

noncomputable def mti_3pulse (sample_now : Real) (sample_prev1 : Real) (sample_prev2 : Real) : Real :=
  ((sample_now - ((2.0 : Real) * sample_prev1)) + sample_prev2)

theorem mti_3pulse_canceller_zeros_dc_and_first_doppler (sample_now : Real) (sample_prev1 : Real) (sample_prev2 : Real)
    (h1 : ((abs sample_now) <= SAMPLE_MAX))
    (h2 : ((abs sample_prev1) <= SAMPLE_MAX))
    (h3 : ((abs sample_prev2) <= SAMPLE_MAX)) :
    True := by
  trivial

-- ── mti_4pulse_weighted ──

noncomputable def mti_4pulse_weighted (s0 : Real) (s1 : Real) (s2 : Real) (s3 : Real) : Real :=
  (((s0 - ((3.0 : Real) * s1)) + ((3.0 : Real) * s2)) - s3)

theorem mti_4pulse_weighted_canceller (s0 : Real) (s1 : Real) (s2 : Real) (s3 : Real)
    (h1 : ((abs s0) <= SAMPLE_MAX))
    (h2 : ((abs s1) <= SAMPLE_MAX))
    (h3 : ((abs s2) <= SAMPLE_MAX))
    (h4 : ((abs s3) <= SAMPLE_MAX)) :
    True := by
  trivial

-- ── improvement_factor ──

noncomputable def improvement_factor (clutter_in_power : Real) (clutter_out_power : Real) : Real :=
  (clutter_in_power / clutter_out_power)

theorem improvement_factor_nonneg (clutter_in_power : Real) (clutter_out_power : Real)
    (h1 : (clutter_in_power >= (0 : Real)))
    (h2 : (clutter_in_power <= (1000000000000.0 : Real)))
    (h3 : (clutter_out_power >= (1e-12 : Real)))
    (h4 : (clutter_out_power <= (1000000000000.0 : Real))) :
    ((improvement_factor clutter_in_power clutter_out_power) >= (0 : Real)) := by
  unfold improvement_factor
  sorry  -- TODO: prove against MachLib foundations
