-- Generated by the EML-lang Lean backend
-- Source module: ofdm_subcarrier
-- Source file:   <private>/ofdm_subcarrier.eml
-- Verified fns:  subcarrier_phase, pilot_channel_estimate, cyclic_prefix_min_samples, carrier_freq_offset

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def N_MAX : Real := (16384.0 : Real)
noncomputable def FS_MAX : Real := (1000000000.0 : Real)
noncomputable def SPREAD_MAX : Real := (0.001 : Real)

-- ── subcarrier_phase ──

noncomputable def subcarrier_phase (bin_index : Real) (n_total : Real) : Real :=
  (((-6.283185307179586 : Real) * bin_index) / n_total)

theorem subcarrier_phase_proportional_to_bin (bin_index : Real) (n_total : Real)
    (h1 : (bin_index >= (0 : Real)))
    (h2 : (bin_index <= N_MAX))
    (h3 : (n_total >= (1 : Real)))
    (h4 : (n_total <= N_MAX)) :
    True := by
  trivial

-- ── pilot_channel_estimate ──

noncomputable def pilot_channel_estimate (received : Real) (transmitted : Real) : Real :=
  (received / transmitted)

theorem pilot_correction_unity_at_known_pilot (received : Real) (transmitted : Real)
    (h1 : ((abs received) <= (1000000.0 : Real)))
    (h2 : ((abs transmitted) >= (0.001 : Real)))
    (h3 : ((abs transmitted) <= (1000000.0 : Real))) :
    True := by
  trivial

-- ── cyclic_prefix_min_samples ──

noncomputable def cyclic_prefix_min_samples (delay_spread_s : Real) (sample_rate_hz : Real) : Real :=
  (delay_spread_s * sample_rate_hz)

theorem cp_length_proportional_to_delay_spread (delay_spread_s : Real) (sample_rate_hz : Real)
    (h1 : (delay_spread_s >= (0 : Real)))
    (h2 : (delay_spread_s <= SPREAD_MAX))
    (h3 : (sample_rate_hz >= (1 : Real)))
    (h4 : (sample_rate_hz <= FS_MAX)) :
    ((cyclic_prefix_min_samples delay_spread_s sample_rate_hz) >= (0 : Real)) := by
  unfold cyclic_prefix_min_samples
  sorry  -- TODO: prove against MachLib foundations

-- ── carrier_freq_offset ──

noncomputable def carrier_freq_offset (phase_diff : Real) (preamble_duration_s : Real) : Real :=
  (phase_diff / ((6.283185307179586 : Real) * preamble_duration_s))

theorem cfo_zero_at_zero_phase_diff (phase_diff : Real) (preamble_duration_s : Real)
    (h1 : ((abs phase_diff) <= (6.2832 : Real)))
    (h2 : (preamble_duration_s >= (1e-09 : Real)))
    (h3 : (preamble_duration_s <= (0.1 : Real))) :
    True := by
  trivial
