-- Generated by the EML-lang Lean backend
-- Source module: one_compartment
-- Source file:   <private>/one_compartment.eml
-- Verified fns:  plasma_concentration

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def T_MAX : Real := (1000.0 : Real)
noncomputable def KE_MAX : Real := (100.0 : Real)
noncomputable def V_MIN : Real := (0.1 : Real)
noncomputable def V_MAX : Real := (1000.0 : Real)
noncomputable def D_MAX : Real := (1000000.0 : Real)

axiom half_life (elimination_rate : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom auc_inf (dose : Real) (volume_of_distribution : Real) (elimination_rate : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── plasma_concentration ──

noncomputable def plasma_concentration (dose : Real) (volume_of_distribution : Real) (elimination_rate : Real) (time : Real) : Real :=
  ((dose / volume_of_distribution) * (Real.exp ((-elimination_rate) * time)))

theorem iv_bolus_decay_monotone (dose : Real) (volume_of_distribution : Real) (elimination_rate : Real) (time : Real)
    (h1 : (dose >= (0 : Real)))
    (h2 : (dose <= D_MAX))
    (h3 : (volume_of_distribution >= V_MIN))
    (h4 : (volume_of_distribution <= V_MAX))
    (h5 : (elimination_rate >= (0 : Real)))
    (h6 : (elimination_rate <= KE_MAX))
    (h7 : (time >= (0 : Real)))
    (h8 : (time <= T_MAX)) :
    ((plasma_concentration dose volume_of_distribution elimination_rate time) >= (0 : Real)) := by
  unfold plasma_concentration
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
