-- Generated by the EML-lang Lean backend
-- Source module: particle_filter_step
-- Source file:   <private>/particle_filter_step.eml
-- Verified fns:  particle_weight_update

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def SIGMA_MIN : Real := (1e-06 : Real)
noncomputable def SIGMA_MAX : Real := (1000.0 : Real)
noncomputable def Z_MAX : Real := (1000000.0 : Real)
noncomputable def HALF : Real := (0.5 : Real)

axiom ess_contribution (weight : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom propagate_constant_velocity (x_prev : Real) (velocity : Real) (dt : Real) (noise : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── particle_weight_update ──

noncomputable def particle_weight_update (prior_weight : Real) (observation : Real) (predicted : Real) (sigma : Real) : Real :=
  (prior_weight * (Real.exp ((((-HALF) * (observation - predicted)) * (observation - predicted)) / (sigma * sigma))))

theorem particle_weight_nonnegative (prior_weight : Real) (observation : Real) (predicted : Real) (sigma : Real)
    (h1 : (prior_weight >= (0 : Real)))
    (h2 : (prior_weight <= (1 : Real)))
    (h3 : ((abs observation) <= Z_MAX))
    (h4 : ((abs predicted) <= Z_MAX))
    (h5 : (sigma >= SIGMA_MIN))
    (h6 : (sigma <= SIGMA_MAX)) :
    ((particle_weight_update prior_weight observation predicted sigma) >= (0 : Real)) := by
  unfold particle_weight_update
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
