-- Generated by the EML-lang Lean backend
-- Source module: pitot_airspeed
-- Source file:   <private>/pitot_airspeed.eml
-- Verified fns:  indicated_airspeed, true_airspeed, calibrated_airspeed

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def RHO_0 : Real := (1.225 : Real)
noncomputable def RHO_MIN : Real := (0.05 : Real)
noncomputable def RHO_MAX : Real := (1.5 : Real)
noncomputable def Q_MIN : Real := (1 : Real)
noncomputable def Q_MAX : Real := (100000.0 : Real)

-- ── indicated_airspeed ──

noncomputable def indicated_airspeed (dynamic_pressure : Real) : Real :=
  (Real.sqrt (((2.0 : Real) * dynamic_pressure) / RHO_0))

theorem ias_monotone_in_dynamic_pressure (dynamic_pressure : Real)
    (h1 : (dynamic_pressure >= Q_MIN))
    (h2 : (dynamic_pressure <= Q_MAX)) :
    ((indicated_airspeed dynamic_pressure) >= (0 : Real)) := by
  unfold indicated_airspeed
  exact sqrt_nonneg _

-- ── true_airspeed ──

noncomputable def true_airspeed (ias : Real) (local_density : Real) : Real :=
  (ias * (Real.sqrt (RHO_0 / local_density)))

theorem tas_equals_ias_at_sea_level (ias : Real) (local_density : Real)
    (h1 : (ias >= (0 : Real)))
    (h2 : (ias <= (1000.0 : Real)))
    (h3 : (local_density >= RHO_MIN))
    (h4 : (local_density <= RHO_MAX)) :
    ((true_airspeed ias local_density) >= (0 : Real)) := by
  unfold true_airspeed
  sorry  -- TODO: prove against MachLib foundations

-- ── calibrated_airspeed ──

noncomputable def calibrated_airspeed (ias : Real) (position_error : Real) : Real :=
  (ias + position_error)

theorem cas_equals_ias_when_pec_zero (ias : Real) (position_error : Real)
    (h1 : (ias >= (0 : Real)))
    (h2 : (ias <= (1000.0 : Real)))
    (h3 : ((abs position_error) <= (50.0 : Real))) :
    True := by
  trivial
