-- Generated by the EML-lang Lean backend
-- Source module: pk_absorption
-- Source file:   <private>/pk_absorption.eml
-- Verified fns:  plasma_concentration

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def T_MAX : Real := (1000.0 : Real)
noncomputable def RATE_MAX : Real := (100.0 : Real)
noncomputable def V_MIN : Real := (0.1 : Real)
noncomputable def V_MAX : Real := (1000.0 : Real)

axiom time_to_cmax (absorption_rate : Real) (elimination_rate : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── plasma_concentration ──

noncomputable def plasma_concentration (dose : Real) (bioavailability : Real) (volume_of_distribution : Real) (absorption_rate : Real) (elimination_rate : Real) (time : Real) : Real :=
  ((((absorption_rate * bioavailability) * dose) / (volume_of_distribution * (absorption_rate - elimination_rate))) * ((Real.exp ((-elimination_rate) * time)) - (Real.exp ((-absorption_rate) * time))))

theorem po_absorption_rises_then_decays (dose : Real) (bioavailability : Real) (volume_of_distribution : Real) (absorption_rate : Real) (elimination_rate : Real) (time : Real)
    (h1 : (dose >= (0 : Real)))
    (h2 : (bioavailability >= (0 : Real)))
    (h3 : (bioavailability <= (1 : Real)))
    (h4 : (volume_of_distribution >= V_MIN))
    (h5 : (volume_of_distribution <= V_MAX))
    (h6 : (absorption_rate >= (0 : Real)))
    (h7 : (absorption_rate <= RATE_MAX))
    (h8 : (elimination_rate >= (0 : Real)))
    (h9 : (elimination_rate <= RATE_MAX))
    (h10 : (absorption_rate ≠ elimination_rate))
    (h11 : (time >= (0 : Real)))
    (h12 : (time <= T_MAX)) :
    ((plasma_concentration dose bioavailability volume_of_distribution absorption_rate elimination_rate time) >= (0 : Real)) := by
  unfold plasma_concentration
  sorry  -- TODO: prove against MachLib foundations
