import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: pk_two_compartment
-- Source file:   <private>/pk_two_compartment.eml
-- Verified fns:  plasma_concentration, auc_inf, effect_site_step

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def T_MAX : Real := (1440.0 : Real)
noncomputable def RATE_MIN : Real := (1e-06 : Real)
noncomputable def RATE_MAX : Real := (1.0 : Real)
noncomputable def COEF_MAX : Real := (1000.0 : Real)

-- ── plasma_concentration ──

noncomputable def plasma_concentration (coef_a : Real) (rate_alpha : Real) (coef_b : Real) (rate_beta : Real) (time_min : Real) : Real :=
  ((coef_a * (Real.exp ((-rate_alpha) * time_min))) + (coef_b * (Real.exp ((-rate_beta) * time_min))))

theorem plasma_concentration_nonneg (coef_a : Real) (rate_alpha : Real) (coef_b : Real) (rate_beta : Real) (time_min : Real)
    (h1 : (coef_a >= (0.0 : Real)))
    (h2 : (coef_a <= COEF_MAX))
    (h3 : (rate_alpha >= RATE_MIN))
    (h4 : (rate_alpha <= RATE_MAX))
    (h5 : (coef_b >= (0.0 : Real)))
    (h6 : (coef_b <= COEF_MAX))
    (h7 : (rate_beta >= RATE_MIN))
    (h8 : (rate_beta <= RATE_MAX))
    (h9 : (time_min >= (0.0 : Real)))
    (h10 : (time_min <= T_MAX)) :
    ((plasma_concentration coef_a rate_alpha coef_b rate_beta time_min) >= (0.0 : Real)) := by
  unfold plasma_concentration
  sorry  -- TODO: prove against MachLib foundations

-- ── auc_inf ──

noncomputable def auc_inf (coef_a : Real) (rate_alpha : Real) (coef_b : Real) (rate_beta : Real) : Real :=
  ((coef_a / rate_alpha) + (coef_b / rate_beta))

theorem auc_inf_finite_for_positive_rates (coef_a : Real) (rate_alpha : Real) (coef_b : Real) (rate_beta : Real)
    (h1 : (coef_a >= (0.0 : Real)))
    (h2 : (coef_a <= COEF_MAX))
    (h3 : (rate_alpha >= RATE_MIN))
    (h4 : (rate_alpha <= RATE_MAX))
    (h5 : (coef_b >= (0.0 : Real)))
    (h6 : (coef_b <= COEF_MAX))
    (h7 : (rate_beta >= RATE_MIN))
    (h8 : (rate_beta <= RATE_MAX)) :
    ((auc_inf coef_a rate_alpha coef_b rate_beta) >= (0.0 : Real)) := by
  unfold auc_inf
  sorry  -- TODO: prove against MachLib foundations

-- ── effect_site_step ──

noncomputable def effect_site_step (ce_prev : Real) (central_c : Real) (rate_keo : Real) (dt : Real) : Real :=
  (min (max (ce_prev + ((dt * rate_keo) * (central_c - ce_prev))) (0.0 : Real)) COEF_MAX)

theorem effect_site_tracks_central_compartment (ce_prev : Real) (central_c : Real) (rate_keo : Real) (dt : Real)
    (h1 : (ce_prev >= (0.0 : Real)))
    (h2 : (ce_prev <= COEF_MAX))
    (h3 : (central_c >= (0.0 : Real)))
    (h4 : (central_c <= COEF_MAX))
    (h5 : (rate_keo >= RATE_MIN))
    (h6 : (rate_keo <= RATE_MAX))
    (h7 : (dt >= (0.0 : Real)))
    (h8 : (dt <= (1.0 : Real))) :
    ((effect_site_step ce_prev central_c rate_keo dt) >= (0.0 : Real)) := by
  unfold effect_site_step
  sorry  -- TODO: prove against MachLib foundations
