-- Generated by the EML-lang Lean backend
-- Source module: plc_setpoint
-- Source file:   <private>/plc_setpoint.eml
-- Verified fns:  actuator_command

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def Kp : Real := (1.5 : Real)
noncomputable def Ki : Real := (0.3 : Real)
noncomputable def Kd : Real := (0 : Real)
noncomputable def dt : Real := (0.05 : Real)
noncomputable def I_LIMIT : Real := (50.0 : Real)
noncomputable def ACTUATOR_MIN : Real := (0 : Real)
noncomputable def ACTUATOR_MAX : Real := (100.0 : Real)
noncomputable def U_LIMIT : Real := (100.0 : Real)

axiom pid_anti_windup (error : Real) (integral : Real) (derivative : Real) (Kp : Real) (Ki : Real) (Kd : Real) (i_limit : Real) (u_limit : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── actuator_command ──

noncomputable def actuator_command (setpoint : Real) (measured : Real) (integral : Real) : Real :=
  (min (max (pid_anti_windup (setpoint - measured) integral (0 : Real) Kp Ki Kd I_LIMIT U_LIMIT) ACTUATOR_MIN) ACTUATOR_MAX)

theorem plc_actuator_command_safe (setpoint : Real) (measured : Real) (integral : Real)
    (h_setpoint : ((ACTUATOR_MIN <= setpoint) ∧ (setpoint <= ACTUATOR_MAX)))
    (h_measured : (-(1000000.0 : Real) < measured ∧ measured < (1000000.0 : Real)))
    (h_integral : (-(1000.0 : Real) < integral ∧ integral < (1000.0 : Real)))
    (h_clamp1 : ACTUATOR_MIN ≤ ACTUATOR_MAX) :
    (((ACTUATOR_MIN - (1 : Real)) <= (actuator_command setpoint measured integral))) ∧ (((actuator_command setpoint measured integral) <= (ACTUATOR_MAX + (1 : Real)))) := by
  unfold actuator_command
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
