-- Generated by the EML-lang Lean backend
-- Source module: plonk
-- Source file:   <private>/plonk.eml
-- Verified fns:  evaluate_gate, kzg_open_at

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def FIELD_BITS : Int := 254
noncomputable def GATE_DEGREE : Int := 5

axiom fadd (a : Real) (b : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

axiom fmul (a : Real) (b : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

axiom kzg_open_one (coeff : Real) (point : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

-- ── evaluate_gate ──

noncomputable def evaluate_gate (a : Real) (b : Real) (c : Real) (q_l : Real) (q_r : Real) (q_o : Real) (q_m : Real) (q_c : Real) : Real :=
  (fadd (fadd (fadd (fadd (fmul q_l a) (fmul q_r b)) (fmul q_o c)) (fmul q_m (fmul a b))) q_c)

theorem plonk_gate_satisfies_circuit (a : Real) (b : Real) (c : Real) (q_l : Real) (q_r : Real) (q_o : Real) (q_m : Real) (q_c : Real)
    (h1 : True) :
    True := by
  trivial

-- ── kzg_open_at ──

noncomputable def kzg_open_at (coeff : Real) (point : Real) : Real :=
  (kzg_open_one coeff point)

theorem plonk_kzg_open_correct (coeff : Real) (point : Real)
    (h1 : True) :
    True := by
  trivial
