import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: powder_bed_thermal
-- Source file:   <private>/powder_bed_thermal.eml
-- Verified fns:  rosenthal_delta_t, linear_energy_density, critical_cooling_rate

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def P_MIN : Real := (1.0 : Real)
noncomputable def P_MAX : Real := (10000.0 : Real)
noncomputable def K_MIN : Real := (1.0 : Real)
noncomputable def K_MAX : Real := (500.0 : Real)
noncomputable def ALPHA_MIN : Real := (1e-07 : Real)
noncomputable def ALPHA_MAX : Real := (0.001 : Real)
noncomputable def V_MIN : Real := (0.001 : Real)
noncomputable def V_MAX : Real := (10.0 : Real)
noncomputable def R_MIN : Real := (1e-06 : Real)
noncomputable def R_MAX : Real := (0.1 : Real)
noncomputable def TWO_PI : Real := (6.283185307179586 : Real)

-- ── rosenthal_delta_t ──

noncomputable def rosenthal_delta_t (laser_power : Real) (conductivity : Real) (diffusivity : Real) (scan_velocity : Real) (radial_distance : Real) (streamwise_offset : Real) : Real :=
  ((laser_power / ((TWO_PI * conductivity) * radial_distance)) * (Real.exp (((-scan_velocity) * (radial_distance + streamwise_offset)) / ((2.0 : Real) * diffusivity))))

theorem rosenthal_decreases_with_radius (laser_power : Real) (conductivity : Real) (diffusivity : Real) (scan_velocity : Real) (radial_distance : Real) (streamwise_offset : Real)
    (h1 : (laser_power >= P_MIN))
    (h2 : (laser_power <= P_MAX))
    (h3 : (conductivity >= K_MIN))
    (h4 : (conductivity <= K_MAX))
    (h5 : (diffusivity >= ALPHA_MIN))
    (h6 : (diffusivity <= ALPHA_MAX))
    (h7 : (scan_velocity >= V_MIN))
    (h8 : (scan_velocity <= V_MAX))
    (h9 : (radial_distance >= R_MIN))
    (h10 : (radial_distance <= R_MAX))
    (h11 : ((abs streamwise_offset) <= R_MAX)) :
    ((rosenthal_delta_t laser_power conductivity diffusivity scan_velocity radial_distance streamwise_offset) >= (0.0 : Real)) := by
  unfold rosenthal_delta_t
  sorry  -- TODO: prove against MachLib foundations

-- ── linear_energy_density ──

noncomputable def linear_energy_density (laser_power : Real) (scan_velocity : Real) (hatch_spacing : Real) (layer_thickness : Real) : Real :=
  (laser_power / ((scan_velocity * hatch_spacing) * layer_thickness))

theorem energy_density_inverse_to_velocity (laser_power : Real) (scan_velocity : Real) (hatch_spacing : Real) (layer_thickness : Real)
    (h1 : (laser_power >= P_MIN))
    (h2 : (laser_power <= P_MAX))
    (h3 : (scan_velocity >= V_MIN))
    (h4 : (scan_velocity <= V_MAX))
    (h5 : (hatch_spacing >= (1e-06 : Real)))
    (h6 : (hatch_spacing <= (0.001 : Real)))
    (h7 : (layer_thickness >= (1e-06 : Real)))
    (h8 : (layer_thickness <= (0.001 : Real))) :
    ((linear_energy_density laser_power scan_velocity hatch_spacing layer_thickness) >= (0.0 : Real)) := by
  unfold linear_energy_density
  sorry  -- TODO: prove against MachLib foundations

-- ── critical_cooling_rate ──

noncomputable def critical_cooling_rate (scan_velocity : Real) (delta_t_peak : Real) (diffusivity : Real) : Real :=
  (((scan_velocity * scan_velocity) * delta_t_peak) / diffusivity)

theorem cooling_rate_proportional_to_speed_squared (scan_velocity : Real) (delta_t_peak : Real) (diffusivity : Real)
    (h1 : (scan_velocity >= V_MIN))
    (h2 : (scan_velocity <= V_MAX))
    (h3 : (delta_t_peak >= (0.0 : Real)))
    (h4 : (delta_t_peak <= (5000.0 : Real)))
    (h5 : (diffusivity >= ALPHA_MIN))
    (h6 : (diffusivity <= ALPHA_MAX)) :
    ((critical_cooling_rate scan_velocity delta_t_peak diffusivity) >= (0.0 : Real)) := by
  unfold critical_cooling_rate
  sorry  -- TODO: prove against MachLib foundations
