-- Generated by the EML-lang Lean backend
-- Source module: q8_quantize
-- Source file:   <private>/q8_quantize.eml
-- Verified fns:  q8_quantize, q8_quantize_asym

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def Q8_MAX : Real := (127.0 : Real)
noncomputable def Q8_MIN : Real := (-(127.0 : Real))
noncomputable def SCALE_MIN : Real := (1e-09 : Real)
noncomputable def SCALE_MAX : Real := (1000000000.0 : Real)

axiom symmetric_scale (min_val : Real) (max_val : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── q8_quantize ──

noncomputable def q8_quantize (x : Real) (scale : Real) : Real :=
  (min (max (x / scale) Q8_MIN) Q8_MAX)

theorem q8_quantize_in_range (x : Real) (scale : Real)
    (h1 : (scale >= SCALE_MIN))
    (h2 : (scale <= SCALE_MAX)) :
    ((q8_quantize x scale) >= Q8_MIN) := by
  unfold q8_quantize
  sorry  -- TODO: prove against MachLib foundations

-- ── q8_quantize_asym ──

noncomputable def q8_quantize_asym (x : Real) (scale : Real) (zero_point : Real) : Real :=
  (min (max ((x / scale) + zero_point) (-128.0 : Real)) (127.0 : Real))

theorem q8_quantize_asym_in_range (x : Real) (scale : Real) (zero_point : Real)
    (h1 : (scale >= SCALE_MIN))
    (h2 : (scale <= SCALE_MAX))
    (h3 : (zero_point >= (-(128.0 : Real))))
    (h4 : (zero_point <= (127.0 : Real))) :
    ((q8_quantize_asym x scale zero_point) >= (-(128.0 : Real))) := by
  unfold q8_quantize_asym
  sorry  -- TODO: prove against MachLib foundations
