-- Generated by the EML-lang Lean backend
-- Source module: quat
-- Source file:   <private>/quat.eml
-- Verified fns:  identity_w, identity_x, identity_y, identity_z, from_rotation_z_w, from_rotation_z_x, from_rotation_z_y, from_rotation_z_z, from_rotation_z_norm_witness

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ONE : Real := (1 : Real)
noncomputable def HALF : Real := (0.5 : Real)

-- ── identity_w ──

noncomputable def identity_w  : Real :=
  ONE

theorem quat_identity_w_is_one  :
    ((identity_w ) = ONE) := by
  unfold identity_w
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── identity_x ──

noncomputable def identity_x  : Real :=
  ZERO

theorem quat_identity_x_is_zero  :
    ((identity_x ) = ZERO) := by
  unfold identity_x
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── identity_y ──

noncomputable def identity_y  : Real :=
  ZERO

theorem quat_identity_y_is_zero  :
    ((identity_y ) = ZERO) := by
  unfold identity_y
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── identity_z ──

noncomputable def identity_z  : Real :=
  ZERO

theorem quat_identity_z_is_zero  :
    ((identity_z ) = ZERO) := by
  unfold identity_z
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_z_w ──

noncomputable def from_rotation_z_w (angle : Real) : Real :=
  (Real.cos (HALF * angle))

theorem quat_from_rotation_z_components_w (angle : Real) :
    ((abs (from_rotation_z_w angle)) <= ONE) := by
  unfold from_rotation_z_w
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_z_x ──

noncomputable def from_rotation_z_x (angle : Real) : Real :=
  ZERO

theorem quat_from_rotation_z_components_x (angle : Real) :
    ((from_rotation_z_x angle) = ZERO) := by
  unfold from_rotation_z_x
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_z_y ──

noncomputable def from_rotation_z_y (angle : Real) : Real :=
  ZERO

theorem quat_from_rotation_z_components_y (angle : Real) :
    ((from_rotation_z_y angle) = ZERO) := by
  unfold from_rotation_z_y
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_z_z ──

noncomputable def from_rotation_z_z (angle : Real) : Real :=
  (Real.sin (HALF * angle))

theorem quat_from_rotation_z_components_z (angle : Real) :
    ((abs (from_rotation_z_z angle)) <= ONE) := by
  unfold from_rotation_z_z
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover

-- ── from_rotation_z_norm_witness ──

noncomputable def from_rotation_z_norm_witness (angle : Real) : Real :=
  (((((Real.cos (HALF * angle)) * (Real.cos (HALF * angle))) + (ZERO * ZERO)) + (ZERO * ZERO)) + ((Real.sin (HALF * angle)) * (Real.sin (HALF * angle))))

theorem quat_from_rotation_z_norm_witness (angle : Real) :
    ((from_rotation_z_norm_witness angle) = ONE) := by
  unfold from_rotation_z_norm_witness
  first
  | mach_positivity
  | rfl
  | sorry  -- mach_positivity out of reach; left for the prover
