-- Generated by the EML-lang Lean backend
-- Source module: rc_time_constant
-- Source file:   <private>/rc_time_constant.eml
-- Verified fns:  capacitor_charging, capacitor_discharging, cutoff_frequency, time_to_threshold

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def R_MIN : Real := (1 : Real)
noncomputable def R_MAX : Real := (1000000000.0 : Real)
noncomputable def C_MIN : Real := (1e-15 : Real)
noncomputable def C_MAX : Real := (0.1 : Real)
noncomputable def V_MAX : Real := (1000.0 : Real)
noncomputable def T_MAX : Real := (100.0 : Real)

-- ── capacitor_charging ──

noncomputable def capacitor_charging (v_supply : Real) (resistance : Real) (capacitance : Real) (time_s : Real) : Real :=
  (v_supply * ((1 : Real) - (Real.exp ((-time_s) / (resistance * capacitance)))))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem rc_charging_voltage_in_unit_interval (v_supply : Real) (resistance : Real) (capacitance : Real) (time_s : Real)
    (h1 : ((abs v_supply) <= V_MAX))
    (h2 : (resistance >= R_MIN))
    (h3 : (resistance <= R_MAX))
    (h4 : (capacitance >= C_MIN))
    (h5 : (capacitance <= C_MAX))
    (h6 : (time_s >= (0 : Real)))
    (h7 : (time_s <= T_MAX)) :
    True := by
  trivial

-- ── capacitor_discharging ──

noncomputable def capacitor_discharging (v_initial : Real) (resistance : Real) (capacitance : Real) (time_s : Real) : Real :=
  (v_initial * (Real.exp ((-time_s) / (resistance * capacitance))))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem rc_discharging_voltage_decays_to_zero (v_initial : Real) (resistance : Real) (capacitance : Real) (time_s : Real)
    (h1 : ((abs v_initial) <= V_MAX))
    (h2 : (resistance >= R_MIN))
    (h3 : (resistance <= R_MAX))
    (h4 : (capacitance >= C_MIN))
    (h5 : (capacitance <= C_MAX))
    (h6 : (time_s >= (0 : Real)))
    (h7 : (time_s <= T_MAX)) :
    True := by
  trivial

-- ── cutoff_frequency ──

noncomputable def cutoff_frequency (resistance : Real) (capacitance : Real) : Real :=
  ((1 : Real) / (((6.283185307179586 : Real) * resistance) * capacitance))

theorem cutoff_freq_inverse_to_rc (resistance : Real) (capacitance : Real)
    (h1 : (resistance >= R_MIN))
    (h2 : (resistance <= R_MAX))
    (h3 : (capacitance >= C_MIN))
    (h4 : (capacitance <= C_MAX)) :
    ((cutoff_frequency resistance capacitance) >= (0 : Real)) := by
  unfold cutoff_frequency
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── time_to_threshold ──

noncomputable def time_to_threshold (target_fraction : Real) (resistance : Real) (capacitance : Real) : Real :=
  (((-resistance) * capacitance) * (Real.log ((1 : Real) - target_fraction)))

theorem time_to_threshold_increases_with_target (target_fraction : Real) (resistance : Real) (capacitance : Real)
    (h1 : (target_fraction >= (0.001 : Real)))
    (h2 : (target_fraction <= (0.999 : Real)))
    (h3 : (resistance >= R_MIN))
    (h4 : (resistance <= R_MAX))
    (h5 : (capacitance >= C_MIN))
    (h6 : (capacitance <= C_MAX)) :
    ((time_to_threshold target_fraction resistance capacitance) >= (0 : Real)) := by
  unfold time_to_threshold
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
