-- Generated by the EML-lang Lean backend
-- Source module: reactor_temperature
-- Source file:   <private>/reactor_temperature.eml
-- Verified fns:  reaction_heat_load

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def R_GAS : Real := (8.314462618 : Real)
noncomputable def T_MIN : Real := (250.0 : Real)
noncomputable def T_MAX : Real := (800.0 : Real)
noncomputable def C_MAX : Real := (10000.0 : Real)
noncomputable def V_MAX : Real := (1000.0 : Real)
noncomputable def EA_MAX : Real := (500000.0 : Real)
noncomputable def HRXN_MAX : Real := (1000000.0 : Real)

axiom required_cooling_duty (reaction_heat : Real) (safety_factor : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── reaction_heat_load ──

noncomputable def reaction_heat_load (delta_h_rxn : Real) (reactor_volume : Real) (concentration_a : Real) (pre_exp_factor : Real) (activation_energy : Real) (temperature : Real) : Real :=
  (((delta_h_rxn * reactor_volume) * concentration_a) * (pre_exp_factor * (Real.exp ((-activation_energy) / (R_GAS * temperature)))))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem reaction_heat_monotone_in_temperature (delta_h_rxn : Real) (reactor_volume : Real) (concentration_a : Real) (pre_exp_factor : Real) (activation_energy : Real) (temperature : Real)
    (h1 : (delta_h_rxn >= (-HRXN_MAX)))
    (h2 : (delta_h_rxn <= HRXN_MAX))
    (h3 : (reactor_volume > (0 : Real)))
    (h4 : (reactor_volume <= V_MAX))
    (h5 : (concentration_a >= (0 : Real)))
    (h6 : (concentration_a <= C_MAX))
    (h7 : (pre_exp_factor > (0 : Real)))
    (h8 : (activation_energy >= (0 : Real)))
    (h9 : (activation_energy <= EA_MAX))
    (h10 : (temperature >= T_MIN))
    (h11 : (temperature <= T_MAX)) :
    True := by
  trivial
