-- Generated by the EML-lang Lean backend
-- Source module: relativistic_doppler
-- Source file:   <private>/relativistic_doppler.eml
-- Verified fns:  recession_doppler_ratio, approach_doppler_ratio, observed_frequency, lorentz_factor, velocity_to_beta

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def ONE : Real := (1 : Real)
noncomputable def C_LIGHT : Real := (299792458.0 : Real)
noncomputable def BETA_MAX : Real := (0.999 : Real)
noncomputable def F_MAX : Real := (1e+30 : Real)

-- ── recession_doppler_ratio ──

noncomputable def recession_doppler_ratio (beta : Real) : Real :=
  (Real.sqrt ((ONE - beta) / (ONE + beta)))

theorem doppler_recession_factor_below_one (beta : Real)
    (h1 : (beta >= (0 : Real)))
    (h2 : (beta <= BETA_MAX)) :
    ((recession_doppler_ratio beta) <= ONE) := by
  unfold recession_doppler_ratio
  sorry  -- TODO: prove against MachLib foundations

-- ── approach_doppler_ratio ──

noncomputable def approach_doppler_ratio (beta : Real) : Real :=
  (Real.sqrt ((ONE + beta) / (ONE - beta)))

theorem doppler_approach_factor_above_one (beta : Real)
    (h1 : (beta >= (0 : Real)))
    (h2 : (beta <= BETA_MAX)) :
    ((approach_doppler_ratio beta) >= ONE) := by
  unfold approach_doppler_ratio
  sorry  -- TODO: prove against MachLib foundations

-- ── observed_frequency ──

noncomputable def observed_frequency (source_frequency : Real) (doppler_ratio : Real) : Real :=
  (source_frequency * doppler_ratio)

theorem doppler_observed_frequency_positive (source_frequency : Real) (doppler_ratio : Real)
    (h1 : (source_frequency > (0 : Real)))
    (h2 : (source_frequency <= F_MAX))
    (h3 : (doppler_ratio > (0 : Real)))
    (h4 : (doppler_ratio <= (1000000.0 : Real))) :
    ((observed_frequency source_frequency doppler_ratio) > (0 : Real)) := by
  unfold observed_frequency
  apply mul_pos <;> first | assumption | exact exp_pos _

-- ── lorentz_factor ──

noncomputable def lorentz_factor (beta : Real) : Real :=
  (ONE / (Real.sqrt (ONE - (beta * beta))))

theorem lorentz_factor_at_least_one (beta : Real)
    (h1 : (beta >= (0 : Real)))
    (h2 : (beta <= BETA_MAX)) :
    ((lorentz_factor beta) >= ONE) := by
  unfold lorentz_factor
  sorry  -- TODO: prove against MachLib foundations

-- ── velocity_to_beta ──

noncomputable def velocity_to_beta (velocity_m_per_s : Real) : Real :=
  (velocity_m_per_s / C_LIGHT)

theorem beta_in_unit_interval_for_subluminal_v (velocity_m_per_s : Real)
    (h1 : (velocity_m_per_s >= (0 : Real)))
    (h2 : (velocity_m_per_s <= (BETA_MAX * C_LIGHT))) :
    ((velocity_to_beta velocity_m_per_s) >= (0 : Real)) := by
  unfold velocity_to_beta
  sorry  -- TODO: prove against MachLib foundations
