import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: reverb_decay
-- Source file:   <private>/reverb_decay.eml
-- Verified fns:  reverb_envelope, schroeder_gain

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def RT60_MIN : Real := (0.05 : Real)
noncomputable def RT60_MAX : Real := (10.0 : Real)
noncomputable def T_MAX : Real := (60.0 : Real)
noncomputable def LN_1000 : Real := (6.907755278982137 : Real)

axiom wet_dry_mix (dry : Real) (wet : Real) (mix : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── reverb_envelope ──

noncomputable def reverb_envelope (time_s : Real) (rt60 : Real) : Real :=
  (Real.exp (((-time_s) * LN_1000) / rt60))

theorem reverb_envelope_decreases_with_time (time_s : Real) (rt60 : Real)
    (h1 : (time_s >= (0.0 : Real)))
    (h2 : (time_s <= T_MAX))
    (h3 : (rt60 >= RT60_MIN))
    (h4 : (rt60 <= RT60_MAX)) :
    ((reverb_envelope time_s rt60) >= (0.0 : Real)) := by
  unfold reverb_envelope
  sorry  -- TODO: prove against MachLib foundations

-- ── schroeder_gain ──

noncomputable def schroeder_gain (target_decay : Real) (n_samples : Real) (n_total : Real) : Real :=
  (target_decay ^ (n_samples / n_total))

theorem schroeder_gain_in_unit_interval (target_decay : Real) (n_samples : Real) (n_total : Real)
    (h1 : (target_decay >= (1e-09 : Real)))
    (h2 : (target_decay <= (1.0 : Real)))
    (h3 : (n_samples >= (0.0 : Real)))
    (h4 : (n_samples <= (1000000.0 : Real)))
    (h5 : (n_total >= (1.0 : Real)))
    (h6 : (n_total <= (1000000.0 : Real))) :
    ((schroeder_gain target_decay n_samples n_total) >= (0.0 : Real)) := by
  unfold schroeder_gain
  sorry  -- TODO: prove against MachLib foundations
