import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: rho
-- Source file:   <private>/rho.eml
-- Verified fns:  rho_call, rho_put

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def SQRT_2_OVER_PI : Real := (0.7978845608028654 : Real)
noncomputable def GELU_C3 : Real := (0.044715 : Real)
noncomputable def HALF : Real := (0.5 : Real)
noncomputable def ONE : Real := (1.0 : Real)
noncomputable def TINY_T : Real := (0.000274 : Real)
noncomputable def T_MAX : Real := (30.0 : Real)
noncomputable def STRIKE_MAX : Real := (1000000.0 : Real)
noncomputable def RATE_MAX : Real := (0.5 : Real)

axiom norm_cdf (x : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom bs_d2 (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── rho_call ──

noncomputable def rho_call (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real :=
  (((strike * time_to_expiry) * (Real.exp ((-rate) * time_to_expiry))) * (HALF * (ONE + (Real.tanh (SQRT_2_OVER_PI * ((bs_d2 spot strike rate vol time_to_expiry) + (((GELU_C3 * (bs_d2 spot strike rate vol time_to_expiry)) * (bs_d2 spot strike rate vol time_to_expiry)) * (bs_d2 spot strike rate vol time_to_expiry))))))))

theorem rho_call_nonneg (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real)
    (h1 : (spot > (0.0 : Real)))
    (h2 : (strike > (0.0 : Real)))
    (h3 : (strike <= STRIKE_MAX))
    (h4 : (vol > (0.0 : Real)))
    (h5 : (rate >= (-RATE_MAX)))
    (h6 : (rate <= RATE_MAX))
    (h7 : (time_to_expiry >= TINY_T))
    (h8 : (time_to_expiry <= T_MAX)) :
    ((rho_call spot strike rate vol time_to_expiry) >= (0.0 : Real)) := by
  unfold rho_call
  sorry  -- TODO: prove against MachLib foundations

-- ── rho_put ──

noncomputable def rho_put (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real :=
  ((((-strike) * time_to_expiry) * (Real.exp ((-rate) * time_to_expiry))) * (ONE - (HALF * (ONE + (Real.tanh (SQRT_2_OVER_PI * ((bs_d2 spot strike rate vol time_to_expiry) + (((GELU_C3 * (bs_d2 spot strike rate vol time_to_expiry)) * (bs_d2 spot strike rate vol time_to_expiry)) * (bs_d2 spot strike rate vol time_to_expiry)))))))))

theorem rho_put_nonpos (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real)
    (h1 : (spot > (0.0 : Real)))
    (h2 : (strike > (0.0 : Real)))
    (h3 : (strike <= STRIKE_MAX))
    (h4 : (vol > (0.0 : Real)))
    (h5 : (rate >= (-RATE_MAX)))
    (h6 : (rate <= RATE_MAX))
    (h7 : (time_to_expiry >= TINY_T))
    (h8 : (time_to_expiry <= T_MAX)) :
    ((rho_put spot strike rate vol time_to_expiry) <= (0.0 : Real)) := by
  unfold rho_put
  sorry  -- TODO: prove against MachLib foundations
