-- Generated by the EML-lang Lean backend
-- Source module: rocket_thrust
-- Source file:   <private>/rocket_thrust.eml
-- Verified fns:  tsiolkovsky_dv, rocket_gross_thrust, rocket_specific_impulse

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def G_GRAVITY : Real := (9.80665 : Real)
noncomputable def VEL_MAX : Real := (10000.0 : Real)
noncomputable def MASS_MIN : Real := (0.001 : Real)
noncomputable def MASS_MAX : Real := (10000000.0 : Real)
noncomputable def ISP_MAX : Real := (1000.0 : Real)

-- ── tsiolkovsky_dv ──

noncomputable def tsiolkovsky_dv (exhaust_velocity : Real) (initial_mass : Real) (final_mass : Real) : Real :=
  (exhaust_velocity * (Real.log (initial_mass / final_mass)))

theorem tsiolkovsky_dv_monotone_in_mass_ratio (exhaust_velocity : Real) (initial_mass : Real) (final_mass : Real)
    (h1 : (exhaust_velocity >= (0 : Real)))
    (h2 : (exhaust_velocity <= VEL_MAX))
    (h3 : (initial_mass >= MASS_MIN))
    (h4 : (initial_mass <= MASS_MAX))
    (h5 : (final_mass >= MASS_MIN))
    (h6 : (final_mass <= initial_mass)) :
    ((tsiolkovsky_dv exhaust_velocity initial_mass final_mass) >= (0 : Real)) := by
  unfold tsiolkovsky_dv
  sorry  -- TODO: prove against MachLib foundations

-- ── rocket_gross_thrust ──

noncomputable def rocket_gross_thrust (mass_flow : Real) (exhaust_velocity : Real) (exit_pressure : Real) (ambient_pressure : Real) (exit_area : Real) : Real :=
  ((mass_flow * exhaust_velocity) + ((exit_pressure - ambient_pressure) * exit_area))

theorem rocket_gross_thrust_nonneg_for_positive_mass_flow (mass_flow : Real) (exhaust_velocity : Real) (exit_pressure : Real) (ambient_pressure : Real) (exit_area : Real)
    (h1 : (mass_flow >= (0 : Real)))
    (h2 : (mass_flow <= (10000.0 : Real)))
    (h3 : (exhaust_velocity >= (0 : Real)))
    (h4 : (exhaust_velocity <= VEL_MAX))
    (h5 : (exit_pressure >= (0 : Real)))
    (h6 : (exit_pressure <= (100000000.0 : Real)))
    (h7 : (ambient_pressure >= (0 : Real)))
    (h8 : (ambient_pressure <= (1000000.0 : Real)))
    (h9 : (exit_area >= (0.001 : Real)))
    (h10 : (exit_area <= (100.0 : Real))) :
    True := by
  trivial

-- ── rocket_specific_impulse ──

noncomputable def rocket_specific_impulse (thrust : Real) (mass_flow : Real) : Real :=
  (thrust / (mass_flow * G_GRAVITY))

theorem rocket_isp_inverse_proportional_to_mass_flow (thrust : Real) (mass_flow : Real)
    (h1 : (thrust >= (0 : Real)))
    (h2 : (thrust <= (100000000.0 : Real)))
    (h3 : (mass_flow >= (0.001 : Real)))
    (h4 : (mass_flow <= (10000.0 : Real))) :
    ((rocket_specific_impulse thrust mass_flow) >= (0 : Real)) := by
  unfold rocket_specific_impulse
  sorry  -- TODO: prove against MachLib foundations
