-- Generated by the EML-lang Lean backend
-- Source module: sabr
-- Source file:   <private>/sabr.eml
-- Verified fns:  sabr_atm_vol

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def HALF : Real := (0.5 : Real)
noncomputable def QUARTER : Real := (0.25 : Real)
noncomputable def ONE_24 : Real := (0.041666666666666664 : Real)

-- ── sabr_atm_vol ──

noncomputable def sabr_atm_vol (forward : Real) (alpha : Real) (beta : Real) (rho : Real) (nu : Real) (time_to_expiry : Real) : Real :=
  ((alpha / (forward ^ ((1 : Real) - beta))) * ((1 : Real) + ((((((ONE_24 * (((1 : Real) - beta) * ((1 : Real) - beta))) * (alpha / (forward ^ ((1 : Real) - beta)))) * (alpha / (forward ^ ((1 : Real) - beta)))) + ((((QUARTER * beta) * rho) * nu) * (alpha / (forward ^ ((1 : Real) - beta))))) + (((ONE_24 * ((2.0 : Real) - (((3.0 : Real) * rho) * rho))) * nu) * nu)) * time_to_expiry)))

theorem sabr_atm_vol_positive (forward : Real) (alpha : Real) (beta : Real) (rho : Real) (nu : Real) (time_to_expiry : Real)
    (h1 : (forward > (0 : Real)))
    (h2 : (alpha > (0 : Real)))
    (h3 : (beta >= (0 : Real)))
    (h4 : (beta <= (1 : Real)))
    (h5 : (nu >= (0 : Real)))
    (h6 : (time_to_expiry >= (0 : Real))) :
    ((sabr_atm_vol forward alpha beta rho nu time_to_expiry) > (0 : Real)) := by
  unfold sabr_atm_vol
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
