-- Generated by the EML-lang Lean backend
-- Source module: sar_phase
-- Source file:   <private>/sar_phase.eml
-- Verified fns:  sar_phase_arg, sar_kernel_real, sar_kernel_imag

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

-- ── sar_phase_arg ──

noncomputable def sar_phase_arg (range_r0 : Real) (t_az : Real) (v_plat : Real) (lambda_m : Real) : Real :=
  ((((12.566370614359172 : Real) * range_r0) * ((1 : Real) - (Real.cos ((v_plat * t_az) / range_r0)))) / lambda_m)

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem sar_phase_arg_zero_at_broadside (range_r0 : Real) (t_az : Real) (v_plat : Real) (lambda_m : Real)
    (h1 : (range_r0 > (0 : Real)))
    (h2 : (lambda_m > (0 : Real))) :
    True := by
  trivial

-- ── sar_kernel_real ──

noncomputable def sar_kernel_real (arg : Real) : Real :=
  (Real.cos arg)

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem sar_kernel_real_unit_at_zero_arg (arg : Real) :
    True := by
  trivial

-- ── sar_kernel_imag ──

noncomputable def sar_kernel_imag (arg : Real) : Real :=
  (Real.sin arg)

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem sar_kernel_imag_zero_at_zero_arg (arg : Real) :
    True := by
  trivial
