-- Generated by the EML-lang Lean backend
-- Source module: sas_pitch_damper
-- Source file:   <private>/sas_pitch_damper.eml
-- Verified fns:  sas_pitch_command, scheduled_gain, elevator_with_trim

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def Q_MAX : Real := (5.0 : Real)
noncomputable def M_MAX : Real := (5.0 : Real)
noncomputable def H_MAX : Real := (25000.0 : Real)
noncomputable def K_BASE_MAX : Real := (50.0 : Real)
noncomputable def A_M_MAX : Real := (5.0 : Real)
noncomputable def A_H_MAX : Real := (5.0 : Real)
noncomputable def ELEV_MAX : Real := (0.7 : Real)

-- ── sas_pitch_command ──

noncomputable def sas_pitch_command (pitch_rate_meas : Real) (pitch_rate_cmd : Real) (gain : Real) : Real :=
  (min (max ((-gain) * (pitch_rate_meas - pitch_rate_cmd)) (-ELEV_MAX)) ELEV_MAX)

theorem sas_pitch_command_signed_by_rate_error (pitch_rate_meas : Real) (pitch_rate_cmd : Real) (gain : Real)
    (h1 : ((abs pitch_rate_meas) <= Q_MAX))
    (h2 : ((abs pitch_rate_cmd) <= Q_MAX))
    (h3 : (gain >= (0 : Real)))
    (h4 : (gain <= K_BASE_MAX)) :
    True := by
  trivial

-- ── scheduled_gain ──

noncomputable def scheduled_gain (base_gain : Real) (mach : Real) (altitude : Real) (a_mach : Real) (a_altitude : Real) : Real :=
  (min (max (base_gain * (((1 : Real) + (a_mach * mach)) + (a_altitude * (altitude / H_MAX)))) (0 : Real)) ((5.0 : Real) * K_BASE_MAX))

theorem scheduled_gain_increases_with_dynamic_pressure (base_gain : Real) (mach : Real) (altitude : Real) (a_mach : Real) (a_altitude : Real)
    (h1 : (base_gain >= (0 : Real)))
    (h2 : (base_gain <= K_BASE_MAX))
    (h3 : (mach >= (0 : Real)))
    (h4 : (mach <= M_MAX))
    (h5 : (altitude >= (0 : Real)))
    (h6 : (altitude <= H_MAX))
    (h7 : ((abs a_mach) <= A_M_MAX))
    (h8 : ((abs a_altitude) <= A_H_MAX)) :
    ((scheduled_gain base_gain mach altitude a_mach a_altitude) >= (0 : Real)) := by
  unfold scheduled_gain
  sorry  -- TODO: prove against MachLib foundations

-- ── elevator_with_trim ──

noncomputable def elevator_with_trim (sas_command : Real) (pilot_stick : Real) (trim_bias : Real) : Real :=
  (min (max ((sas_command + pilot_stick) + trim_bias) (-ELEV_MAX)) ELEV_MAX)

theorem trim_bias_combined_within_authority (sas_command : Real) (pilot_stick : Real) (trim_bias : Real)
    (h1 : ((abs sas_command) <= ELEV_MAX))
    (h2 : ((abs pilot_stick) <= ELEV_MAX))
    (h3 : ((abs trim_bias) <= ELEV_MAX)) :
    True := by
  trivial
