-- Generated by the EML-lang Lean backend
-- Source module: schwarzschild_radius
-- Source file:   <private>/schwarzschild_radius.eml
-- Verified fns:  schwarzschild_radius, gravitational_redshift_factor, newtonian_orbital_velocity, photon_sphere_radius

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def G_GRAV : Real := (6.6743e-11 : Real)
noncomputable def C_LIGHT : Real := (299792458.0 : Real)
noncomputable def C_SQ : Real := (8.987551787368176e+16 : Real)
noncomputable def M_MIN : Real := (1 : Real)
noncomputable def M_MAX : Real := (1e+40 : Real)
noncomputable def R_MIN : Real := (1 : Real)
noncomputable def R_MAX : Real := (1e+25 : Real)

-- ── schwarzschild_radius ──

noncomputable def schwarzschild_radius (mass_kg : Real) : Real :=
  ((((2.0 : Real) * G_GRAV) * mass_kg) / C_SQ)

theorem schwarzschild_radius_proportional_to_mass (mass_kg : Real)
    (h1 : (mass_kg >= M_MIN))
    (h2 : (mass_kg <= M_MAX)) :
    ((schwarzschild_radius mass_kg) >= (0 : Real)) := by
  unfold schwarzschild_radius
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── gravitational_redshift_factor ──

noncomputable def gravitational_redshift_factor (schwarzschild_r : Real) (radius : Real) : Real :=
  ((1 : Real) / (Real.sqrt (min (max ((1 : Real) - (schwarzschild_r / radius)) (1e-09 : Real)) (1 : Real))))

theorem redshift_unity_at_infinity (schwarzschild_r : Real) (radius : Real)
    (h1 : (schwarzschild_r >= (0 : Real)))
    (h2 : (schwarzschild_r <= R_MAX))
    (h3 : (radius >= R_MIN))
    (h4 : (radius <= R_MAX))
    (h5 : (radius > schwarzschild_r))
    (h_clamp1 : (1e-09 : Real) ≤ (1 : Real)) :
    ((gravitational_redshift_factor schwarzschild_r radius) >= (1 : Real)) := by
  unfold gravitational_redshift_factor
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── newtonian_orbital_velocity ──

noncomputable def newtonian_orbital_velocity (mass_kg : Real) (radius : Real) : Real :=
  (Real.sqrt ((G_GRAV * mass_kg) / radius))

theorem orbital_velocity_decreases_with_radius (mass_kg : Real) (radius : Real)
    (h1 : (mass_kg >= M_MIN))
    (h2 : (mass_kg <= M_MAX))
    (h3 : (radius >= R_MIN))
    (h4 : (radius <= R_MAX)) :
    ((newtonian_orbital_velocity mass_kg radius) >= (0 : Real)) := by
  unfold newtonian_orbital_velocity
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── photon_sphere_radius ──

noncomputable def photon_sphere_radius (schwarzschild_r : Real) : Real :=
  ((1.5 : Real) * schwarzschild_r)

theorem photon_sphere_above_horizon (schwarzschild_r : Real)
    (h1 : (schwarzschild_r >= (0 : Real)))
    (h2 : (schwarzschild_r <= R_MAX)) :
    ((photon_sphere_radius schwarzschild_r) >= (0 : Real)) := by
  unfold photon_sphere_radius
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
