-- Generated by the EML-lang Lean backend
-- Source module: second_order
-- Source file:   <private>/second_order.eml
-- Verified fns:  concentration_at

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def T_MAX : Real := (100000000.0 : Real)
noncomputable def K_MAX : Real := (1000000.0 : Real)
noncomputable def C0_MAX : Real := (1000.0 : Real)

axiom half_life (rate_constant : Real) (initial_concentration : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom inverse_concentration (concentration : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── concentration_at ──

noncomputable def concentration_at (initial_concentration : Real) (rate_constant : Real) (time : Real) : Real :=
  (initial_concentration / ((1 : Real) + ((rate_constant * initial_concentration) * time)))

theorem second_order_decay_monotone (initial_concentration : Real) (rate_constant : Real) (time : Real)
    (h1 : (initial_concentration > (0 : Real)))
    (h2 : (initial_concentration <= C0_MAX))
    (h3 : (rate_constant >= (0 : Real)))
    (h4 : (rate_constant <= K_MAX))
    (h5 : (time >= (0 : Real)))
    (h6 : (time <= T_MAX)) :
    (((concentration_at initial_concentration rate_constant time) > (0 : Real))) ∧ (((concentration_at initial_concentration rate_constant time) <= initial_concentration)) := by
  unfold concentration_at
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
