-- Generated by the EML-lang Lean backend
-- Source module: seir_epidemic
-- Source file:   <private>/seir_epidemic.eml
-- Verified fns:  step_susceptible, step_exposed, step_infectious, step_recovered, basic_reproduction_number

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def ONE : Real := (1 : Real)
noncomputable def N_MIN : Real := (1 : Real)
noncomputable def N_MAX : Real := (10000000000.0 : Real)
noncomputable def RATE_MAX : Real := (10.0 : Real)
noncomputable def DT_MAX : Real := (1 : Real)

-- ── step_susceptible ──

noncomputable def step_susceptible (s : Real) (i : Real) (n : Real) (beta : Real) (dt : Real) : Real :=
  (s - ((((beta * s) * i) / n) * dt))

theorem seir_step_susceptible_nonincreasing (s : Real) (i : Real) (n : Real) (beta : Real) (dt : Real)
    (h1 : (s >= (0 : Real)))
    (h2 : (i >= (0 : Real)))
    (h3 : (n >= N_MIN))
    (h4 : (n <= N_MAX))
    (h5 : (beta >= (0 : Real)))
    (h6 : (beta <= RATE_MAX))
    (h7 : (dt >= (0 : Real)))
    (h8 : (dt <= DT_MAX)) :
    ((step_susceptible s i n beta dt) <= s) := by
  unfold step_susceptible
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── step_exposed ──

noncomputable def step_exposed (s : Real) (e : Real) (i : Real) (n : Real) (beta : Real) (sigma : Real) (dt : Real) : Real :=
  (e + (((((beta * s) * i) / n) - (sigma * e)) * dt))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem seir_step_exposed_nonneg (s : Real) (e : Real) (i : Real) (n : Real) (beta : Real) (sigma : Real) (dt : Real)
    (h1 : (s >= (0 : Real)))
    (h2 : (e >= (0 : Real)))
    (h3 : (i >= (0 : Real)))
    (h4 : (n >= N_MIN))
    (h5 : (n <= N_MAX))
    (h6 : (beta >= (0 : Real)))
    (h7 : (beta <= RATE_MAX))
    (h8 : (sigma >= (0 : Real)))
    (h9 : (sigma <= RATE_MAX))
    (h10 : (dt >= (0 : Real)))
    (h11 : (dt <= DT_MAX))
    (h12 : ((sigma * dt) <= ONE)) :
    True := by
  trivial

-- ── step_infectious ──

noncomputable def step_infectious (e : Real) (i : Real) (sigma : Real) (gamma : Real) (dt : Real) : Real :=
  (i + (((sigma * e) - (gamma * i)) * dt))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem seir_step_infectious_nonneg (e : Real) (i : Real) (sigma : Real) (gamma : Real) (dt : Real)
    (h1 : (e >= (0 : Real)))
    (h2 : (i >= (0 : Real)))
    (h3 : (sigma >= (0 : Real)))
    (h4 : (sigma <= RATE_MAX))
    (h5 : (gamma >= (0 : Real)))
    (h6 : (gamma <= RATE_MAX))
    (h7 : (dt >= (0 : Real)))
    (h8 : (dt <= DT_MAX))
    (h9 : ((gamma * dt) <= ONE)) :
    True := by
  trivial

-- ── step_recovered ──

noncomputable def step_recovered (i : Real) (r : Real) (gamma : Real) (dt : Real) : Real :=
  (r + ((gamma * i) * dt))

theorem seir_step_recovered_nondecreasing (i : Real) (r : Real) (gamma : Real) (dt : Real)
    (h1 : (i >= (0 : Real)))
    (h2 : (r >= (0 : Real)))
    (h3 : (gamma >= (0 : Real)))
    (h4 : (gamma <= RATE_MAX))
    (h5 : (dt >= (0 : Real)))
    (h6 : (dt <= DT_MAX)) :
    ((step_recovered i r gamma dt) >= r) := by
  unfold step_recovered
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── basic_reproduction_number ──

noncomputable def basic_reproduction_number (beta : Real) (gamma : Real) : Real :=
  (beta / gamma)

theorem seir_r0_threshold_at_one (beta : Real) (gamma : Real)
    (h1 : (beta >= (0 : Real)))
    (h2 : (beta <= RATE_MAX))
    (h3 : (gamma >= (0.001 : Real)))
    (h4 : (gamma <= RATE_MAX)) :
    ((basic_reproduction_number beta gamma) >= (0 : Real)) := by
  unfold basic_reproduction_number
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
