import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: sgd_optimizer
-- Source file:   <private>/sgd.eml
-- Verified fns:  sgd_step, momentum_velocity_step, nesterov_step

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def LR_MIN : Real := (1e-09 : Real)
noncomputable def LR_MAX : Real := (1.0 : Real)
noncomputable def MOM_MAX : Real := (1.0 : Real)
noncomputable def VAL_MAX : Real := (1000000.0 : Real)

axiom sgdw_step (theta : Real) (gradient : Real) (lr : Real) (weight_decay : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── sgd_step ──

noncomputable def sgd_step (theta : Real) (gradient : Real) (lr : Real) : Real :=
  (theta - (lr * gradient))

theorem sgd_step_descent_when_grad_signed (theta : Real) (gradient : Real) (lr : Real)
    (h1 : ((abs theta) <= VAL_MAX))
    (h2 : ((abs gradient) <= VAL_MAX))
    (h3 : (lr >= LR_MIN))
    (h4 : (lr <= LR_MAX)) :
    True := by
  trivial

-- ── momentum_velocity_step ──

noncomputable def momentum_velocity_step (velocity : Real) (gradient : Real) (beta : Real) : Real :=
  ((beta * velocity) + gradient)

theorem momentum_velocity_decays_with_beta (velocity : Real) (gradient : Real) (beta : Real)
    (h1 : ((abs velocity) <= VAL_MAX))
    (h2 : ((abs gradient) <= VAL_MAX))
    (h3 : (beta >= (0.0 : Real)))
    (h4 : (beta <= MOM_MAX)) :
    True := by
  trivial

-- ── nesterov_step ──

noncomputable def nesterov_step (theta : Real) (velocity : Real) (gradient : Real) (beta : Real) (lr : Real) : Real :=
  (theta - (lr * ((beta * velocity) + gradient)))

theorem nesterov_step_consistent_with_lookahead (theta : Real) (velocity : Real) (gradient : Real) (beta : Real) (lr : Real)
    (h1 : ((abs theta) <= VAL_MAX))
    (h2 : ((abs velocity) <= VAL_MAX))
    (h3 : ((abs gradient) <= VAL_MAX))
    (h4 : (beta >= (0.0 : Real)))
    (h5 : (beta <= MOM_MAX))
    (h6 : (lr >= LR_MIN))
    (h7 : (lr <= LR_MAX)) :
    True := by
  trivial
