-- Generated by the EML-lang Lean backend
-- Source module: shadow_pcf
-- Source file:   <private>/shadow_pcf.eml
-- Verified fns:  pcf_4tap, pcf_9tap

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ONE : Real := (1 : Real)
noncomputable def QUARTER : Real := (0.25 : Real)
noncomputable def NINTH : Real := (0.111111111111111 : Real)
noncomputable def BIAS_MAX : Real := (0.01 : Real)
noncomputable def DEPTH_MAX : Real := (1 : Real)

-- ── pcf_4tap ──

noncomputable def pcf_4tap (query_depth : Real) (sample0 : Real) (sample1 : Real) (sample2 : Real) (sample3 : Real) (bias : Real) : Real :=
  (QUARTER * ((((step sample0 (query_depth - bias)) + (step sample1 (query_depth - bias))) + (step sample2 (query_depth - bias))) + (step sample3 (query_depth - bias))))

theorem shadow_pcf4_in_unit_interval (query_depth : Real) (sample0 : Real) (sample1 : Real) (sample2 : Real) (sample3 : Real) (bias : Real)
    (h1 : (query_depth >= (0 : Real)))
    (h2 : (query_depth <= DEPTH_MAX))
    (h3 : (sample0 >= (0 : Real)))
    (h4 : (sample0 <= DEPTH_MAX))
    (h5 : (sample1 >= (0 : Real)))
    (h6 : (sample1 <= DEPTH_MAX))
    (h7 : (sample2 >= (0 : Real)))
    (h8 : (sample2 <= DEPTH_MAX))
    (h9 : (sample3 >= (0 : Real)))
    (h10 : (sample3 <= DEPTH_MAX))
    (h11 : (bias >= (0 : Real)))
    (h12 : (bias <= BIAS_MAX)) :
    (((pcf_4tap query_depth sample0 sample1 sample2 sample3 bias) >= (0 : Real))) ∧ (((pcf_4tap query_depth sample0 sample1 sample2 sample3 bias) <= ONE)) := by
  unfold pcf_4tap
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover

-- ── pcf_9tap ──

noncomputable def pcf_9tap (query_depth : Real) (s0 : Real) (s1 : Real) (s2 : Real) (s3 : Real) (s4 : Real) (s5 : Real) (s6 : Real) (s7 : Real) (s8 : Real) (bias : Real) : Real :=
  (NINTH * (((((((((step s0 (query_depth - bias)) + (step s1 (query_depth - bias))) + (step s2 (query_depth - bias))) + (step s3 (query_depth - bias))) + (step s4 (query_depth - bias))) + (step s5 (query_depth - bias))) + (step s6 (query_depth - bias))) + (step s7 (query_depth - bias))) + (step s8 (query_depth - bias))))

theorem shadow_pcf9_in_unit_interval (query_depth : Real) (s0 : Real) (s1 : Real) (s2 : Real) (s3 : Real) (s4 : Real) (s5 : Real) (s6 : Real) (s7 : Real) (s8 : Real) (bias : Real)
    (h1 : (query_depth >= (0 : Real)))
    (h2 : (query_depth <= DEPTH_MAX))
    (h3 : (bias >= (0 : Real)))
    (h4 : (bias <= BIAS_MAX)) :
    (((pcf_9tap query_depth s0 s1 s2 s3 s4 s5 s6 s7 s8 bias) >= (0 : Real))) ∧ (((pcf_9tap query_depth s0 s1 s2 s3 s4 s5 s6 s7 s8 bias) <= ONE)) := by
  unfold pcf_9tap
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
