-- Generated by the EML-lang Lean backend
-- Source module: shockley_diode
-- Source file:   <private>/shockley_diode.eml
-- Verified fns:  shockley_current

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def VT_300K : Real := (0.025852 : Real)

axiom shockley_at_room_temp (voltage : Real) (saturation_current : Real) (ideality : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── shockley_current ──

noncomputable def shockley_current (voltage : Real) (saturation_current : Real) (ideality : Real) (thermal_voltage : Real) : Real :=
  (saturation_current * ((Real.exp (voltage / (ideality * thermal_voltage))) - (1 : Real)))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem shockley_current_monotone_in_voltage (voltage : Real) (saturation_current : Real) (ideality : Real) (thermal_voltage : Real)
    (h1 : (saturation_current > (0 : Real)))
    (h2 : (ideality >= (1 : Real)))
    (h3 : (ideality <= (2.0 : Real)))
    (h4 : (thermal_voltage > (0 : Real))) :
    True := by
  trivial
