-- Generated by the EML-lang Lean backend
-- Source module: sigmoid
-- Source file:   <private>/sigmoid.eml
-- Verified fns:  sigmoid, sigmoid_alt

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def SIGMOID_X_MAX : Real := (30.0 : Real)
noncomputable def HALF : Real := (0.5 : Real)

axiom logit (p : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── sigmoid ──

noncomputable def sigmoid (x : Real) : Real :=
  ((1 : Real) / ((1 : Real) + (Real.exp (-x))))

theorem sigmoid_monotone_in_x (x : Real)
    (h1 : ((abs x) < SIGMOID_X_MAX)) :
    (((sigmoid x) >= (0 : Real))) ∧ (((sigmoid x) <= (1 : Real))) := by
  unfold sigmoid
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover

-- ── sigmoid_alt ──

noncomputable def sigmoid_alt (x : Real) : Real :=
  (((Real.tanh (x * HALF)) * HALF) + HALF)

theorem sigmoid_alt_equals_canonical (x : Real)
    (h1 : ((abs x) < SIGMOID_X_MAX)) :
    (((sigmoid_alt x) >= (0 : Real))) ∧ (((sigmoid_alt x) <= (1 : Real))) := by
  unfold sigmoid_alt
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
