-- Generated by the EML-lang Lean backend
-- Source module: stark
-- Source file:   <private>/stark.eml
-- Verified fns:  fri_fold_step, verify_byte

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def FIELD_BITS : Int := 64
noncomputable def FRI_ROUNDS : Int := 80

axiom fri_fold (coeff_even : Real) (coeff_odd : Real) (challenge : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

axiom verify_stark_byte (proof : Real) (public_input : Real) : Real  -- extern (axiomatised in MachLib/Discovered)

-- ── fri_fold_step ──

noncomputable def fri_fold_step (coeff_even : Real) (coeff_odd : Real) (challenge : Real) : Real :=
  (fri_fold coeff_even coeff_odd challenge)

theorem fri_round_correct (coeff_even : Real) (coeff_odd : Real) (challenge : Real)
    (h1 : True) :
    True := by
  trivial

-- ── verify_byte ──

noncomputable def verify_byte (proof_byte : Real) (public_input_byte : Real) : Real :=
  (verify_stark_byte proof_byte public_input_byte)

theorem stark_verify_correct (proof_byte : Real) (public_input_byte : Real)
    (h1 : True) :
    True := by
  trivial
