-- Generated by the EML-lang Lean backend
-- Source module: substrate_field_line
-- Source file:   <private>/substrate_field_line.eml
-- Verified fns:  field_line_field

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ONE : Real := (1 : Real)
noncomputable def HALF : Real := (0.5 : Real)
noncomputable def RING_SCALE : Real := (0.4 : Real)
noncomputable def TIME_RATE : Real := (1.5 : Real)
noncomputable def EPSILON : Real := (0.02 : Real)

-- ── field_line_field ──

noncomputable def field_line_field (u : Real) (v : Real) (t : Real) (proximity : Real) : Real :=
  (min (max ((((Real.sin ((((ONE / (Real.sqrt ((((u - HALF) * (u - HALF)) + ((v - HALF) * (v - HALF))) + EPSILON))) + (t * TIME_RATE)) * RING_SCALE) * (ONE / EPSILON))) + ONE) * HALF) * (min (max proximity ZERO) ONE)) ZERO) ONE)

theorem substrate_field_line_field_in_unit_band (u : Real) (v : Real) (t : Real) (proximity : Real) :
    ((field_line_field u v t proximity) >= ZERO) := by
  unfold field_line_field
  sorry  -- TODO: prove against MachLib foundations
