-- Generated by the EML-lang Lean backend
-- Source module: substrate_cellular_mesh
-- Source file:   <private>/substrate_cellular_mesh.eml
-- Verified fns:  cellular_mesh_field

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ONE : Real := (1 : Real)
noncomputable def CELL_RADIUS_1 : Real := (0.3 : Real)
noncomputable def CELL_RADIUS_2 : Real := (0.35 : Real)
noncomputable def CELL_RADIUS_3 : Real := (0.25 : Real)
noncomputable def RATE_1X : Real := (0.13 : Real)
noncomputable def RATE_1Y : Real := (0.17 : Real)
noncomputable def RATE_2X : Real := (0.21 : Real)
noncomputable def RATE_2Y : Real := (0.11 : Real)
noncomputable def RATE_3X : Real := (0.07 : Real)
noncomputable def RATE_3Y : Real := (0.19 : Real)
noncomputable def GLOW_TIGHTNESS : Real := (30.0 : Real)

-- ── cellular_mesh_field ──

noncomputable def cellular_mesh_field (u : Real) (v : Real) (t : Real) (proximity : Real) : Real :=
  (min (max ((((Real.exp (-((((u - ((Real.sin (t * RATE_1X)) * CELL_RADIUS_1)) * (u - ((Real.sin (t * RATE_1X)) * CELL_RADIUS_1))) + ((v - ((Real.cos (t * RATE_1Y)) * CELL_RADIUS_1)) * (v - ((Real.cos (t * RATE_1Y)) * CELL_RADIUS_1)))) * GLOW_TIGHTNESS))) + (Real.exp (-((((u - ((Real.cos (t * RATE_2X)) * CELL_RADIUS_2)) * (u - ((Real.cos (t * RATE_2X)) * CELL_RADIUS_2))) + ((v - ((Real.sin (t * RATE_2Y)) * CELL_RADIUS_2)) * (v - ((Real.sin (t * RATE_2Y)) * CELL_RADIUS_2)))) * GLOW_TIGHTNESS)))) + (Real.exp (-((((u - ((Real.sin (t * RATE_3X)) * CELL_RADIUS_3)) * (u - ((Real.sin (t * RATE_3X)) * CELL_RADIUS_3))) + ((v - ((Real.cos (t * RATE_3Y)) * CELL_RADIUS_3)) * (v - ((Real.cos (t * RATE_3Y)) * CELL_RADIUS_3)))) * GLOW_TIGHTNESS)))) * (min (max proximity ZERO) ONE)) ZERO) ONE)

theorem substrate_cellular_mesh_field_in_unit_band (u : Real) (v : Real) (t : Real) (proximity : Real) :
    ((cellular_mesh_field u v t proximity) >= ZERO) := by
  unfold cellular_mesh_field
  sorry  -- TODO: prove against MachLib foundations
