-- Generated by the EML-lang Lean backend
-- Source module: substrate_parity_split
-- Source file:   <private>/substrate_parity_split.eml
-- Verified fns:  substrate_parity_split_field

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ONE : Real := (1 : Real)
noncomputable def HALF : Real := (0.5 : Real)
noncomputable def ALPHA_1 : Real := (-(0.3 : Real))
noncomputable def ALPHA_2 : Real := (-(0.55 : Real))
noncomputable def BETA : Real := (4.0 : Real)
noncomputable def COEF_F12 : Real := (0.2 : Real)
noncomputable def COEF_F13 : Real := (0.2 : Real)
noncomputable def COEF_F23 : Real := (0.2 : Real)
noncomputable def COEF_G1 : Real := (0.18 : Real)
noncomputable def COEF_G2 : Real := (0.18 : Real)
noncomputable def COEF_G3 : Real := (0.18 : Real)
noncomputable def COEF_G123 : Real := (0.3 : Real)
noncomputable def BLEND_RATE : Real := (0.628 : Real)
noncomputable def F_PART_SCALE : Real := (1.2 : Real)
noncomputable def G_PART_SCALE : Real := (1.2 : Real)

-- ── substrate_parity_split_field ──

noncomputable def substrate_parity_split_field (u : Real) (v : Real) (t : Real) (proximity : Real) : Real :=
  (min (max ((((((Real.cos (BLEND_RATE * t)) + ONE) * HALF) * (min (max (((((ONE + (COEF_F12 * (Real.exp ((ALPHA_1 * u) + (ALPHA_2 * u))))) + (COEF_F13 * (Real.exp ((ALPHA_1 * u) + (BETA * v))))) + (COEF_F23 * (Real.exp ((ALPHA_2 * u) + (BETA * v))))) - ONE) * F_PART_SCALE) ZERO) ONE)) + ((ONE - (((Real.cos (BLEND_RATE * t)) + ONE) * HALF)) * (min (max (((((COEF_G1 * (Real.exp (ALPHA_1 * u))) + (COEF_G2 * (Real.exp (ALPHA_2 * u)))) + (COEF_G3 * (Real.exp (BETA * v)))) + (COEF_G123 * (Real.exp (((ALPHA_1 * u) + (ALPHA_2 * u)) + (BETA * v))))) * G_PART_SCALE) ZERO) ONE))) * (min (max proximity ZERO) ONE)) ZERO) ONE)

theorem substrate_parity_split_field_in_unit_band (u : Real) (v : Real) (t : Real) (proximity : Real) :
    ((substrate_parity_split_field u v t proximity) >= ZERO) := by
  unfold substrate_parity_split_field
  sorry  -- TODO: prove against MachLib foundations
