-- Generated by the EML-lang Lean backend
-- Source module: swish
-- Source file:   <private>/swish.eml
-- Verified fns:  swish, hard_swish

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def SWISH_X_MAX : Real := (30.0 : Real)
noncomputable def HARD_SWISH_DENOM : Real := (6.0 : Real)
noncomputable def HARD_SWISH_OFFSET : Real := (3.0 : Real)

axiom e_swish (x : Real) (beta : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── swish ──

noncomputable def swish (x : Real) : Real :=
  (x / ((1 : Real) + (Real.exp (-x))))

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem swish_smooth_at_zero (x : Real)
    (h1 : ((abs x) < SWISH_X_MAX)) :
    True := by
  trivial

-- ── hard_swish ──

noncomputable def hard_swish (x : Real) : Real :=
  ((x * (min (max (x + HARD_SWISH_OFFSET) (0 : Real)) HARD_SWISH_DENOM)) / HARD_SWISH_DENOM)

-- ⚠ NO OBLIGATION: kernel declares no `ensures` and no return
-- refinement, so this theorem is vacuously `True` (proves only
-- well-typedness). Exclude from any close-rate / verified count.
theorem hard_swish_bounded (x : Real)
    (h1 : ((abs x) < SWISH_X_MAX))
    (h_clamp1 : (0 : Real) ≤ HARD_SWISH_DENOM) :
    True := by
  trivial
