import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: tafel
-- Source file:   <private>/tafel.eml
-- Verified fns:  overpotential_from_current

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def R_GAS : Real := (8.314462618 : Real)
noncomputable def F_FARAD : Real := (96485.33212 : Real)
noncomputable def T_MIN : Real := (200.0 : Real)
noncomputable def T_MAX : Real := (1000.0 : Real)

axiom overpotential_mechanistic (current_density : Real) (exchange_current_density : Real) (alpha : Real) (temperature : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom tafel_slope (alpha : Real) (temperature : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── overpotential_from_current ──

noncomputable def overpotential_from_current (intercept_a : Real) (slope_b : Real) (current_density : Real) : Real :=
  (intercept_a + (slope_b * (log10 current_density)))

theorem tafel_monotone_in_current (intercept_a : Real) (slope_b : Real) (current_density : Real)
    (h1 : (current_density > (0.0 : Real))) :
    True := by
  trivial
