-- Generated by the EML-lang Lean backend
-- Source module: tanh_activation
-- Source file:   <private>/tanh.eml
-- Verified fns:  tanh_activation, tanh_from_sigmoid, hard_tanh

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def TANH_X_MAX : Real := (30.0 : Real)

-- ── tanh_activation ──

noncomputable def tanh_activation (x : Real) : Real :=
  (Real.tanh x)

theorem tanh_monotone_in_x (x : Real)
    (h1 : ((abs x) < TANH_X_MAX)) :
    (((tanh_activation x) >= (-(1 : Real)))) ∧ (((tanh_activation x) <= (1 : Real))) := by
  unfold tanh_activation
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover

-- ── tanh_from_sigmoid ──

noncomputable def tanh_from_sigmoid (x : Real) : Real :=
  (((2.0 : Real) / ((1 : Real) + (Real.exp ((-2.0 : Real) * x)))) - (1 : Real))

theorem tanh_from_sigmoid_equals_canonical (x : Real)
    (h1 : ((abs x) < TANH_X_MAX)) :
    (((tanh_from_sigmoid x) >= (-(1 : Real)))) ∧ (((tanh_from_sigmoid x) <= (1 : Real))) := by
  unfold tanh_from_sigmoid
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover

-- ── hard_tanh ──

noncomputable def hard_tanh (x : Real) : Real :=
  (min (max x (-1.0 : Real)) (1 : Real))

theorem hard_tanh_bounded (x : Real)
    (h_clamp1 : (-1.0 : Real) ≤ (1 : Real)) :
    (((hard_tanh x) >= (-(1 : Real)))) ∧ (((hard_tanh x) <= (1 : Real))) := by
  unfold hard_tanh
  refine ⟨?_, ?_⟩ <;>
    first
    | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
    | apply clamp_le_hi
    | mach_positivity
    | mach_sign
    | (apply convex_comb_le <;> assumption)
    | (apply convex_comb_ge <;> assumption)
    | (apply convex_comb3_le <;> assumption)
    | (apply convex_comb3_ge <;> assumption)
    | (apply convex_comb4_le <;> assumption)
    | (apply convex_comb4_ge <;> assumption)
    | (apply convex_comb5_le <;> assumption)
    | (apply convex_comb5_ge <;> assumption)
    | (apply convex_comb6_le <;> assumption)
    | (apply convex_comb6_ge <;> assumption)
    | rfl
    | sorry  -- out of reach; left for the prover
