-- Generated by the EML-lang Lean backend
-- Source module: tool_wear_taylor
-- Source file:   <private>/tool_wear_taylor.eml
-- Verified fns:  tool_life_minutes, max_cutting_speed, extended_tool_life

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def V_MIN : Real := (1 : Real)
noncomputable def V_MAX : Real := (5000.0 : Real)
noncomputable def T_MIN : Real := (0.01 : Real)
noncomputable def T_MAX : Real := (10000.0 : Real)
noncomputable def N_MIN : Real := (0.05 : Real)
noncomputable def N_MAX : Real := (1 : Real)
noncomputable def C_MIN : Real := (1 : Real)
noncomputable def C_MAX : Real := (100000.0 : Real)

-- ── tool_life_minutes ──

noncomputable def tool_life_minutes (cutting_speed : Real) (taylor_n : Real) (taylor_c : Real) : Real :=
  ((taylor_c / cutting_speed) ^ ((1 : Real) / taylor_n))

-- source obligations for tool_life_minutes: {O1}
--   O1 [5e6747126a45] -> PRESERVED (accounted)  theorem tool_life_decreases_with_speed
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem tool_life_decreases_with_speed (cutting_speed : Real) (taylor_n : Real) (taylor_c : Real)
    (h_cutting_speed : ((V_MIN <= cutting_speed) ∧ (cutting_speed <= V_MAX)))
    (h_taylor_n : ((N_MIN <= taylor_n) ∧ (taylor_n <= N_MAX)))
    (h_taylor_c : ((C_MIN <= taylor_c) ∧ (taylor_c <= C_MAX))) :
    ((tool_life_minutes cutting_speed taylor_n taylor_c) >= (0 : Real)) := by
  unfold tool_life_minutes
  try unfold V_MIN at *
  try unfold V_MAX at *
  try unfold T_MIN at *
  try unfold T_MAX at *
  try unfold N_MIN at *
  try unfold N_MAX at *
  try unfold C_MIN at *
  try unfold C_MAX at *
  try mach_split_hyps
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── max_cutting_speed ──

noncomputable def max_cutting_speed (target_life_minutes : Real) (taylor_n : Real) (taylor_c : Real) : Real :=
  (taylor_c / (target_life_minutes ^ taylor_n))

-- source obligations for max_cutting_speed: {O1}
--   O1 [0a191079968c] -> PRESERVED (accounted)  theorem max_speed_decreases_with_target_life
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem max_speed_decreases_with_target_life (target_life_minutes : Real) (taylor_n : Real) (taylor_c : Real)
    (h_target_life_minutes : ((T_MIN <= target_life_minutes) ∧ (target_life_minutes <= T_MAX)))
    (h_taylor_n : ((N_MIN <= taylor_n) ∧ (taylor_n <= N_MAX)))
    (h_taylor_c : ((C_MIN <= taylor_c) ∧ (taylor_c <= C_MAX))) :
    ((max_cutting_speed target_life_minutes taylor_n taylor_c) >= (0 : Real)) := by
  unfold max_cutting_speed
  try unfold V_MIN at *
  try unfold V_MAX at *
  try unfold T_MIN at *
  try unfold T_MAX at *
  try unfold N_MIN at *
  try unfold N_MAX at *
  try unfold C_MIN at *
  try unfold C_MAX at *
  try mach_split_hyps
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover

-- ── extended_tool_life ──

noncomputable def extended_tool_life (cutting_speed : Real) (feed_rate : Real) (depth_of_cut : Real) (taylor_n : Real) (feed_exponent : Real) (depth_exponent : Real) (taylor_c : Real) : Real :=
  ((taylor_c / ((cutting_speed * (feed_rate ^ feed_exponent)) * (depth_of_cut ^ depth_exponent))) ^ ((1 : Real) / taylor_n))

-- source obligations for extended_tool_life: {O1}
--   O1 [2c646d0c0436] -> PRESERVED (accounted)  theorem extended_taylor_consistent_with_classical
--        build: unconditional -- the theorem STATEMENT is in the artifact unconditionally; whether it is PROVED is a separate axis -- this checker rejects an undischarged theorem unless cheating is explicitly enabled
theorem extended_taylor_consistent_with_classical (cutting_speed : Real) (feed_rate : Real) (depth_of_cut : Real) (taylor_n : Real) (feed_exponent : Real) (depth_exponent : Real) (taylor_c : Real)
    (h_cutting_speed : ((V_MIN <= cutting_speed) ∧ (cutting_speed <= V_MAX)))
    (h_feed_rate : (((0.001 : Real) <= feed_rate) ∧ (feed_rate <= (1 : Real))))
    (h_depth_of_cut : (((0.001 : Real) <= depth_of_cut) ∧ (depth_of_cut <= (100.0 : Real))))
    (h_taylor_n : ((N_MIN <= taylor_n) ∧ (taylor_n <= N_MAX)))
    (h_feed_exponent : (((0 : Real) <= feed_exponent) ∧ (feed_exponent <= (1 : Real))))
    (h_depth_exponent : (((0 : Real) <= depth_exponent) ∧ (depth_exponent <= (1 : Real))))
    (h_taylor_c : ((C_MIN <= taylor_c) ∧ (taylor_c <= C_MAX))) :
    ((extended_tool_life cutting_speed feed_rate depth_of_cut taylor_n feed_exponent depth_exponent taylor_c) >= (0 : Real)) := by
  unfold extended_tool_life
  try unfold V_MIN at *
  try unfold V_MAX at *
  try unfold T_MIN at *
  try unfold T_MAX at *
  try unfold N_MIN at *
  try unfold N_MAX at *
  try unfold C_MIN at *
  try unfold C_MAX at *
  try mach_split_hyps
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
