-- Generated by the EML-lang Lean backend
-- Source module: torque_vectoring
-- Source file:   <private>/torque_vectoring.eml
-- Verified fns:  left_wheel_torque, right_wheel_torque, yaw_moment_from_split

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def TORQUE_MAX : Real := (10000.0 : Real)
noncomputable def TRACK_MIN : Real := (1 : Real)
noncomputable def TRACK_MAX : Real := (3.0 : Real)
noncomputable def RADIUS_MIN : Real := (0.2 : Real)
noncomputable def RADIUS_MAX : Real := (0.5 : Real)
noncomputable def YAW_MOMENT_MAX : Real := (5000.0 : Real)

-- ── left_wheel_torque ──

noncomputable def left_wheel_torque (total_drive_torque : Real) (desired_yaw_moment : Real) (track_width : Real) (rolling_radius : Real) : Real :=
  (min (max (((0.5 : Real) * total_drive_torque) - ((desired_yaw_moment * rolling_radius) / track_width)) (-TORQUE_MAX)) TORQUE_MAX)

theorem left_torque_within_limit (total_drive_torque : Real) (desired_yaw_moment : Real) (track_width : Real) (rolling_radius : Real)
    (h1 : ((abs total_drive_torque) <= TORQUE_MAX))
    (h2 : ((abs desired_yaw_moment) <= YAW_MOMENT_MAX))
    (h3 : (track_width >= TRACK_MIN))
    (h4 : (track_width <= TRACK_MAX))
    (h5 : (rolling_radius >= RADIUS_MIN))
    (h6 : (rolling_radius <= RADIUS_MAX)) :
    True := by
  trivial

-- ── right_wheel_torque ──

noncomputable def right_wheel_torque (total_drive_torque : Real) (desired_yaw_moment : Real) (track_width : Real) (rolling_radius : Real) : Real :=
  (min (max (((0.5 : Real) * total_drive_torque) + ((desired_yaw_moment * rolling_radius) / track_width)) (-TORQUE_MAX)) TORQUE_MAX)

theorem right_torque_complements_left (total_drive_torque : Real) (desired_yaw_moment : Real) (track_width : Real) (rolling_radius : Real)
    (h1 : ((abs total_drive_torque) <= TORQUE_MAX))
    (h2 : ((abs desired_yaw_moment) <= YAW_MOMENT_MAX))
    (h3 : (track_width >= TRACK_MIN))
    (h4 : (track_width <= TRACK_MAX))
    (h5 : (rolling_radius >= RADIUS_MIN))
    (h6 : (rolling_radius <= RADIUS_MAX)) :
    True := by
  trivial

-- ── yaw_moment_from_split ──

noncomputable def yaw_moment_from_split (left_torque : Real) (right_torque : Real) (track_width : Real) (rolling_radius : Real) : Real :=
  (((right_torque - left_torque) * track_width) / ((2.0 : Real) * rolling_radius))

theorem yaw_moment_zero_at_balanced_split (left_torque : Real) (right_torque : Real) (track_width : Real) (rolling_radius : Real)
    (h1 : ((abs left_torque) <= TORQUE_MAX))
    (h2 : ((abs right_torque) <= TORQUE_MAX))
    (h3 : (track_width >= TRACK_MIN))
    (h4 : (track_width <= TRACK_MAX))
    (h5 : (rolling_radius >= RADIUS_MIN))
    (h6 : (rolling_radius <= RADIUS_MAX)) :
    True := by
  trivial
