-- Generated by the EML-lang Lean backend
-- Source module: unsharp_mask
-- Source file:   <private>/unsharp_mask.eml
-- Verified fns:  unsharp_linear, unsharp_detail, unsharp_threshold_blend

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def ZERO : Real := (0 : Real)
noncomputable def ONE : Real := (1 : Real)
noncomputable def PIXEL_MIN : Real := (0 : Real)
noncomputable def PIXEL_MAX : Real := (1 : Real)
noncomputable def AMOUNT_MAX : Real := (5.0 : Real)
noncomputable def THRESHOLD_MAX : Real := (1 : Real)

-- ── unsharp_linear ──

noncomputable def unsharp_linear (pixel : Real) (blurred : Real) (amount : Real) : Real :=
  (pixel + (amount * (pixel - blurred)))

theorem unsharp_linear_zero_amount_is_passthrough (pixel : Real) (blurred : Real) (amount : Real)
    (h1 : (pixel >= PIXEL_MIN))
    (h2 : (pixel <= PIXEL_MAX))
    (h3 : (blurred >= PIXEL_MIN))
    (h4 : (blurred <= PIXEL_MAX))
    (h5 : (amount >= ZERO))
    (h6 : (amount <= AMOUNT_MAX)) :
    True := by
  trivial

-- ── unsharp_detail ──

noncomputable def unsharp_detail (pixel : Real) (blurred : Real) : Real :=
  (pixel - blurred)

theorem unsharp_detail_zero_when_pixel_eq_blurred (pixel : Real) (blurred : Real)
    (h1 : (pixel >= PIXEL_MIN))
    (h2 : (pixel <= PIXEL_MAX))
    (h3 : (blurred >= PIXEL_MIN))
    (h4 : (blurred <= PIXEL_MAX)) :
    True := by
  trivial

-- ── unsharp_threshold_blend ──

noncomputable def unsharp_threshold_blend (pixel : Real) (blurred : Real) (amount : Real) (gate : Real) : Real :=
  (pixel + ((gate * amount) * (pixel - blurred)))

theorem unsharp_threshold_passthrough_when_gate_zero (pixel : Real) (blurred : Real) (amount : Real) (gate : Real)
    (h1 : (pixel >= PIXEL_MIN))
    (h2 : (pixel <= PIXEL_MAX))
    (h3 : (blurred >= PIXEL_MIN))
    (h4 : (blurred <= PIXEL_MAX))
    (h5 : (amount >= ZERO))
    (h6 : (amount <= AMOUNT_MAX))
    (h7 : (gate >= ZERO))
    (h8 : (gate <= ONE)) :
    True := by
  trivial
