-- Generated by the EML-lang Lean backend
-- Source module: vant_hoff
-- Source file:   <private>/vant_hoff.eml
-- Verified fns:  predict_k

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def R_GAS : Real := (8.314462618 : Real)
noncomputable def T_MIN : Real := (200.0 : Real)
noncomputable def T_MAX : Real := (2000.0 : Real)
noncomputable def DH_MAX : Real := (1000000.0 : Real)

axiom ln_k_at_inverse_t (intercept : Real) (slope : Real) (inverse_t : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── predict_k ──

noncomputable def predict_k (k1 : Real) (delta_h : Real) (t1 : Real) (t2 : Real) : Real :=
  (k1 * (Real.exp ((delta_h / R_GAS) * (((1 : Real) / t1) - ((1 : Real) / t2)))))

theorem vant_hoff_predict_k (k1 : Real) (delta_h : Real) (t1 : Real) (t2 : Real)
    (h1 : (k1 > (0 : Real)))
    (h2 : (delta_h >= (-DH_MAX)))
    (h3 : (delta_h <= DH_MAX))
    (h4 : (t1 >= T_MIN))
    (h5 : (t1 <= T_MAX))
    (h6 : (t2 >= T_MIN))
    (h7 : (t2 <= T_MAX)) :
    ((predict_k k1 delta_h t1 t2) > (0 : Real)) := by
  unfold predict_k
  sorry  -- TODO: prove against MachLib foundations
