import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: vega
-- Source file:   <private>/vega.eml
-- Verified fns:  bs_vega

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def HALF : Real := (0.5 : Real)
noncomputable def SQRT_2_PI_INV : Real := (0.3989422804014327 : Real)
noncomputable def TINY_T : Real := (0.000274 : Real)

axiom norm_pdf (x : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom d1 (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── bs_vega ──

noncomputable def bs_vega (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real) : Real :=
  ((spot * (SQRT_2_PI_INV * (Real.exp (((-HALF) * (d1 spot strike rate vol time_to_expiry)) * (d1 spot strike rate vol time_to_expiry))))) * (Real.sqrt time_to_expiry))

theorem bs_vega_non_negative (spot : Real) (strike : Real) (rate : Real) (vol : Real) (time_to_expiry : Real)
    (h1 : (spot > (0.0 : Real)))
    (h2 : (strike > (0.0 : Real)))
    (h3 : (vol > (0.0 : Real)))
    (h4 : (time_to_expiry > TINY_T)) :
    ((bs_vega spot strike rate vol time_to_expiry) >= (0.0 : Real)) := by
  unfold bs_vega
  sorry  -- TODO: prove against MachLib foundations
