-- Generated by the EML-lang Lean backend
-- Source module: voigt
-- Source file:   <private>/voigt.eml
-- Verified fns:  pseudo_voigt

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def PI : Real := (3.141592653589793 : Real)
noncomputable def SQRT_2PI : Real := (2.5066282746310002 : Real)

axiom voigt_eta (fwhm_lorentzian : Real) (fwhm_combined : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── pseudo_voigt ──

noncomputable def pseudo_voigt (frequency : Real) (centre : Real) (fwhm_combined : Real) (eta : Real) : Real :=
  ((eta * (((0.5 : Real) * fwhm_combined) / (PI * (((frequency - centre) * (frequency - centre)) + (((0.5 : Real) * fwhm_combined) * ((0.5 : Real) * fwhm_combined)))))) + (((1 : Real) - eta) * ((Real.exp (((-(frequency - centre)) * (frequency - centre)) / (((2.0 : Real) * (fwhm_combined / (2.3548200450309493 : Real))) * (fwhm_combined / (2.3548200450309493 : Real))))) / ((fwhm_combined / (2.3548200450309493 : Real)) * SQRT_2PI))))

theorem voigt_peak_at_centre (frequency : Real) (centre : Real) (fwhm_combined : Real) (eta : Real)
    (h1 : (fwhm_combined > (0 : Real)))
    (h2 : (eta >= (0 : Real)))
    (h3 : (eta <= (1 : Real))) :
    ((pseudo_voigt frequency centre fwhm_combined eta) >= (0 : Real)) := by
  unfold pseudo_voigt
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
