-- Generated by the EML-lang Lean backend
-- Source module: vpd_control
-- Source file:   <private>/vpd_control.eml
-- Verified fns:  vpd_safe

import MachLib.EML
import MachLib.Trig
import MachLib.Forge
import MachLib.Linarith
import MachLib.FixedPoint
import MachLib.SignTactic

open MachLib
open MachLib.Real

noncomputable def TETENS_A : Real := (17.27 : Real)
noncomputable def TETENS_B : Real := (237.3 : Real)
noncomputable def TETENS_REF : Real := (0.6108 : Real)
noncomputable def T_MIN_C : Real := (0 : Real)
noncomputable def T_MAX_C : Real := (60.0 : Real)

axiom saturation_vp (temp_c : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

axiom vpd (temp_c : Real) (humidity_pct : Real) : Real  -- helper (axiomatised in MachLib/Discovered)

-- ── vpd_safe ──

noncomputable def vpd_safe (temp_c : Real) (humidity_pct : Real) : Real :=
  ((TETENS_REF * (Real.exp ((TETENS_A * temp_c) / (TETENS_B + temp_c)))) * ((1 : Real) - (humidity_pct / (100.0 : Real))))

theorem vpd_positive (temp_c : Real) (humidity_pct : Real)
    (h1 : (temp_c >= T_MIN_C))
    (h2 : (temp_c <= T_MAX_C))
    (h3 : (humidity_pct > (0 : Real)))
    (h4 : (humidity_pct < (100.0 : Real))) :
    ((vpd_safe temp_c humidity_pct) > (0 : Real)) := by
  unfold vpd_safe
  first
  | (apply lo_le_clamp <;> (first | assumption | mach_positivity))
  | apply clamp_le_hi
  | mach_positivity
  | mach_sign
  | (apply convex_comb_le <;> assumption)
  | (apply convex_comb_ge <;> assumption)
  | (apply convex_comb3_le <;> assumption)
  | (apply convex_comb3_ge <;> assumption)
  | (apply convex_comb4_le <;> assumption)
  | (apply convex_comb4_ge <;> assumption)
  | (apply convex_comb5_le <;> assumption)
  | (apply convex_comb5_ge <;> assumption)
  | (apply convex_comb6_le <;> assumption)
  | (apply convex_comb6_ge <;> assumption)
  | rfl
  | sorry  -- out of reach; left for the prover
