import MachLib.Basic
-- Generated by the EML-lang Lean backend
-- Source module: waypoint_steering
-- Source file:   <private>/waypoint_steering.eml
-- Verified fns:  eta_angle, l1_lateral_accel, cross_track_distance

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def RANGE_MAX : Real := (100000.0 : Real)
noncomputable def SPEED_MAX : Real := (300.0 : Real)
noncomputable def L1_MIN : Real := (5.0 : Real)
noncomputable def L1_MAX : Real := (5000.0 : Real)
noncomputable def ETA_MAX : Real := (1.5708 : Real)
noncomputable def LAT_ACCEL_MAX : Real := (100.0 : Real)

-- ── eta_angle ──

noncomputable def eta_angle (cross_track : Real) (along_track : Real) (heading : Real) : Real :=
  ((atan2 cross_track along_track) - heading)

theorem eta_zero_when_aligned (cross_track : Real) (along_track : Real) (heading : Real)
    (h1 : ((abs cross_track) <= RANGE_MAX))
    (h2 : ((abs along_track) <= RANGE_MAX))
    (h3 : ((abs heading) <= (6.2832 : Real))) :
    True := by
  trivial

-- ── l1_lateral_accel ──

noncomputable def l1_lateral_accel (speed : Real) (eta : Real) (l1_distance : Real) : Real :=
  (((((2.0 : Real) * speed) * speed) * (Real.sin eta)) / l1_distance)

theorem l1_lateral_accel_zero_at_eta_zero (speed : Real) (eta : Real) (l1_distance : Real)
    (h1 : (speed >= (0.0 : Real)))
    (h2 : (speed <= SPEED_MAX))
    (h3 : ((abs eta) <= ETA_MAX))
    (h4 : (l1_distance >= L1_MIN))
    (h5 : (l1_distance <= L1_MAX)) :
    True := by
  trivial

-- ── cross_track_distance ──

noncomputable def cross_track_distance (px : Real) (py : Real) (x1 : Real) (y1 : Real) (x2 : Real) (y2 : Real) : Real :=
  ((((px - x1) * (y2 - y1)) - ((py - y1) * (x2 - x1))) / (min (max (Real.sqrt (((x2 - x1) * (x2 - x1)) + ((y2 - y1) * (y2 - y1)))) (1e-06 : Real)) ((2.0 : Real) * RANGE_MAX)))

theorem cross_track_zero_on_line (px : Real) (py : Real) (x1 : Real) (y1 : Real) (x2 : Real) (y2 : Real)
    (h1 : ((abs px) <= RANGE_MAX))
    (h2 : ((abs py) <= RANGE_MAX))
    (h3 : ((abs x1) <= RANGE_MAX))
    (h4 : ((abs y1) <= RANGE_MAX))
    (h5 : ((abs x2) <= RANGE_MAX))
    (h6 : ((abs y2) <= RANGE_MAX)) :
    True := by
  trivial
