#!/usr/bin/env python3
"""Generate AXIOM_MANIFEST.md — the trusted base as one readable page.

GENERATED, never hand-edited: the point of the manifest is that a reviewer can read the whole
trusted base, and a hand-maintained list drifts from the thing it describes exactly the way the
witness project's pinned footprint did (78 names against a live 149, undetected for 33 days).
Regenerate with:  python3 tools/gen_axiom_manifest.py
"""
import re, pathlib, subprocess, datetime, sys
HERE = pathlib.Path(__file__).resolve().parent.parent
BRIDGE = HERE.parent.parent / "monogate-lean" / "MonogateEML" / "AxiomWitnessBridge.lean"

def strip_comments(s):
    """Strip Lean comments, but NOT inside string literals.

    A naive version treats `--` as a line comment even inside a `"..."` reason string, which
    truncates the entry at that point and silently loses everything after it. That is exactly
    how a gap entry reading "cheaper than it looks -- do this one first" came back UNACCOUNTED
    while gate 13 (which only needs the NAME, before the dashes) reported it fine.
    """
    out, i, depth, instr = [], 0, 0, False
    while i < len(s):
        c = s[i]
        if instr:
            out.append(c)
            if c == '\\' and i + 1 < len(s): out.append(s[i+1]); i += 2; continue
            if c == '"': instr = False
            i += 1; continue
        if not depth and c == '"':
            instr = True; out.append(c); i += 1; continue
        if s.startswith('/-', i): depth += 1; i += 2; continue
        if s.startswith('-/', i) and depth: depth -= 1; i += 2; continue
        if depth: i += 1; continue
        if s.startswith('--', i):
            j = s.find('\n', i); i = len(s) if j < 0 else j; continue
        out.append(c); i += 1
    return ''.join(out)
def span(s,pat):
    m=re.search(pat,s)
    if not m: return ""
    i=s.index('[',m.end()); d=0;j=i
    while j<len(s):
        if s[j]=='[':d+=1
        elif s[j]==']':
            d-=1
            if d==0:break
        j+=1
    return strip_comments(s[i:j+1])

led = (HERE/"AxiomLedger.lean").read_text(); br = BRIDGE.read_text()
trusted = re.findall(r'`([A-Za-z_][\w.]*)', span(led, r'def trustedFootprint\s*:\s*List Name\s*:=\s*'))
# NOTE the `[,\]]` alternative: the LAST registry entry ends `)) ]`, not `)),`. Requiring the
# comma silently dropped it and the manifest reported one spurious UNACCOUNTED axiom while
# gate 13 reported none -- two of our own measurements disagreeing, which is how it was caught.
wit = dict(re.findall(r'\(\s*`([A-Za-z_][\w.]*)\s*,\s*Unhygienic\.run\s*`\((.*?)\)\)\s*[,\]]',
                      span(br, r'def witnessRegistry\s*:\s*List \(Name × TSyntax `term\)\s*:=\s*'), re.S))
gap = dict(re.findall(r'\(\s*`([A-Za-z_][\w.]*)\s*,\s*"(.*?)"\s*\)',
                      span(br, r'def witnessGap\s*:\s*List \(Name × String\)\s*:=\s*'), re.S))
bridge = set(re.findall(r'`([A-Za-z_][\w.]*)', span(br, r'def bridgeAxioms\s*:\s*List Name\s*:=\s*')))
standard = set(re.findall(r'`([A-Za-z_][\w.]*)', span(br, r'def standardAxioms\s*:\s*List Name\s*:=\s*')))
mapped = set(re.findall(r'`([A-Za-z_][\w.]*)', span(br, r'def mappedConstants\s*:\s*List Name\s*:=\s*')))

# statement text for each axiom, straight from source
stmts = {}
for f in sorted((HERE/"MachLib").glob("*.lean")) + [HERE/"Certcom.lean"]:
    if not f.exists(): continue
    txt = f.read_text()
    for m in re.finditer(r'^axiom\s+([A-Za-z_][\w]*)\s*(.*?)(?=\n\S|\n\n)', txt, re.M|re.S):
        stmts.setdefault(m.group(1), ' '.join(m.group(2).split())[:150])

def row(a):
    short = a.split('.')[-1]
    st = stmts.get(short, "")
    if a in standard:  cls, note = "standard", "Lean kernel axiom — sound by construction"
    elif a in mapped:  cls, note = "mapped", "carrier / function symbol, interpreted not witnessed"
    elif a in bridge:  cls, note = "float-bridge", "claim about IEEE float, NOT modelable in ℝ — validated by measurement"
    elif a in gap:     cls, note = "GAP", ' '.join(gap[a].replace('\\','').split())
    elif a in wit:     cls, note = "witnessed", ' '.join(wit[a].split())
    else:              cls, note = "**UNACCOUNTED**", "no witness, no classification — gate 13 fails on this"
    return f"| `{a}` | {cls} | `{st}` | {note} |"

counts = {}
for a in trusted:
    k = ("standard" if a in standard else "mapped" if a in mapped else "float-bridge" if a in bridge
         else "GAP" if a in gap else "witnessed" if a in wit else "UNACCOUNTED")
    counts[k] = counts.get(k, 0) + 1

out = [f"""# MachLib trusted base — the axiom manifest

**GENERATED by `tools/gen_axiom_manifest.py`. Do not hand-edit.**

MachLib is Mathlib-free by construction, so nothing inside it can show its axioms are
satisfiable. That is done in a *separate* project (`monogate-lean`) which imports both Mathlib
and MachLib and, for each axiom, checks that a Mathlib term inhabits the axiom's **interpreted
type** (`MachLib.Real ↦ ℝ`, `exp ↦ Real.exp`, …). The witness is a certificate *about* MachLib,
never a dependency *of* it.

The honest headline is **"zero unmodeled axioms"**, not "zero axioms". There are
{len(trusted)} of them and they are all listed below.

| class | count | meaning |
|---|---|---|
| witnessed | {counts.get('witnessed',0)} | a Mathlib term inhabits the interpreted axiom type, kernel-checked |
| mapped | {counts.get('mapped',0)} | carrier or function symbol — interpreted, not a proposition |
| standard | {counts.get('standard',0)} | `propext`, `Classical.choice`, `Quot.sound` |
| float-bridge | {counts.get('float-bridge',0)} | about IEEE floats, **not modelable in `ℝ`** — empirical; see the note below on what is and is not pinned |
| GAP | {counts.get('GAP',0)} | witnessable, not yet witnessed — reason given per row |
| **UNACCOUNTED** | {counts.get('UNACCOUNTED',0)} | must be 0; gate 13 fails otherwise |

**The float-bridge rows are a different kind of trust and are deliberately not averaged in.**
No Mathlib witness can discharge "the machine `atan` rounds to within ε of `Real.arctan`" —
Mathlib has no IEEE-754 semantics. Those {counts.get('float-bridge',0)} axioms are what a hardware
certificate actually rests on, so anyone reading an atan/tan bench certificate should read that
block first.

**And read this before reading them.** These rows are not one kind of thing, and the difference
decides what a certificate can claim.

* **The `real_<f>_eps` constants are UNCONSTRAINED.** Each is an `axiom` of type `MachLib.Real`
  with nothing said about it — not `0 ≤ eps`, not a relation to the unit roundoff `u`. So a
  grounded theorem such as `Certcom.pid_sin_grounded` concludes *"within `real_sin_eps + absErr`"*,
  which holds for any sufficiently large constant. **Its content is UNIFORMITY — one constant
  works for every `Float` — and not accuracy.** The uniformity is real and was hard-won: the
  2026-07-22 audit found it FALSE for `exp`/`log`/`sqrt`/`asin`/`acos`/`tan` and repaired those six
  with domain hypotheses, which is why they carry `R`/`lo`/`hi` and the globally-Lipschitz five do
  not. But a reader cannot get a NUMBER out of any of them.
* **The measurement exists and is separate.** The forward-error certifier measures the f64 lane at
  `u = 2⁻⁵³` for the correctly-rounded operations and `4u` (two ulp) for the libm transcendentals,
  over ~1.4M samples, and its own headline finding is that the transcendentals are **not**
  correctly rounded. Note that IEEE-754 *requires* `√` to be correctly rounded and says nothing
  about any transcendental, so `real_sqrt_rounds` is a different grade of claim from
  `real_sin_rounds` even though both sit in this block.
* **`MachLib/LibmBudget.lean` is the join**, added 2026-09-08: an interface (not new axioms, so this
  count does not move) carrying `real_<f>_eps ≤ B`, with `abs` exact at `0` because IEEE-754 `abs`
  clears the sign bit exactly as `FPBridge.neg` already records for negation. Under it the grounded
  kernels restate with a numeric bound. What it does not do — and cannot, `Float` being opaque — is
  establish that the runtime meets any particular `B`. That stays empirical; it is now quantitative
  and in one named place instead of implicit in four unconstrained constants.
* **`tools/float_bridge/measure.py` MEASURES every row here that states something measurable** (since
  2026-09-14; run by `tools/check_all.sh`, local only). Each bound is checked against a 256-bit reference
  over dense, tiny, threshold, large, random and adversarial inputs (results just above a power of two,
  products and reals straddling `DBL_MIN`, sums and products near overflow), with a sample of the runtime's
  floats checked bit for bit against Lean's own evaluation. It found eight rows FALSE as stated:
  `real_tanh_rounds`, `real_fpbridge`, `real_round_bounds`, `real_exp_rounds`, `real_sinh_rounds`,
  `real_cosh_rounds`, `real_log10_rounds` and `real_tan_rounds`. **All eight are restated from the measurement
  and hold now**: finite inputs or results, products and reals kept out of the subnormal range
  (`FPBridgeFinite`), and constants glibc actually meets where it is not correctly rounded (`tanh` and `exp`
  2u, `sinh` and `cosh` 4u, `log10` 3u, `tan` 2u). The grounded theorems that rest on them carry the matching
  hypotheses in their statements. `tools/float_bridge/registry.json` pins every number and keeps each old
  statement as a control that must still fail; the gate fails if a number moves or a row starts failing.
  Read that file, and the axiom's docstring, before relying on a certificate that cites one of them.
* **Six rows conclude that a float is FINITE rather than how close it reads back** (added 2026-09-14, owner-approved):
  `real_fpfinite` (round-to-nearest's overflow rule: finite operands and an exact result at most `DBL_MAX` in
  magnitude give a finite `+`, `−` or `×`), `real_round_finite` (`floatOfR x` is finite for `|x| ≤ DBL_MAX`), and
  `real_exp_finite`, `real_sinh_finite`, `real_cosh_finite` and `real_log_finite` (the runtime primitive of a finite
  float is finite: `exp` at most `709`, `sinh` and `cosh` at most `710` in magnitude, `log` of a positive float). They
  are what lets a grounded certificate's float side conditions be discharged from a bound on its inputs
  (`MachLib/FloatSafeInstances.lean`, `GroundedPIDInstances.lean`, `GroundedEMLInstances.lean`). The harness measured
  each before it was added, with controls that must fail: the first two exactly at the overflow tie `DBL_MAX + 2^970`,
  the primitive rows with their range widened (`exp` to `710`, `sinh` and `cosh` to `711`) only beyond their own bound,
  and `log` at `0 ≤ x` only at zero.
* **Three rows say what a `Float` literal IS** (added 2026-09-14, owner-approved): `float_lit_1_5`, `float_lit_0_4` and
  `float_lit_0_05`, the PID law's gains, each `floatOfR` of its own decimal. They are narrow on purpose. Lean's
  `Float.ofScientific` truncates to 64 bits before it rounds once, so it is not correctly rounded in general; the harness
  measures the generic statement, "every decimal literal is `floatOfR` of its decimal", as a control that must fail, and
  checks each registered literal against Lean's own evaluation in literal syntax and inside `pidRawEML`.
  `u_lt_one` and `u_le_half`, added the same day, are witnessed rows, not float-bridge ones.

| axiom | class | statement | witness / reason |
|---|---|---|---|"""]
for a in sorted(trusted): out.append(row(a))
out.append("")
(HERE/"AXIOM_MANIFEST.md").write_text('\n'.join(out))
print(f"AXIOM_MANIFEST.md: {len(trusted)} axioms — " + ", ".join(f"{k} {v}" for k,v in sorted(counts.items())))
