#!/usr/bin/env python3
"""Generate AXIOM_MANIFEST.md — the trusted base as one readable page.

GENERATED, never hand-edited: the point of the manifest is that a reviewer can read the whole
trusted base, and a hand-maintained list drifts from the thing it describes exactly the way the
witness project's pinned footprint did (78 names against a live 149, undetected for 33 days).
Regenerate with:  python3 tools/gen_axiom_manifest.py
"""
import re, pathlib, subprocess, datetime, sys
HERE = pathlib.Path(__file__).resolve().parent.parent
BRIDGE = HERE.parent.parent / "monogate-lean" / "MonogateEML" / "AxiomWitnessBridge.lean"

def strip_comments(s):
    """Strip Lean comments, but NOT inside string literals.

    A naive version treats `--` as a line comment even inside a `"..."` reason string, which
    truncates the entry at that point and silently loses everything after it. That is exactly
    how a gap entry reading "cheaper than it looks -- do this one first" came back UNACCOUNTED
    while gate 13 (which only needs the NAME, before the dashes) reported it fine.
    """
    out, i, depth, instr = [], 0, 0, False
    while i < len(s):
        c = s[i]
        if instr:
            out.append(c)
            if c == '\\' and i + 1 < len(s): out.append(s[i+1]); i += 2; continue
            if c == '"': instr = False
            i += 1; continue
        if not depth and c == '"':
            instr = True; out.append(c); i += 1; continue
        if s.startswith('/-', i): depth += 1; i += 2; continue
        if s.startswith('-/', i) and depth: depth -= 1; i += 2; continue
        if depth: i += 1; continue
        if s.startswith('--', i):
            j = s.find('\n', i); i = len(s) if j < 0 else j; continue
        out.append(c); i += 1
    return ''.join(out)
def span(s,pat):
    m=re.search(pat,s)
    if not m: return ""
    i=s.index('[',m.end()); d=0;j=i
    while j<len(s):
        if s[j]=='[':d+=1
        elif s[j]==']':
            d-=1
            if d==0:break
        j+=1
    return strip_comments(s[i:j+1])

led = (HERE/"AxiomLedger.lean").read_text(); br = BRIDGE.read_text()
trusted = re.findall(r'`([A-Za-z_][\w.]*)', span(led, r'def trustedFootprint\s*:\s*List Name\s*:=\s*'))
# NOTE the `[,\]]` alternative: the LAST registry entry ends `)) ]`, not `)),`. Requiring the
# comma silently dropped it and the manifest reported one spurious UNACCOUNTED axiom while
# gate 13 reported none -- two of our own measurements disagreeing, which is how it was caught.
wit = dict(re.findall(r'\(\s*`([A-Za-z_][\w.]*)\s*,\s*Unhygienic\.run\s*`\((.*?)\)\)\s*[,\]]',
                      span(br, r'def witnessRegistry\s*:\s*List \(Name × TSyntax `term\)\s*:=\s*'), re.S))
gap = dict(re.findall(r'\(\s*`([A-Za-z_][\w.]*)\s*,\s*"(.*?)"\s*\)',
                      span(br, r'def witnessGap\s*:\s*List \(Name × String\)\s*:=\s*'), re.S))
bridge = set(re.findall(r'`([A-Za-z_][\w.]*)', span(br, r'def bridgeAxioms\s*:\s*List Name\s*:=\s*')))
standard = set(re.findall(r'`([A-Za-z_][\w.]*)', span(br, r'def standardAxioms\s*:\s*List Name\s*:=\s*')))
mapped = set(re.findall(r'`([A-Za-z_][\w.]*)', span(br, r'def mappedConstants\s*:\s*List Name\s*:=\s*')))

# statement text for each axiom, straight from source
stmts = {}
for f in sorted((HERE/"MachLib").glob("*.lean")) + [HERE/"Certcom.lean"]:
    if not f.exists(): continue
    txt = f.read_text()
    for m in re.finditer(r'^axiom\s+([A-Za-z_][\w]*)\s*(.*?)(?=\n\S|\n\n)', txt, re.M|re.S):
        stmts.setdefault(m.group(1), ' '.join(m.group(2).split())[:150])

def row(a):
    short = a.split('.')[-1]
    st = stmts.get(short, "")
    if a in standard:  cls, note = "standard", "Lean kernel axiom — sound by construction"
    elif a in mapped:  cls, note = "mapped", "carrier / function symbol, interpreted not witnessed"
    elif a in bridge:  cls, note = "float-bridge", "claim about IEEE float, NOT modelable in ℝ — validated by measurement"
    elif a in gap:     cls, note = "GAP", ' '.join(gap[a].replace('\\','').split())
    elif a in wit:     cls, note = "witnessed", ' '.join(wit[a].split())
    else:              cls, note = "**UNACCOUNTED**", "no witness, no classification — gate 13 fails on this"
    return f"| `{a}` | {cls} | `{st}` | {note} |"

counts = {}
for a in trusted:
    k = ("standard" if a in standard else "mapped" if a in mapped else "float-bridge" if a in bridge
         else "GAP" if a in gap else "witnessed" if a in wit else "UNACCOUNTED")
    counts[k] = counts.get(k, 0) + 1

out = [f"""# MachLib trusted base — the axiom manifest

**GENERATED by `tools/gen_axiom_manifest.py`. Do not hand-edit.**

MachLib is Mathlib-free by construction, so nothing inside it can show its axioms are
satisfiable. That is done in a *separate* project (`monogate-lean`) which imports both Mathlib
and MachLib and, for each axiom, checks that a Mathlib term inhabits the axiom's **interpreted
type** (`MachLib.Real ↦ ℝ`, `exp ↦ Real.exp`, …). The witness is a certificate *about* MachLib,
never a dependency *of* it.

The honest headline is **"zero unmodeled axioms"**, not "zero axioms". There are
{len(trusted)} of them and they are all listed below.

| class | count | meaning |
|---|---|---|
| witnessed | {counts.get('witnessed',0)} | a Mathlib term inhabits the interpreted axiom type, kernel-checked |
| mapped | {counts.get('mapped',0)} | carrier or function symbol — interpreted, not a proposition |
| standard | {counts.get('standard',0)} | `propext`, `Classical.choice`, `Quot.sound` |
| float-bridge | {counts.get('float-bridge',0)} | about IEEE floats, **not modelable in `ℝ`** — validated by measurement |
| GAP | {counts.get('GAP',0)} | witnessable, not yet witnessed — reason given per row |
| **UNACCOUNTED** | {counts.get('UNACCOUNTED',0)} | must be 0; gate 13 fails otherwise |

**The float-bridge rows are a different kind of trust and are deliberately not averaged in.**
No Mathlib witness can discharge "the machine `atan` rounds to within ε of `Real.arctan`" —
Mathlib has no IEEE-754 semantics. Those {counts.get('float-bridge',0)} axioms are what a hardware
certificate actually rests on, so anyone reading an atan/tan bench certificate should read that
block first.

| axiom | class | statement | witness / reason |
|---|---|---|---|"""]
for a in sorted(trusted): out.append(row(a))
out.append("")
(HERE/"AXIOM_MANIFEST.md").write_text('\n'.join(out))
print(f"AXIOM_MANIFEST.md: {len(trusted)} axioms — " + ", ".join(f"{k} {v}" for k,v in sorted(counts.items())))
