-- Generated by the EML-lang Lean backend, then sorry-closed by hand
-- against MachLib.Forge.
-- Source module: maglev_driver
-- Source file:   forge/examples/maglev/driver.eml
-- Verified fns:  current_at_zero_drive, r_total_proof,
--                force_at_zero_current, lr_product
--
-- Phase E5 of the math-to-manufactured-PCB pipeline. All four
-- coil-driver obligations close.

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def L_COIL_HENRY : Real := (5e-3 : Real)
noncomputable def R_COIL_OHMS : Real := (2.0 : Real)
noncomputable def R_SENSE_OHMS : Real := (0.1 : Real)
noncomputable def FORCE_K : Real := (0.18 : Real)

axiom circuit  : Real
axiom coil_current_steady (v : Real) (r_total : Real) : Real
axiom coil_tau (l : Real) (r_total : Real) : Real
axiom coil_force_proxy (i : Real) : Real

-- ── current_at_zero_drive ──
-- 0 / r_total = 0 (with r_total ≠ 0 from h1)

noncomputable def current_at_zero_drive (r_total : Real) : Real :=
  ((0 : Real) / r_total)

theorem driver_zero_drive_zero_current (r_total : Real)
    (h1 : (r_total > (0 : Real))) :
    ((current_at_zero_drive r_total) = (0 : Real)) := by
  unfold current_at_zero_drive
  have hne : r_total ≠ 0 := ne_of_gt h1
  rw [div_def 0 r_total hne]
  exact zero_mul (1 / r_total)

-- ── r_total_proof ──

noncomputable def r_total_proof (r_coil : Real) (r_sense : Real) : Real :=
  (r_coil + r_sense)

theorem driver_total_resistance_positive (r_coil : Real) (r_sense : Real)
    (h1 : (r_coil > (0 : Real)))
    (h2 : (r_sense > (0 : Real))) :
    ((r_total_proof r_coil r_sense) > (0 : Real)) := by
  unfold r_total_proof
  exact add_pos h1 h2

-- ── force_at_zero_current ──
-- The EML constant folder already reduced `FORCE_K * (0.0 * 0.0)` to (0 : Real).

noncomputable def force_at_zero_current  : Real :=
  (0 : Real)

theorem driver_zero_current_zero_force  :
    ((force_at_zero_current ) = (0 : Real)) := by
  unfold force_at_zero_current
  rfl

-- ── lr_product ──

noncomputable def lr_product (l : Real) (r_total : Real) : Real :=
  (l * r_total)

theorem driver_lr_product_positive (l : Real) (r_total : Real)
    (h1 : (l > (0 : Real)))
    (h2 : (r_total > (0 : Real))) :
    ((lr_product l r_total) > (0 : Real)) := by
  unfold lr_product
  exact mul_pos h1 h2
