-- Generated by the EML-lang Lean backend, then sorry-closed by hand
-- against MachLib.Forge.
-- Source module: maglev_power
-- Source file:   forge/examples/maglev/power.eml
-- Verified fns:  current_at_zero_supply, bulk_tau_proof
--
-- Phase E5 of the math-to-manufactured-PCB pipeline. Both
-- power-rail obligations close.

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def V_SUPPLY : Real := (12.0 : Real)
noncomputable def R_LOAD_OHMS : Real := (24.0 : Real)
noncomputable def C_BULK_FARADS : Real := (2.2e-4 : Real)
noncomputable def C_BYPASS_FARADS : Real := (1e-07 : Real)

axiom circuit  : Real
axiom supply_current (v : Real) (r_load : Real) : Real
axiom bulk_tau (r_load : Real) (c_bulk : Real) : Real

-- ── current_at_zero_supply ──

noncomputable def current_at_zero_supply (r_load : Real) : Real :=
  ((0 : Real) / r_load)

theorem power_zero_supply_zero_current (r_load : Real)
    (h1 : (r_load > (0 : Real))) :
    ((current_at_zero_supply r_load) = (0 : Real)) := by
  unfold current_at_zero_supply
  have hne : r_load ≠ 0 := ne_of_gt h1
  rw [div_def 0 r_load hne]
  exact zero_mul (1 / r_load)

-- ── bulk_tau_proof ──

noncomputable def bulk_tau_proof (r_load : Real) (c_bulk : Real) : Real :=
  (r_load * c_bulk)

theorem power_bulk_tau_positive (r_load : Real) (c_bulk : Real)
    (h1 : (r_load > (0 : Real)))
    (h2 : (c_bulk > (0 : Real))) :
    ((bulk_tau_proof r_load c_bulk) > (0 : Real)) := by
  unfold bulk_tau_proof
  exact mul_pos h1 h2
