-- Generated by the EML-lang Lean backend, then sorry-closed by hand
-- against MachLib.Forge.
-- Source module: maglev_sensor
-- Source file:   forge/examples/maglev/sensor.eml
-- Verified fns:  position_at_offset, filter_tau_proof
--
-- Phase E5 of the math-to-manufactured-PCB pipeline (maglev
-- bring-up). Both obligations on the analog sensor signal chain
-- close against MachLib's axiomatic real-number layer.

import MachLib.EML
import MachLib.Trig
import MachLib.Forge

open MachLib
open MachLib.Real

noncomputable def HALL_SCALE : Real := (1.4 : Real)
noncomputable def R_AA_OHMS : Real := (1000.0 : Real)
noncomputable def C_AA_FARADS : Real := (1e-07 : Real)
noncomputable def V_OFFSET : Real := (2.5 : Real)
noncomputable def MM_PER_VOLT : Real := (5.0 : Real)
noncomputable def POSITION_MIN_MM : Real := (-(10.0 : Real))
noncomputable def POSITION_MAX_MM : Real := (10.0 : Real)

axiom circuit  : Real
axiom filter_tau (r_ohms : Real) (c_farads : Real) : Real
axiom adc_voltage_to_position (adc_v : Real) : Real
axiom position_to_adc_voltage (pos_mm : Real) : Real

-- ── position_at_offset ──
-- (V_OFFSET - V_OFFSET) * MM_PER_VOLT = 0
-- chain: sub_def -> add_neg -> zero_mul

noncomputable def position_at_offset  : Real :=
  ((V_OFFSET - V_OFFSET) * MM_PER_VOLT)

theorem sensor_zero_offset_zero_position  :
    ((position_at_offset ) = (0 : Real)) := by
  unfold position_at_offset
  rw [sub_def, add_neg]
  exact zero_mul MM_PER_VOLT

-- ── filter_tau_proof ──
-- r > 0, c > 0  ->  r * c > 0  via mul_pos

noncomputable def filter_tau_proof (r : Real) (c : Real) : Real :=
  (r * c)

theorem sensor_filter_tau_positive (r : Real) (c : Real)
    (h1 : (r > (0 : Real)))
    (h2 : (c > (0 : Real))) :
    ((filter_tau_proof r c) > (0 : Real)) := by
  unfold filter_tau_proof
  exact mul_pos h1 h2
